Repository hrydgard/ppsspp, pull requests merged in 2019-04, with the labels that each got.

#11956 Correct vmfvc/vmtvc decoding, prefixes on vsgn, vdot, vhdp, and matrix init
  Core/MIPS/ARM/ArmCompVFPU.cpp
  Core/MIPS/ARM64/Arm64CompVFPU.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
  Core/MIPS/x86/CompVFPU.cpp
Labels: CPU emulation

#11954 Fix prefix and size handling for vsbx, vsocp, and integer conv ops
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
Labels: CPU emulation

#11955 Correct prefixes for several swizzled ops, use zero for invalid
  Core/MIPS/MIPSIntVFPU.cpp
Labels: CPU emulation

#11959 Improve prefixes for vwbn/vlgb/vmin/vmax/vqmul/vcrsp and 2 ops
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
Labels: CPU emulation

#11948 Make vfad/vavg/vtfm ops more accurate
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
Labels: CPU emulation

#11972 Masked PSP Memory support for the AArch64 Dynarec
  Core/MIPS/ARM64/Arm64Asm.cpp
  Core/MIPS/ARM64/Arm64CompALU.cpp
  Core/MIPS/ARM64/Arm64CompFPU.cpp
  Core/MIPS/ARM64/Arm64CompLoadStore.cpp
  Core/MIPS/ARM64/Arm64CompVFPU.cpp
  Core/MIPS/ARM64/Arm64RegCache.cpp
Labels: arm64jit

#11970 Added IO Timing Method option for RetroArch PPSSPP Core.
  libretro/libretro.cpp
Labels: I/O Timing, Libretro

#10783 Remove "sound speed hack"
  Core/Config.cpp
  Core/Config.h
  Core/HW/SimpleAudioDec.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  UI/SavedataScreen.cpp
  libretro/libretro.cpp
Labels: Audio
