Repository hrydgard/ppsspp, pull requests merged in 2019-12, with the labels that each got.

#12462 Vulkan: Enable renderpass merging for all games
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Vulkan/GPU_Vulkan.cpp
  assets/compat.ini
  ext/native/gfx_es2/draw_buffer.cpp
  ext/native/thin3d/VulkanQueueRunner.cpp
  ext/native/thin3d/VulkanRenderManager.h
Labels: Vulkan

#12509 Fix Pangya(KS).
  Core/FileSystems/MetaFileSystem.cpp
  Core/HLE/sceIo.cpp
Labels: I/O

#12517 Touch control grid snap
  Core/Config.cpp
  Core/Config.h
  UI/TouchControlLayoutScreen.cpp
Labels: Input/Controller
