Repository hrydgard/ppsspp, pull requests merged in 2020-12, with the labels that each got.

#13733 Apple M1 - initial work
  CMakeLists.txt
  cmake/sdl/FindSDL2.cmake
Labels: Platform-specific (Mac OS X)

#13736 sz must be longer than target string
  Common/ArmCPUDetect.cpp
Labels: Platform-specific (Mac OS X)

#13744 Avoid potential crash without storage permissions
  UI/MainScreen.cpp
Labels: Platform-specific (Android)

#13748 Only create icon for specify target
  CMakeLists.txt
Labels: Platform-specific (iOS)

#13757 Use system time format on savedata aswell
  UI/SavedataScreen.cpp
Labels: User Interface

#13760 Fix car lighting issues in DiRT 2.
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GPUCommon.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  assets/compat.ini
Labels: GE emulation

#13763 Turn off vertex range culling in bezier/spline calls.
  Common/GPU/ShaderWriter.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUState.h
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation, Spline/Bezier tesselation

#13769 Minor cleanups in GPU feature detection, and restore a lost compat hack.
  Common/Data/Format/PNGLoad.cpp
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/thin3d.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUState.h
  GPU/Software/SoftGpu.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  Qt/QtMain.cpp
Labels: OpenGL, Vulkan

#13775 Apple driver GLSL bug workaround
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/thin3d.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.h
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  unittest/TestShaderGenerators.cpp
Labels: GE emulation, Platform-specific (iOS)

#13792 Fix UWP audio and a hang bug
  UI/GameSettingsScreen.cpp
  UWP/StorageFileLoader.cpp
  UWP/XAudioSoundStream.cpp
Labels: Platform-specific (UWP)

#13791 Linux: Properly avoid committing address space for large mmap().
  Common/MemArenaPosix.cpp
Labels: Platform-specific (Linux/POSIX)

#13798 Add some ThreadManForKernel nids
  Core/HLE/sceKernel.cpp
Labels: HLE/Kernel

#13776 Add stack value in scempeg and scepsmf from jpcsp
  Core/HLE/sceMpeg.cpp
  Core/HLE/scePsmf.cpp
Labels: PSMF / MPEG

#13241 Added some missing OpenPSID nids and some stub functions
  Core/HLE/HLETables.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceOpenPSID.cpp
  Core/HLE/sceOpenPSID.h
Labels: Networking / adhoc

#13809 [Adhoc] - Fixed an issue where sometimes a player unable to join a host on Warriors Orochi 2
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhoc.h
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#13802 Mpeg: Add warm up staff
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#13817 Split the DepthRangeHack compat setting into itself and DisableRangeCulling
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  assets/compat.ini
Labels: GE emulation, Guardband / Range Culling

#13826 Using MSG_TRUNC along with MSG_PEEK as a precaution of a possible buffer overflow when peeking recv buffer
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#13831 Debugger: Tweaks to memory read/write APIs
  Common/Data/Encoding/Base64.cpp
  Common/Data/Encoding/Base64.h
  Common/Net/Sinks.cpp
  Common/Net/Sinks.h
  Core/Debugger/WebSocket.cpp
  Core/Debugger/WebSocket/MemorySubscriber.cpp
  Core/Debugger/WebSocket/MemorySubscriber.h
Labels: API
