Repository hrydgard/ppsspp, pull requests merged in 2020-04, with the labels that each got.

#12790 Use consistent state for render mode and hw transform
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/FramebufferCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SplineCommon.cpp
  GPU/Common/SplineCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPUCommon.cpp
  GPU/Software/TransformUnit.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: GE emulation

#12794 Net: Correct pool allocation
  Core/HLE/sceNet.cpp
Labels: Networking / adhoc

#12713 Travis: build libretro android
  .travis.sh
  .travis.yml
  b.sh
Labels: Libretro

#12800 x86jit: Force INF * 0 to +NAN
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/MIPSInt.cpp
  Core/MIPS/x86/CompFPU.cpp
Labels: x86jit

#12803 GLES: Re-enable non-float depal shader path
  GPU/GLES/DepalettizeShaderGLES.cpp
  GPU/GLES/DepalettizeShaderGLES.h
  GPU/GLES/GPU_GLES.cpp
Labels: OpenGL

#12816 Implement Xinput vibration CWCheat (PPSSPP specific 0xA code type)
  Core/CwCheat.cpp
  Core/CwCheat.h
  Core/HLE/sceCtrl.cpp
  Core/HLE/sceCtrl.h
  Windows/XinputDevice.cpp
  Windows/XinputDevice.h
Labels: Cheats

#12839 GLES: Disable range culling on old Tegras, they seem to misbehave
  ext/native/thin3d/thin3d_gl.cpp
Labels: OpenGL, Platform-specific (Android)

#12225 Rebased: Wrap some SysMemForKernel's nids, fixing #7960
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/HLE/FunctionWrappers.h
  Core/HLE/HLETables.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  Core/HLE/sceKernelHeap.cpp
  Core/HLE/sceKernelHeap.h
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceKernelMemory.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: HLE/Kernel

#12856 Vulkan: Discard negative width/height framebuffer blits.
  GPU/Vulkan/FramebufferVulkan.cpp
Labels: Vulkan
