Repository hrydgard/ppsspp, pull requests merged in 2020-11, with the labels that each got.

#13609 Merge GLSL and HLSL fragment shader generators into one generic
  CMakeLists.txt
  Common/GPU/D3D9/D3D9ShaderCompiler.cpp
  Common/GPU/D3D9/D3D9ShaderCompiler.h
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/Net/Resolve.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/ShaderCommon.cpp
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderId.h
  GPU/Common/ShaderTranslation.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/D3D11/StencilBufferD3D11.cpp
  GPU/Directx9/DepalettizeShaderDX9.cpp
  GPU/Directx9/DepalettizeShaderDX9.h
  GPU/Directx9/FragmentShaderGeneratorHLSL.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/Directx9/StencilBufferDX9.cpp
  GPU/Directx9/VertexShaderGeneratorHLSL.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/FragmentShaderGeneratorGLES.h
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/StateMappingGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/VertexShaderGeneratorGLES.cpp
  GPU/GLES/VertexShaderGeneratorGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Software/SoftGpu.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
  GPU/Vulkan/VulkanUtil.cpp
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#13610 Remove a redundant bit from vertex shader IDs.
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Directx9/VertexShaderGeneratorHLSL.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/VertexShaderGeneratorGLES.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: GE emulation

#13611 Merge GLSL and HLSL vertex shader generators
  CMakeLists.txt
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderCommon.cpp
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderUniforms.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.h
  GPU/D3D11/D3D11Util.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/Directx9/VertexShaderGeneratorHLSL.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/VertexShaderGeneratorGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#13616 Enable "masked memory" on iOS
  Core/MIPS/ARM64/Arm64Asm.cpp
  Core/MIPS/ARM64/Arm64CompLoadStore.cpp
  Core/MIPS/ARM64/Arm64CompVFPU.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MemMap.cpp
  Core/MemMap.h
Labels: Platform-specific (iOS)

#13622 Move ShaderWriter to Common
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  GPU/Common/ShaderCommon.cpp
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderTranslation.cpp
  GPU/Common/ShaderTranslation.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.h
  GPU/GLES/DepalettizeShaderGLES.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Software/SoftGpu.cpp
  UI/GPUDriverTestScreen.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: Code Cleanup, GE emulation

#13623 Show an error on screen if a shader fails to compile.
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.h
  Common/GPU/thin3d.h
  GPU/GLES/ShaderManagerGLES.cpp
  Windows/GPU/WindowsGLContext.cpp
  android/jni/app-android.cpp
  ios/ViewController.mm
Labels: GE emulation, OpenGL

#13624 More minor cleanups
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  GPU/Common/ShaderTranslation.cpp
  GPU/Common/ShaderTranslation.h
  UI/GPUDriverTestScreen.cpp
Labels: Code Cleanup

#13626 More framebuffer code cleanup
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/DepthBufferGLES.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPUState.h
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup

#13630 Fix off by one in Qt
  Qt/mainwindow.cpp
Labels: Qt

#13629 Move the shader language feature detection to the draw context
  Common/Common.vcxproj.filters
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Core/CoreParameter.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  GPU/Common/ShaderCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  headless/Headless.cpp
Labels: Code Cleanup

#13634 Device lost improvements, unify BindFramebufferAsColorTexture
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup

#13636 Reinterpret framebuffer formats as needed. Outrun reflections partial fix
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Collections/Slice.h
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/Opcode.h
  GPU/Common/ColorReinterpret.cpp
  GPU/Common/ColorReinterpret.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/ReinterpretFramebuffer.h
  GPU/Common/ShaderId.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/ge_constants.h
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  assets/compat.ini
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#13637 Shaderblend code cleanup
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/Common/ShaderId.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPUState.h
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/StateMappingVulkan.cpp
  ext/native/tools/atlastool.cpp
  ext/native/tools/atlastool/atlastool.vcxproj
Labels: Code Cleanup, GE emulation

#13640 Fix car reflections in Outrun by implementing per-bit color masking
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/ShaderWriter.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPUCommon.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
  assets/compat.ini
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#13645 Mpeg:Revert part of https://github.com/hrydgard/ppsspp/commit/fa59be7e5db1526d07de75f6d7c14b94e98809e6
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#13646 Framebuffer fetch fixes
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/GLES/GPU_GLES.cpp
Labels: GE emulation, OpenGL

#13654 Expose the "Lower resolution for effects" setting in libretro.
  libretro/libretro.cpp
Labels: Libretro

#13656 Assorted OpenGL fixes
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  UI/DevScreens.cpp
Labels: GE emulation, OpenGL

#13659 Mpeg:Improves the support of multiple streams video.
  Core/HLE/sceMpeg.cpp
  Core/HW/MediaEngine.cpp
  Core/HW/MediaEngine.h
Labels: PSMF / MPEG

#13663 Corrects the number of added packets returned by sceMpegRingbufferPut.
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#13669 Better GLSL version handling with OpenGL
  Common/GPU/D3D9/D3D9StateCache.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/ShaderWriter.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  GPU/Common/FragmentShaderGenerator.cpp
Labels: OpenGL

#13695 Add developer setting "Show on-screen messages". Uncheck to hide them.
  Core/Config.cpp
  Core/Config.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GameSettingsScreen.cpp
Labels: User Interface

#13701 Mpeg:Checks autual available space before putting data.
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#13703 Guess at a fix for #13698 - sceKernelThreadGetExitStatus probably takes some cycles.
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelThread.cpp
  Core/HLE/sceKernelThread.h
Labels: HLE/Kernel

#13706 Add back the old implementation of vfpu_sin/cos/sincos.
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/MIPS/MIPSVFPUUtils.cpp
  Core/MIPS/MIPSVFPUUtils.h
  Core/System.cpp
  assets/compat.ini
Labels: CPU emulation

#13713 Mpeg:Correctly handle stuffing data of pack header.
  Core/HW/MpegDemux.cpp
Labels: PSMF / MPEG

#13711 Microphone:Improves the support of microphone.
  Core/HLE/sceAudio.cpp
  Core/HLE/sceUsbCam.cpp
  Core/HLE/sceUsbMic.cpp
  Core/HLE/sceUsbMic.h
  Windows/CaptureDevice.cpp
  Windows/CaptureDevice.h
Labels: Audio

#13720 Enable color reinterpret for Ultimate Ghosts & Goblins
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  assets/compat.ini
Labels: GE emulation

#13721 Change ltn x font
  assets/flash0/font/ltn0.pgf
  assets/flash0/font/ltn10.pgf
  assets/flash0/font/ltn11.pgf
  assets/flash0/font/ltn12.pgf
  assets/flash0/font/ltn13.pgf
  assets/flash0/font/ltn14.pgf
  assets/flash0/font/ltn15.pgf
  assets/flash0/font/ltn2.pgf
  assets/flash0/font/ltn8.pgf
  assets/flash0/font/ltn9.pgf
Labels: PGF / sceFont
