Repository hrydgard/ppsspp, pull requests merged in 2021-05, with the labels that each got.

#14422 Small warning fixes
  Common/Data/Format/ZIMLoad.cpp
  Common/Log.cpp
  UWP/UI_UWP/UI_UWP.vcxproj
Labels: Code Cleanup

#14435 Ctrl: Apply analog limiter to real sticks too
  UI/EmuScreen.cpp
  UI/EmuScreen.h
Labels: Input/Controller

#14438 Core: Leave delay slot when re-entering jit
  Core/MIPS/MIPS.cpp
Labels: Debugger

#14466 [Adhoc] Fix possible crash issue on blocking socket implementation.
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#14478 SDL: Ignore commas in joystick names
  SDL/SDLJoystick.cpp
Labels: SDL2

#14489 Remove multiple config search paths
  Common/File/FileUtil.cpp
  Core/Config.cpp
  Core/Config.h
  Core/System.h
  UI/NativeApp.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
Labels: Code Cleanup
