Repository hrydgard/ppsspp, pull requests merged in 2021-04, with the labels that each got.

#14335 [Adhoc] Prevent flooding Adhoc Server with connection attempts
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhoc.h
  Core/HLE/sceNet.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/Util/PortManager.cpp
Labels: Networking / adhoc

#14342 [AdhocMatching] Fix crashing issue when leaving a multiplayer game room
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#14344 Include more memory info in debugger tags
  Core/Debugger/MemBlockInfo.cpp
  Core/Debugger/MemBlockInfo.h
  Core/Dialog/SavedataParam.cpp
  Core/Dialog/SavedataParam.h
  Core/HLE/ReplaceTables.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceDeflt.cpp
  Core/HLE/sceDmac.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HW/SasAudio.cpp
  Core/MIPS/MIPSAsm.cpp
  Core/MemMapHelpers.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPUCommon.cpp
  GPU/Software/SoftGpu.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/ppsspp.rc
  Windows/resource.h
Labels: Debugger

#14347 UI: Add BG animation for recent games
  Core/Config.h
  Core/ConfigValues.h
  UI/GameInfoCache.h
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MiscScreens.cpp
  UI/TextureUtil.cpp
Labels: User Interface

#14345 [APctl] Fix stuck issue when scanning AP to Recruit on MGS:PW
  Core/HLE/sceNet.cpp
  Core/HLE/sceNet.h
Labels: Networking / adhoc

#14354 Disable spvremapper from glslang by default, we don't use it.
  ext/CMakeLists.txt
Labels: Platform-specific (Linux/POSIX)

#13970 Correct UMD stat waiting when changing discs
  Core/HLE/sceUmd.cpp
Labels: I/O

#14368 Stop using Off as terminator for postshaders
  Core/Config.cpp
  Core/CwCheat.cpp
  GPU/Common/PostShader.cpp
  GPU/Common/PresentationCommon.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  Windows/MainWindowMenu.cpp
Labels: Code Cleanup

#14367 Kernel: Define most reported missing kernel funcs
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelModule.cpp
Labels: Kernel mode

#14374 Rtc: Cleanup and simplify date struct handling
  Core/HLE/sceKernelMbx.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceRtc.cpp
Labels: Code Cleanup

#14385 UI: Load BG image properly on init
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
Labels: User Interface

#14387 Change pointer ID allocation on iOS. Fixes part of #14240
  Common/UI/UIScreen.cpp
  ios/ViewController.mm
Labels: Platform-specific (iOS)

#14379 Cleanup libretro options
  libretro/libretro.cpp
Labels: Libretro

#14358 Add basic APIs for managing memory info tagging
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Debugger/MemBlockInfo.cpp
  Core/Debugger/MemBlockInfo.h
  Core/Debugger/WebSocket.cpp
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Core/Debugger/WebSocket/MemoryInfoSubscriber.cpp
  Core/Debugger/WebSocket/MemoryInfoSubscriber.h
  Core/Debugger/WebSocket/WebSocketUtils.cpp
  Core/Debugger/WebSocket/WebSocketUtils.h
  Core/HLE/sceAtrac.cpp
  Core/HW/SasAudio.cpp
  Core/MemMap.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
Labels: Debugger

#14363 [Adhoc] An attempt to fix GetIPList on Linux/Unix
  Common/Net/Resolve.cpp
Labels: Networking / adhoc

#14389 Reporting: Avoid generated homebrew IDs
  Common/Net/HTTPClient.cpp
  Core/PSPLoaders.cpp
  Core/Reporting.cpp
Labels: User Interface

#14398 Debugger: Mark ELF sections as suballocations
  Core/ELF/ElfReader.cpp
  Core/FileSystems/ISOFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlMemView.cpp
Labels: Debugger

#14399 Debugger: Show string in status bar for li, etc.
  Core/Debugger/DisassemblyManager.cpp
  Core/Debugger/DisassemblyManager.h
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
Labels: Debugger

#14408 Windows: Reduce focus juggling on game start
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/Debugger_Disasm.h
  Windows/MainWindow.cpp
  Windows/W32Util/DialogManager.cpp
  Windows/W32Util/DialogManager.h
Labels: Platform-specific (Windows)

#14406 Apply integer math narrowing before VFPU sin/cos
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/MIPS/MIPSVFPUUtils.cpp
  Core/MIPS/MIPSVFPUUtils.h
  Core/MIPS/x86/Jit.cpp
  Core/System.cpp
  assets/compat.ini
  unittest/JitHarness.cpp
  unittest/UnitTest.cpp
Labels: CPU emulation

#14411 FileUtil cleanup
  Common/CPUDetect.cpp
  Common/Data/Format/JSONReader.cpp
  Common/Data/Text/I18n.cpp
  Common/File/DirListing.cpp
  Common/File/DirListing.h
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Common/File/PathBrowser.cpp
  Common/File/PathBrowser.h
  Common/File/VFS/AssetReader.cpp
  Common/File/VFS/AssetReader.h
  Common/File/VFS/VFS.cpp
  Common/File/VFS/VFS.h
  Common/GPU/OpenGL/GLSLProgram.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileLoaders/LocalFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/HLE/Plugins.cpp
  Core/Reporting.cpp
  GPU/Common/PostShader.cpp
  UI/CwCheatScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/InstallZipScreen.cpp
  UI/MainScreen.cpp
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/NativeApp.cpp
  UI/RemoteISOScreen.cpp
  UI/SavedataScreen.cpp
  UWP/StorageFileLoader.cpp
  UWP/UWPHost.cpp
  Windows/WindowsHost.cpp
  headless/Compare.cpp
Labels: Code Cleanup
