Repository hrydgard/ppsspp, pull requests merged in 2021-01, with the labels that each got.

#13835 If we are reporting a small memstick size, but data is bigger, lie.
  Core/HW/MemoryStick.cpp
Labels: Saving issue

#13850 Cleanup some warnings and a logger shutdown crash
  Common/Buffer.cpp
  Common/LogManager.cpp
  Common/Math/expression_parser.cpp
  Common/Net/HTTPClient.cpp
  Common/Net/HTTPHeaders.cpp
  Common/Net/HTTPServer.cpp
  Common/Net/Sinks.cpp
  UI/MainScreen.cpp
  UI/NativeApp.cpp
  Windows/DinputDevice.cpp
  Windows/DinputDevice.h
  android/android-ndk-profiler/Android.mk
  android/android-ndk-profiler/COPYING
  android/android-ndk-profiler/README.mkd
  android/android-ndk-profiler/armeabi-v7a/libandroid-ndk-profiler.a
  android/android-ndk-profiler/armeabi/libandroid-ndk-profiler.a
  android/android-ndk-profiler/prof.h
  android/jni/Android.mk
  android/jni/Locals.mk
  headless/Headless.cpp
Labels: Code Cleanup

#13855 Remove "Null" GPU and enable softgpu without a backend
  .github/workflows/build.yml
  CMakeLists.txt
  Core/CoreParameter.h
  Core/Util/PPGeDraw.cpp
  GPU/GPU.cpp
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Null/NullGpu.cpp
  GPU/Null/NullGpu.h
  GPU/Software/Sampler.cpp
  GPU/Software/SoftGpu.cpp
  android/jni/Android.mk
  android/jni/TestRunner.cpp
  headless/Headless.cpp
  headless/WindowsHeadlessHost.cpp
  libretro/LibretroGraphicsContext.cpp
  libretro/LibretroGraphicsContext.h
  libretro/Makefile.common
Labels: Code Cleanup

#13863 Bleach Soul Carnival. Disable the "First Frame Readback" compat setting.
  assets/compat.ini
Labels: GE emulation

#13867 UI: Use "Details" for upgrade outside Win/Android
  UI/MainScreen.cpp
Labels: User Interface

#13866 SaveState: Allow rewind on mobile
  Core/KeyMap.cpp
  Core/SaveState.cpp
Labels: User Interface

#13857 iOS: Expose iOS 12.1+/13/14 buttons
  ios/ViewController.mm
Labels: Input/Controller, Platform-specific (iOS)

#13874 Initialize/Deinitialize the shader translation system once globally.
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/ShaderTranslation.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Software/SoftGpu.cpp
  UI/NativeApp.cpp
Labels: User Interface

#13883 Fix adding extra new line on checkbox change
  UI/CwCheatScreen.cpp
Labels: Cheats

#13878 Save on game start
  UI/MainScreen.cpp
Labels: User Interface

#13885 Android: Add button to easily switch to SD card directory.
  Common/File/PathBrowser.cpp
  Common/System/System.h
  Common/UI/View.cpp
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/MainScreen.cpp
  UI/MainScreen.h
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/assets/ui_atlas.meta
  android/assets/ui_atlas.zim
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/NativeApp.java
  assets/ui_atlas.meta
  assets/ui_atlas.zim
  atlasscript.txt
  headless/Headless.cpp
  ios/main.mm
  libretro/libretro.cpp
  source_assets/image/buttons.svg
  source_assets/image/fullscreen.png
  source_assets/image/home.png
  source_assets/image/restore.png
  source_assets/image/sdcard.png
  source_assets/image/umd256.png
  source_assets/image/umd48.png
  unittest/UnitTest.cpp
Labels: User Interface

#13891 add assets to ubuntu build artifact
  .github/workflows/build.yml
Labels: Platform-specific (Linux/POSIX), SDL2

#13893 Fullscreen toggle button (windows-only for now)
  Common/UI/View.h
  UI/MainScreen.cpp
  UI/MainScreen.h
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Platform-specific (Windows)

#13894 [Adhoc Matching] Fix Lord of Arcana
  Core/HLE/proAdhoc.cpp
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#13895 Use the same logic of game setting for main menu full screen
  UI/MainScreen.cpp
Labels: User Interface

#13898 Add Browse... button to Android game browser
  Common/Net/URL.cpp
  UI/MainScreen.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Platform-specific (Android)

#13900 Correct flags for SetCtrlVFPUReg
  Core/MIPS/ARM/ArmCompALU.cpp
  Core/MIPS/ARM/ArmCompFPU.cpp
  Core/MIPS/ARM/ArmCompLoadStore.cpp
  Core/MIPS/IR/IRCompALU.cpp
  Core/MIPS/IR/IRCompFPU.cpp
  Core/MIPS/IR/IRCompLoadStore.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/x86/CompFPU.cpp
  Core/MIPS/x86/CompLoadStore.cpp
Labels: IRInterpreter

#13902 UI: Cleanup Windows header in MainScreen.cpp
  Common/Net/HTTPClient.cpp
  Common/Net/HTTPClient.h
  Common/System/System.h
  Core/Util/GameManager.cpp
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/MainScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
  ios/main.mm
Labels: Code Cleanup

#13908 Fix IR issue in Persona 3
  Core/MIPS/IR/IRPassSimplify.cpp
Labels: IRInterpreter

#13924 VK: Re-apply the old Adreno driver bug workaround. Fixes #13910.
  GPU/Common/FragmentShaderGenerator.cpp
Labels: Adreno GPU, Vulkan

#13925 Fix Stuck issue on some games when Failed to connect to Adhoc Server (faked success)
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#13935 There's little reason to build at O3, so let's just not. Changing to O2.
  CMakeLists.txt
Labels: Platform-specific (Linux/POSIX)

#13911 Enable BlockTransferAllowCreateFB for Gradius Collection
  assets/compat.ini
Labels: GE emulation

#13936 iOS CMake fixes and new --ios-xcode ./b.sh command.
  CMakeLists.txt
  b.sh
  ios/ViewController.mm
Labels: Platform-specific (iOS)

#13928 Adds two new tests to GPU driver test screen: Adreno shader logic test and flat shading
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/Render/DrawBuffer.cpp
  Common/Render/DrawBuffer.h
  Common/UI/Context.cpp
  Common/UI/Context.h
  GPU/Common/FragmentShaderGenerator.cpp
  UI/GPUDriverTestScreen.cpp
  UI/GPUDriverTestScreen.h
Labels: GE emulation, OpenGL, User Interface, Vulkan

#13941 GPU: Fix safe size checks when rect offscreen
  GPU/Common/SoftwareTransformCommon.cpp
Labels: GE emulation

#13944 Vulkan: Prevent scaling shader leak
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan

#13947 Kernel: Adjust sceKernelGetThreadExitStatus timing
  Core/HLE/sceKernelThread.cpp
Labels: Code Cleanup

#13962 PPGe: Scale down by worst of window/internal res
  Core/Util/PPGeDraw.cpp
Labels: HLE/Kernel

#13959 Resample mp3 in 32000Hz
  Core/HLE/sceMp3.cpp
Labels: Audio, MP3

#13967 [adhoc] Fix The Warriors
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#13969 Io: Don't allow async close while async busy
  Core/HLE/sceIo.cpp
Labels: I/O

#13972 GPU: Respect stencil write mask for 5551 buffers
  GPU/Common/GPUStateUtils.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: GE emulation

#13977 sceMp3Init:Add layerBits and versionBits and header information
  Core/HLE/sceMp3.cpp
Labels: MP3

#13974 Reporting: Expose CRC queue methods for other uses
  Core/Reporting.cpp
  Core/Reporting.h
Labels: User Interface

#13981 Cleanup some MP3 SDK version differences
  Core/HLE/sceMp3.cpp
  Core/HW/SimpleAudioDec.cpp
Labels: MP3

#13983 Remove duplicates from ThreadManForKernel
  Core/HLE/sceKernel.cpp
Labels: HLE/Kernel

#13986 Vulkan: Add MMPX upscaling texture shader
  GPU/Common/PostShader.cpp
  GPU/Common/PostShader.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  assets/shaders/defaultshaders.ini
  assets/shaders/tex_mmpx.csh
Labels: User Interface

#13998 (.gitlab-ci.yml) Add windows-x64 target
  .gitlab-ci.yml
  libretro/Makefile
  libretro/README_WINDOWS.txt
Labels: Libretro

#13999 Mpeg:Only allow firmware >= 3 for warmup
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#14009 jit: Make branch shift more obvious
  Core/MIPS/ARM/ArmCompBranch.cpp
  Core/MIPS/ARM64/Arm64CompBranch.cpp
  Core/MIPS/IR/IRCompBranch.cpp
  Core/MIPS/x86/CompBranch.cpp
Labels: Code Cleanup

#13997 [Adhoc] Fix connection issue on Dynasty Warriors (Shin Sangoku Musou) games
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhoc.h
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#14019 Fix logging flags
  UI/NativeApp.cpp
Labels: User Interface

#14023 Attempt to fix #14022
  Core/Font/PGF.cpp
Labels: PGF / sceFont

#14029 Io: Consistently use LE values of ISO entries
  Core/FileSystems/ISOFileSystem.cpp
Labels: Code Cleanup

#14030 Vulkan: Fix image layout issues after compute shader uploads.
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan

#14034 Ge: Restore saved context when ending a list
  Core/HLE/sceGe.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPUCommon.cpp
Labels: GE emulation

#14033 Mpeg:Only allow firmware >= 6 for warmup
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#14037 Add a command in developer tools to list and load framedumps from the web
  Common/Render/DrawBuffer.cpp
  Common/Render/DrawBuffer.h
  Common/UI/Context.cpp
  Common/UI/View.cpp
  Common/UI/ViewGroup.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.cpp
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MainScreen.h
  UI/UI.vcxproj.filters
Labels: GE emulation, User Interface

#14039 Core: Maintain frame dump disc ID in SFO
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileLoaders/LocalFileLoader.cpp
  Core/System.cpp
Labels: User Interface
