Repository hrydgard/ppsspp, pull requests merged in 2021-07, with the labels that each got.

#14107 [Adhoc] Replace the link to the Ad-hoc forums in Networking options to a PPSSPP Github Wiki page link
  UI/GameSettingsScreen.cpp
Labels: Networking / adhoc, User Interface

#14588 Vulkan: Use the mandatory-support RGB565 format and not the opposite one.
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan

#14589 Fix black screen on multiple libretro content loads.
  Common/Thread/ThreadManager.h
  libretro/libretro.cpp
Labels: Libretro

#14592 Break out EmuScreen's key/axis inputs to ControlMapper.cpp/h
  CMakeLists.txt
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/NativeApp.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Input/Controller

#14594 More control refactoring
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/Debugger/WebSocket/InputSubscriber.cpp
  Core/HLE/sceCtrl.cpp
  Core/HLE/sceCtrl.h
  UI/EmuScreen.cpp
  UI/GamepadEmu.cpp
  UI/NativeApp.cpp
  UI/TiltEventProcessor.cpp
  libretro/libretro.cpp
Labels: Input/Controller

#14596 Replace the "Test Analogs" screen with a new screen that lets you directly try the settings.
  Core/Config.cpp
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
Labels: Input/Controller

#14042 Implement basic depth texturing for OpenGL
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/GLES/DepthBufferGLES.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Depth Texture, GE emulation

#14598 Change default adhoc server
  Core/Config.cpp
  UI/GameSettingsScreen.cpp
Labels: Networking / adhoc

#14597 WASAPI: Survive switching to a mono device.
  UI/NativeApp.cpp
  UWP/XAudioSoundStream.cpp
  Windows/DSoundStream.cpp
  Windows/WASAPIStream.cpp
  Windows/WindowsAudio.h
Labels: Platform-specific (Windows)

#14599 Change the default port offset
  Core/Config.cpp
Labels: Networking / adhoc

#14603 Vulkan: Turn off all 16-bit formats if B5G6R5 format is not available.
  Common/GPU/Vulkan/VulkanContext.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Platform-specific (Linux/POSIX), Vulkan, intel gpu

#14605 Make the "Running Slow" warning a bit more lenient.
  Core/HLE/sceDisplay.cpp
Labels: User Interface

#14606 Fix bug in homebrew store with files with "." in their names.
  GPU/Vulkan/GPU_Vulkan.cpp
  UI/MainScreen.cpp
  UI/Store.cpp
  UI/Store.h
Labels: User Interface

#14609 Viewport fixes
  GPU/Common/GPUStateUtils.cpp
Labels: GE emulation, Vulkan

#14620 Implement the option for auto audio devices switching for Windows too
  UI/GameSettingsScreen.cpp
  Windows/WASAPIStream.cpp
Labels: Audio

#14623 Add i18n INIfile load on libretro startup
  libretro/libretro.cpp
Labels: Libretro

#14626 Make GetFilesInDir fully-featured enough to use in DirectoryFileSystem, clean it up
  Common/File/DirListing.cpp
  Common/File/DirListing.h
  Common/File/PathBrowser.cpp
Labels: Code Cleanup

#14627 Path and I/O fixes preparing for Android scoped storage
  Common/Data/Format/JSONReader.cpp
  Common/File/AndroidStorage.cpp
  Common/File/AndroidStorage.h
  Common/File/DirListing.h
  Common/File/DiskFree.cpp
  Common/File/DiskFree.h
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Common/File/Path.h
  Common/File/PathBrowser.h
  Common/File/VFS/AssetReader.cpp
  Common/File/VFS/VFS.cpp
  Common/GPU/OpenGL/GLSLProgram.cpp
  Core/Debugger/SymbolMap.cpp
  Core/Dialog/SavedataParam.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/DirectoryFileSystem.h
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/HLE/sceIo.cpp
  Core/SaveState.cpp
  Core/System.cpp
  Core/System.h
  GPU/Common/PostShader.cpp
  GPU/Common/PresentationCommon.cpp
  UI/MainScreen.cpp
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
Labels: I/O, Platform-specific (Android)

#14636 More scoped storage support work
  Common/File/AndroidStorage.cpp
  Common/File/AndroidStorage.h
  Core/FileSystems/DirectoryFileSystem.cpp
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
Labels: Platform-specific (Android)

#14639 Fix English language mapping after recent i18n additions.
  libretro/libretro.cpp
Labels: Libretro

#14638 Cleanup the ownership model in MetaFileSystem.
  Core/FileSystems/ISOFileSystem.h
  Core/FileSystems/MetaFileSystem.cpp
  Core/FileSystems/MetaFileSystem.h
  Core/HLE/sceIo.cpp
  Core/PSPLoaders.cpp
  Core/System.cpp
Labels: Code Cleanup

#14642 Merge a few more of the commits from #14619
  Common/File/AndroidStorage.cpp
  Common/File/AndroidStorage.h
  Common/File/FileUtil.cpp
  Common/File/Path.cpp
  Common/File/Path.h
  Common/Serialize/Serializer.h
  Core/FileLoaders/LocalFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/DirectoryFileSystem.h
  Core/FileSystems/FileSystem.h
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.h
  Core/HLE/sceIo.cpp
  Core/System.cpp
  Core/System.h
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
Labels: Code Cleanup, Platform-specific (Android)

#14644 Even more scoped storage commits
  Common/File/Path.cpp
  Core/FileLoaders/LocalFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/System.cpp
  UI/MainScreen.cpp
  UI/MainScreen.h
Labels: Platform-specific (Android)

#14649 Trim username on join as well
  Core/HLE/proAdhoc.cpp
Labels: User Interface

#14648 Detect CwCheat file UTF-8 BOM sequence and ignore it
  Core/CwCheat.cpp
Labels: Cheats
