Repository hrydgard/ppsspp, pull requests merged in 2021-08, with the labels that each got.

#14671 Make tap to customize translatable
  UI/TouchControlVisibilityScreen.cpp
Labels: User Interface

#14677 cmake: use vendor-neutral GL implementation when available
  CMakeLists.txt
Labels: Libretro

#14619 Enable scoped storage enforcement on Android 11+.
  Common/Data/Text/Parsers.cpp
  Common/Data/Text/Parsers.h
  Common/File/AndroidStorage.cpp
  Common/File/AndroidStorage.h
  Common/File/DiskFree.cpp
  Common/File/DiskFree.h
  Common/File/FileUtil.cpp
  Common/File/Path.cpp
  Common/File/Path.h
  Common/File/PathBrowser.cpp
  Common/File/PathBrowser.h
  Common/System/NativeApp.h
  Common/UI/Screen.cpp
  Core/Config.cpp
  Core/Config.h
  Core/Dialog/SavedataParam.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/HLE/sceCtrl.cpp
  Core/HLE/sceIo.cpp
  UI/DevScreens.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MainScreen.cpp
  UI/MemStickScreen.cpp
  UI/MemStickScreen.h
  UI/NativeApp.cpp
  Windows/W32Util/Misc.cpp
  Windows/W32Util/Misc.h
  android/AndroidManifest.xml
  android/build.gradle
  android/jni/AndroidContentURI.h
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
  unittest/UnitTest.cpp
Labels: Platform-specific (Android)

#14690 Improve translatability of memstick screen
  Common/UI/View.cpp
  Common/UI/View.h
  UI/MemStickScreen.cpp
Labels: Translation

#14679 Savestate load undo
  Core/Config.cpp
  Core/Config.h
  Core/SaveState.cpp
  Core/SaveState.h
  UI/PauseScreen.cpp
  UI/PauseScreen.h
Labels: User Interface

#14694 Scoped storage fixes
  Core/Config.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  android/AndroidManifest.xml
Labels: Platform-specific (Android)

#14695 Scoped load fix
  Core/Loaders.cpp
  Core/Loaders.h
  Core/System.cpp
  Core/Util/GameManager.cpp
  UI/GameInfoCache.cpp
  UI/MainScreen.cpp
  UI/SavedataScreen.cpp
  android/jni/AndroidContentURI.h
  unittest/UnitTest.cpp
Labels: Platform-specific (Android)

#14696 Allow to disable right analog diagonal
  Core/Config.cpp
  Core/Config.h
  UI/GamepadEmu.cpp
  UI/TouchControlVisibilityScreen.cpp
Labels: Input/Controller

#14697 Add undo last save as well
  Core/Config.cpp
  Core/Config.h
  Core/SaveState.cpp
  Core/SaveState.h
  UI/PauseScreen.cpp
  UI/PauseScreen.h
Labels: User Interface

#14705 Move focus when scrolling with page up/down or home/end
  Common/UI/Root.cpp
  Common/UI/View.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
Labels: User Interface

#14711 Sas: Add option to control reverb volume
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Core/HW/SasAudio.cpp
  Core/HW/SasReverb.cpp
  Core/HW/StereoResampler.cpp
  UI/GameSettingsScreen.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
Labels: Audio

#14713 First pass on using Display KHR, needs proper init flags
  CMakeLists.txt
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  libretro/LibretroVulkanContext.cpp
  libretro/libretro_vulkan.cpp
Labels: Vulkan, Libretro

#14722 Fix controls layout opacity
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#14718 Miscellaneous control/gamepad fixes
  Core/Config.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/ControlMappingScreen.cpp
  UI/DevScreens.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/InputDeviceState.java
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Input/Controller, User Interface

#14729 Fix cheat import on scoped storage
  Common/File/FileUtil.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  assets/lang/az_AZ.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/hr_HR.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/jv_ID.ini
  assets/lang/lo_LA.ini
  assets/lang/nl_NL.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Cheats

#14732 (Libretro) Set base_width/base_height to sane dimensions (480x272)
  libretro/libretro.cpp
Labels: Libretro

#14735 (Libretro) Switch back to earlier base_width/base_height values
  libretro/libretro.cpp
Labels: Libretro

#14744 Improve touch control layout screen
  UI/TouchControlLayoutScreen.cpp
Labels: Input/Controller, User Interface

#14745 Allow to disable chat button
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
Labels: Networking / adhoc, User Interface

#14747 Make touch layout position accurate
  UI/TouchControlLayoutScreen.cpp
Labels: Input/Controller, User Interface

#14749 Rename Vulkan externals
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanMemory.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/VulkanUtil.cpp
  libretro/libretro_vulkan.cpp
Labels: Vulkan, Libretro

#12530 Allow tilt input on Z instead of X
  Core/Config.cpp
  Core/Config.h
  UI/NativeApp.cpp
  UI/TiltAnalogSettingsScreen.cpp
  UI/TiltEventProcessor.cpp
Labels: Input/Controller

#14000 Add CRC32 calc
  UI/GameScreen.cpp
  UI/GameScreen.h
Labels: User Interface

#14751 More input fixes
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Platform-specific (Android), Input/Controller

#14753 Keyboard/gamepad navigation: Change the formula for scoring neighbors.
  Common/UI/ViewGroup.cpp
Labels: User Interface

#14759 Correct breakpoints in delay slots
  Core/Dialog/SavedataParam.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MIPS/x86/Jit.cpp
  Core/MIPS/x86/Jit.h
Labels: Debugger

#14764 More Android control fixes
  CMakeLists.txt
  Common/Input/InputState.cpp
  Common/Input/InputState.h
  Common/UI/Root.cpp
  Core/ControlMapper.cpp
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/KeyMap.cpp
  Core/KeyMap.h
  Core/KeyMapDefaults.cpp
  Core/KeyMapDefaults.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  Windows/XinputDevice.cpp
  android/jni/Android.mk
  android/src/org/ppsspp/ppsspp/InputDeviceState.java
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  libretro/Makefile.common
Labels: Platform-specific (Android), Input/Controller

#14767 Tweak defaults some more (no L2 on xbox pads..). Minor code cleanup.
  Core/KeyMap.cpp
  Core/KeyMapDefaults.cpp
  UI/EmuScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  android/src/org/ppsspp/ppsspp/InputDeviceState.java
Labels: Platform-specific (Android), Input/Controller

#14768 Fix the math in cardboard VR mode for wide aspect ratios
  GPU/Common/PresentationCommon.cpp
Labels: Platform-specific (Android)

#14769 Add a visual means of control mapping
  Common/Render/DrawBuffer.cpp
  Common/Render/DrawBuffer.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Common/UI/ViewGroup.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  Windows/MainWindowMenu.cpp
Labels: Input/Controller, User Interface

#14775 Debugger: Avoid infinite loop in disasm API
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
Labels: Debugger

#13107 Basic mappable motion gesture
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
Labels: Input/Controller

#14777 Handle OpenGL vertex shader generation failures better.
  GPU/GLES/ShaderManagerGLES.cpp
Labels: OpenGL

#14782 Support virtual button in touch gesture
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/ComboKeyMappingScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
Labels: Input/Controller

#14784 [Libretro] Small core options cleanup + create a new git-version.cpp instead of appending stuff in it
  libretro/Makefile.common
  libretro/README_WINDOWS.txt
  libretro/libretro.cpp
Labels: Libretro
