Repository hrydgard/ppsspp, pull requests merged in 2022-07, with the labels that each got.

#15639 [UI] Show a tip message when enabling "UPnP use original port" option.
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#15652 Replace Win32 file IO with UWP safe variants and add support for getting drives to UWP build
  .gitignore
  Common/File/DirListing.cpp
  Common/File/FileUtil.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileLoaders/LocalFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.cpp
  ext/libzip/zip_source_file_win32_utf16.c
Labels: Platform-specific (UWP)

#15658 Change theme color endianess in the ini
  Common/Data/Format/IniFile.cpp
  Common/Data/Text/Parsers.cpp
  UI/Theme.cpp
  assets/themes/defaultthemes.ini
Labels: User Interface

#15647 Remove unmotivated check preventing texture ini creation on mobile.
  Common/Render/Text/draw_text_uwp.cpp
  Common/System/System.h
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/GameSettingsScreen.cpp
  UI/MemStickScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  ios/main.mm
  libretro/libretro.cpp
Labels: User Interface

#15640 Disable ForceMax60FPS for GOW games and replace it with fixed 60 fps
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/ReplaceTables.cpp
  Core/HLE/sceDisplay.cpp
  Core/HLE/sceDisplay.h
  Core/MIPS/MIPSAnalyst.cpp
  assets/compat.ini
Labels: Game Bug, GE emulation, HLE/Kernel

#15671 Tweak the Mali stencil-test workaround to work for Surf's Up
  GPU/Common/ShaderId.cpp
  assets/compat.ini
Labels: Mali GPU, GE emulation

#15677 Show message if files are outside valid ISO
  Core/FileSystems/ISOFileSystem.cpp
Labels: User Interface

#15673 Vulkan fragment shaders: Don't opportunistically emit "layout (early_fragment_tests) in"
  GPU/Common/FragmentShaderGenerator.cpp
Labels: Vulkan, GE emulation

#15687 Add Zettai Zetsumei Toshi 3 bypass for softlock
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/ReplaceTables.cpp
  Core/MIPS/MIPSAnalyst.cpp
  assets/compat.ini
Labels: HLE/Kernel

#15691 Add a simple compat flag to workaround the Clone Wars issue, #12949
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/sceMpeg.cpp
  GPU/Common/TextureCacheCommon.cpp
  assets/compat.ini
Labels: GE emulation

#15696 Use the recent Clone Wars fix for Star Wars: Force Unleashed too
  assets/compat.ini
Labels: GE emulation

#15698 Osk: Allow upper/lower for all keyboards
  Core/Dialog/PSPOskDialog.cpp
Labels: HLE/Kernel

#15702 Mali driver bug workaround for driver 32+.
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/VertexShaderGenerator.cpp
Labels: Mali GPU, GE emulation

#15705 Main screen: Display .ppdmp filenames on buttons in grid mode
  UI/MainScreen.cpp
Labels: User Interface

#15711 (UWP) More Build Tweaks
  UWP/PPSSPP_UWP_TemporaryKey.pfx
  UWP/Package.appxmanifest
  UWP/PackageGold.appxmanifest
  UWP/PackageNormal.appxmanifest
  UWP/UWP.vcxproj
  UWP/UWP_TemporaryKey.pfx
Labels: Platform-specific (UWP)

#15719 Minor code cleanups
  Common/GPU/Vulkan/VulkanMemory.h
  Core/Util/PPGeDraw.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/D3D11/StencilBufferD3D11.cpp
  GPU/Directx9/StencilBufferDX9.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/Vulkan/StencilBufferVulkan.cpp
Labels: Code Cleanup

#15718 Split GetPointer into GetPointer and GetPointerWrite
  Core/ELF/ElfReader.cpp
  Core/FileSystems/ISOFileSystem.cpp
  Core/HLE/FunctionWrappers.h
  Core/HLE/ReplaceTables.cpp
  Core/HLE/proAdhoc.cpp
  Core/HLE/sceAdler.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAudiocodec.cpp
  Core/HLE/sceChnnlsv.cpp
  Core/HLE/sceDeflt.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceJpeg.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceKernelMsgPipe.cpp
  Core/HLE/sceKernelSemaphore.cpp
  Core/HLE/sceMd5.cpp
  Core/HLE/sceMp3.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceMt19937.cpp
  Core/HLE/sceNet.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/HLE/sceNp.cpp
  Core/HLE/scePauth.cpp
  Core/HLE/sceSha256.cpp
  Core/HW/MediaEngine.cpp
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  Core/HW/SimpleAudioDec.cpp
  Core/HW/SimpleAudioDec.h
  Core/MIPS/MIPSIntVFPU.cpp
  Core/MemMap.cpp
  Core/MemMap.h
  Core/MemMapFunctions.cpp
  Core/MemMapHelpers.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/GPUCommon.cpp
  GPU/Software/Rasterizer.cpp
  GPU/Software/Rasterizer.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Software/TransformUnit.h
  Windows/Debugger/CtrlMemView.cpp
  libretro/libretro.cpp
Labels: Code Cleanup

#15720 Add GPU stat for number of depth copies per frame
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
Labels: GE emulation

#15717 Allows "merging" render targets that overlap on the Y axis. Fixes Juiced 2
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/GPUState.h
  assets/compat.ini
Labels: GE emulation

#15721 Add tests for IR and optimize to Mov a bit more
  .gitignore
  CMakeLists.txt
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/MIPSAnalyst.cpp
  android/jni/Android.mk
  unittest/TestIRPassSimplify.cpp
  unittest/UnitTest.cpp
  unittest/UnitTests.vcxproj
  unittest/UnitTests.vcxproj.filters
Labels: IRInterpreter

#15722 Remove bool that was always true in state mapping.
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: Code Cleanup

#15724 Build: Update to NDK r21e
  .github/workflows/build.yml
  .github/workflows/manual_generate_apk.yml
Labels: Platform-specific (Android)

#15733 Fix bug in blue-to-alpha - alpha blending could be on when it shouldn't be.
  Common/Render/Text/draw_text_android.cpp
  GPU/Common/GPUStateUtils.cpp
  assets/compat.ini
Labels: GE emulation

#15738 Add confirmation dialog when generating a new Mac address
  UI/GameSettingsScreen.cpp
Labels: Networking / adhoc

#15748 Windows: Add a simple window message to get the base pointer.
  Windows/MainWindow.cpp
Labels: Platform-specific (Windows)

#15723 D3D9 state cache cleanup
  Common/GPU/D3D9/D3D9StateCache.cpp
  Common/GPU/D3D9/D3D9StateCache.h
  Common/GPU/D3D9/thin3d_d3d9.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/Directx9/StencilBufferDX9.cpp
  GPU/Directx9/TextureCacheDX9.cpp
Labels: D3D9, Code Cleanup

#15749 Color format cleanups
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup

#15743 TextureCache "BuildTexture" refactor and cleanup
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/Vulkan/VulkanImage.cpp
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation, Code Cleanup

#15758 Simplify CPU upscaling code
  CMakeLists.txt
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureScalerCommon.cpp
  GPU/Common/TextureScalerCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/D3D11/TextureScalerD3D11.cpp
  GPU/D3D11/TextureScalerD3D11.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/Directx9/TextureScalerDX9.cpp
  GPU/Directx9/TextureScalerDX9.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/GLES/TextureScalerGLES.cpp
  GPU/GLES/TextureScalerGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  GPU/Vulkan/TextureScalerVulkan.cpp
  GPU/Vulkan/TextureScalerVulkan.h
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  Windows/MainWindowMenu.cpp
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#15760 Unify the LoadTextureLevel function between three of the backends
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation, Code Cleanup

#15765 Reporting: Disable when debugger methods used
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Core/Debugger/WebSocket/HLESubscriber.cpp
  Core/Debugger/WebSocket/MemorySubscriber.cpp
  Core/Reporting.cpp
  Core/Reporting.h
  GPU/GPUCommon.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/CtrlRegisterList.cpp
  Windows/MainWindow.cpp
Labels: Debugger

#15700 Track depth buffers separately from framebuffers to track previous use for copies
  Core/HLE/sceKernel.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
Labels: GE emulation

#15769 [UWP] Fixes UWP building issue after Retargeting Solution to a different SDK version
  UWP/UWP.vcxproj
Labels: Platform-specific (UWP)
