Repository hrydgard/ppsspp, pull requests merged in 2022-08, with the labels that each got.

#15727 Implement the PSP's equal-size mips "3D texturing"
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/D3D9StateCache.cpp
  Common/GPU/D3D9/D3D9StateCache.h
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/DepalettizeShaderGLES.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/FragmentTestCacheGLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUState.h
  GPU/Vulkan/DepalettizeShaderVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation

#15775 Use BlueToAlpha in more games instead of ReinterpretFramebuffers/ShaderColorBitmask
  assets/compat.ini
Labels: GE emulation

#15772 Add support for binding the depth buffer as a color target. Fixes Kurohyo depth sorting
  Common/GPU/Shader.cpp
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPU.h
  GPU/GPUState.h
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: Depth / Z, GE emulation

#15781 Blit feature detection cleanup
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GPUState.h
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: GE emulation, Code Cleanup

#15754 Unify stencil upload using thin3d
  CMakeLists.txt
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Shader.cpp
  Common/GPU/Shader.h
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Render/DrawBuffer.cpp
  Common/Render/DrawBuffer.h
  GPU/Common/DrawEngineCommon.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/StencilCommon.h
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/StencilBufferD3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/Directx9/StencilBufferDX9.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/GPUCommon.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/Vulkan/StencilBufferVulkan.cpp
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: GE emulation, Code Cleanup

#15782 Unify DrawActiveTexture
  CMakeLists.txt
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#15784 Unify BlitFramebuffer with a generic implementation
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/StencilCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: GE emulation, Code Cleanup

#15421 Implementing NpSigninDialog and Updating NP Library.
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Dialog/PSPNpSigninDialog.cpp
  Core/Dialog/PSPNpSigninDialog.h
  Core/HLE/FunctionWrappers.h
  Core/HLE/sceNp.cpp
  Core/HLE/sceNp.h
  Core/HLE/sceNp2.cpp
  Core/HLE/sceNp2.h
  Core/HLE/sceUtility.cpp
  Core/HLE/sceUtility.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Networking / adhoc

#15794 State handling reordering in D3D11 and D3D9 backends.
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/StateMappingGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: Code Cleanup

#15796 Fix feature check for wrapping of non-pow-2 textures
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/GLRenderManager.cpp
Labels: OpenGL

#15798 Cleanup some stencil upload things, clarify alpha skipping
  Common/GPU/OpenGL/GLFeatures.cpp
  Core/Dialog/PSPNpSigninDialog.cpp
  Core/HLE/ReplaceTables.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/StencilCommon.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/SoftGpu.h
Labels: Code Cleanup

#15804 Fix OpenGL ES crash in blit if copies not supported, fix raster blit
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: OpenGL, GE emulation

#15809 Headless: Cleanup unused/leak warnings
  Core/HLE/sceKernelThread.cpp
  headless/Headless.cpp
Labels: Code Cleanup

#15820 Switch the depal shader generator to use the ShaderWriter, fix some issues
  Common/GPU/Shader.cpp
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/DepalettizeCommon.cpp
  GPU/Common/DepalettizeCommon.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/Draw2D.cpp
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  UI/CwCheatScreen.cpp
  unittest/TestShaderGenerators.cpp
Labels: OpenGL

#15815 Depth blit using raster
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPU.h
  GPU/GPUState.h
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: D3D9, GE emulation

#15833 Debugger: Correct GE frame dump VRAM dirty flag
  Common/Net/HTTPHeaders.cpp
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Record.cpp
  GPU/Debugger/RecordFormat.h
Labels: Debugger

#15834 Fix some issues in Headless from Valgrind
  .github/workflows/build.yml
  Common/x64Emitter.cpp
  Core/HLE/sceAtrac.cpp
  Core/System.cpp
  GPU/Software/TransformUnit.cpp
  headless/SDLHeadlessHost.cpp
Labels: Code Cleanup

#15836 Correct a couple more Valgrind warnings in HLE
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceFont.cpp
Labels: Code Cleanup

#15837 Warning fixes
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/Vulkan/VulkanMemory.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/Render/TextureAtlas.cpp
  Core/Font/PGF.cpp
  Core/HLE/sceNp.cpp
  GPU/Common/TextureDecoder.cpp
  GPU/Common/TextureScalerCommon.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/VulkanUtil.h
  UI/ComboKeyMappingScreen.h
  ext/libpng17/arm/filter_neon_intrinsics.c
  ext/libpng17/arm/neon.h
Labels: Code Cleanup

#15844 GE Debugger: Correct base accounting in playback
  GPU/Common/DrawEngineCommon.cpp
  GPU/Debugger/Playback.cpp
  GPU/Software/TransformUnit.cpp
Labels: Debugger

#15839 GE debugger: Allow displaying two tabs at once, separate DL view
  Core/Config.cpp
  Core/Config.h
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/GEDebugger/GEDebugger.h
  Windows/GEDebugger/TabState.cpp
  Windows/GEDebugger/TabState.h
  Windows/W32Util/ContextMenu.h
  Windows/W32Util/DialogManager.h
  Windows/W32Util/Misc.cpp
  Windows/W32Util/TabControl.cpp
  Windows/W32Util/TabControl.h
  Windows/ppsspp.rc
  Windows/resource.h
Labels: User Interface, Debugger

#15847 Remove storage fileloader and storage folderbrowser, also re-add bin and elf [UWP]
  UWP/PPSSPP_UWPMain.cpp
  UWP/StorageFileLoader.cpp
  UWP/StorageFileLoader.h
  UWP/StorageFolderBrowser.cpp
  UWP/StorageFolderBrowser.h
  UWP/UWP.vcxproj
  UWP/UWP.vcxproj.filters
Labels: Platform-specific (UWP), Code Cleanup

#15846 Minor GPU code cleanup
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/ReinterpretFramebuffer.h
  GPU/Common/StencilCommon.cpp
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  unittest/TestShaderGenerators.cpp
Labels: Code Cleanup

#15848 Refcount shader modules properly in thin3d
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
Labels: Code Cleanup

#15850 Vulkan: Restore a forgotten dirty-tracking optimization
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: Vulkan

#15852 Remove DX9 namespace, other code cleanup
  Common/GPU/D3D9/D3D9StateCache.cpp
  Common/GPU/D3D9/D3D9StateCache.h
  Common/GPU/D3D9/thin3d_d3d9.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/Directx9/StateMappingDX9.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/DepthBufferGLES.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GPU.cpp
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  Windows/GPU/D3D9Context.cpp
Labels: Code Cleanup

#15851 After recording a GE dump, open an explorer window pointing at the file
  GPU/Debugger/Record.cpp
  Windows/GEDebugger/GEDebugger.cpp
Labels: Debugger

#15853 Framebuffer-bind sequence numbers
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GLES/DepthBufferGLES.cpp
  GPU/ge_constants.h
Labels: GE emulation, Code Cleanup

#15854 Use sequence numbers instead of a tracking array for depth buffers
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
Labels: GE emulation, Code Cleanup

#15855 Fix depth blit regression
  Common/GPU/D3D9/thin3d_d3d9.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
Labels: Code Cleanup

#15857 More flexible texture matching, bias matching by the bind sequence counters
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
Labels: GE emulation, Code Cleanup

#15862 Fix dependency of RISC-V targets on common JIT code
  CMakeLists.txt
Labels: RISC-V

#15869 Fix bug in framebuffer matching where the wrong format was checked
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GeConstants.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation

#15858 Copy color to depth, defer depth buffer copies
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUState.h
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: GE emulation

#15870 GPU: Dirty params when converting viewport state for sw transform
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: GE emulation

#15874 softgpu: Correct morph weight updates
  GPU/Software/SoftGpu.cpp
Labels: Software Rasterizer

#15873 softgpu: Flush on transfer to pending tex read
  GPU/Software/BinManager.cpp
  GPU/Software/BinManager.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Software/TransformUnit.h
Labels: Software Rasterizer

#15859 Allow binding depth as 565 by going through depal
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/CoreParameter.h
  GPU/Common/DepalettizeCommon.cpp
  GPU/Common/DepalettizeCommon.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Directx9/GPU_DX9.cpp
  assets/compat.ini
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#15881 Headless: Fix comparison for oversized buffers
  headless/Compare.cpp
  headless/Headless.cpp
Labels: Debugger

#15886 Rename DepalShaderCache to TextureShaderCache
  CMakeLists.txt
  GPU/Common/DepalettizeCommon.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/ShaderCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/TextureShaderCommon.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  UI/DevScreens.cpp
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: GE emulation, Code Cleanup

#15710 Implement smooth depal lookups for Test Drive's strange usage.
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/TextureShaderCommon.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPUState.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation

#15890 Minor framebuffer stuff (renaming, refactoring)
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
Labels: Code Cleanup

#15891 Use Draw2D for reinterpret and (partially) for depal
  Common/GPU/ShaderWriter.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/ReinterpretFramebuffer.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/TextureShaderCommon.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  unittest/TestShaderGenerators.cpp
Labels: GE emulation, Code Cleanup

#15894 GE Debugger: Record only one flip if display framebuf not changed, step on vsync
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/Debugger.h
  GPU/Debugger/Record.cpp
  GPU/Debugger/Record.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  Windows/GEDebugger/GEDebugger.cpp
  Windows/ppsspp.rc
  Windows/resource.h
Labels: Debugger

#15897 Many GL/GLES fixes
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureShaderCommon.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  UI/OnScreenDisplay.cpp
Labels: OpenGL, GE emulation

#15899 Fix smoothed depal on GLES. Don't enable filtering if not using.
  GPU/Common/ShaderId.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureShaderCommon.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
Labels: GE emulation

#15892 Reimplement framebuffer reinterpret on the new color copy framework
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/GPUCommon.cpp
  unittest/TestShaderGenerators.cpp
Labels: GE emulation, Code Cleanup

#15902 Block transfer code refactor
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPUCommon.cpp
Labels: Code Cleanup

#15905 Add a RISC-V emitter
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/RiscVEmitter.cpp
  Common/RiscVEmitter.h
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
Labels: RISC-V

#15908 Finish the depal refactoring.
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/TextureShaderCommon.h
Labels: Code Cleanup

#15907 Reinterpret between 32 and 16 bit texture formats
  Common/GPU/Shader.h
  Common/GPU/ShaderWriter.h
  Common/Math/math_util.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepalettizeShaderCommon.h
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUStateUtils.h
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/TextureShaderCommon.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
  assets/compat.ini
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#15910 Add LI and compressed instructions for RISC-V
  CMakeLists.txt
  Common/RiscVEmitter.cpp
  Common/RiscVEmitter.h
  android/jni/Android.mk
  unittest/TestRiscVEmitter.cpp
  unittest/UnitTest.cpp
  unittest/UnitTests.vcxproj
  unittest/UnitTests.vcxproj.filters
Labels: RISC-V

#15917 Vulkan bandwidth optimizations (configure renderpass load/store better)
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan, GE emulation

#15920 Better framebuffer checks, remove all ways that framebuffer formats can change
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPUCommon.cpp
Labels: GE emulation

#15921 Fix OpenGL bug when framebuffer fetch is available. Add two new GPU stats.
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
Labels: GE emulation

#15922 Remove reinterpret compat flag
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
  assets/compat.ini
Labels: Code Cleanup

#15925 GE Debugger: Improve display list disasm
  GPU/GeDisasm.cpp
Labels: Debugger

#15924 Add support for reading depth buffers to the PackFramebufferSync function
  Common/GPU/DataFormat.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/thin3d.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GPUCommon.cpp
Labels: GE emulation, Code Cleanup

#15928 Clean up mip size calculations
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup

#15926 Implement shader blending for D3D9
  Common/GPU/D3D9/D3D9ShaderCompiler.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Directx9/StateMappingDX9.cpp
  unittest/TestShaderGenerators.cpp
Labels: D3D9

#15929 Fix race condition in replacement texture loading
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation

#15930 Fix sceKernelUnlockMutex timing
  Core/HLE/sceKernelMutex.cpp
Labels: HLE/Kernel

#15934 Split the main framebuffer in Killzone, to avoid texturing-from-current-rendertarget
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/sceDisplay.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/GPUCommon.cpp
  GPU/GPUState.h
  assets/compat.ini
Labels: GE emulation
