Repository hrydgard/ppsspp, pull requests merged in 2022-06, with the labels that each got.

#15570 GLES: Fix sw transform flip in skip buffer mode
  GPU/GLES/DrawEngineGLES.cpp
Labels: OpenGL

#15581 Add additional rescaps for UWP port
  UWP/PackageGold.appxmanifest
  UWP/PackageNormal.appxmanifest
Labels: Platform-specific (UWP)

#15582 Update zh_CN.ini
  assets/lang/zh_CN.ini
Labels: Translation

#15583 Fix and further improve line drawing in Echochrome
  .gitignore
  Common/TimeUtil.cpp
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/GPUCommon.h
  GPU/Math3D.cpp
  assets/compat.ini
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: GE emulation

#15611 Workaround old Mali driver bug with discard + stencil
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/ShaderId.cpp
  UI/DevScreens.cpp
  UI/GPUDriverTestScreen.cpp
  assets/compat.ini
Labels: GE emulation

#15614 Avoid including signal.h from CommonFuncs.h
  Common/CommonFuncs.h
Labels: Code Cleanup

#15615 Workaround for strange driver hang on Raspberry Pi 3.
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  UI/GameSettingsScreen.cpp
Labels: Platform-specific (Linux/POSIX), OpenGL, GE emulation

#15619 Update lang file
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  assets/shaders/defaultshaders.ini
Labels: Translation

#15625 Mask some part of public IP in the logs for security reason.
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhoc.h
Labels: Networking / adhoc

#15631 [UI] Minor changes to PRO ad hoc server IP address selection
  UI/GameSettingsScreen.cpp
  libretro/libretro.cpp
Labels: User Interface
