Repository hrydgard/ppsspp, pull requests merged in 2022-12, with the labels that each got.

#16470 softgpu: Correctly fix inversions, matching tests
  GPU/Software/Clipper.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Software/TransformUnit.h
Labels: Software Rasterizer

#16476 Minor optimizations
  Common/Data/Convert/SmallDataConvert.cpp
  Common/Data/Convert/SmallDataConvert.h
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/VulkanProfiler.cpp
  Common/GPU/Vulkan/VulkanProfiler.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Core/MemMapHelpers.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/GPUCommon.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  UI/MiscScreens.cpp
  unittest/UnitTest.cpp
Labels: GE emulation

#16477 Add a flags parameter to InvalidateCachedState and rename it Invalidate.
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/MiscTypes.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/Draw2D.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GPUCommon.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
Labels: Code Cleanup

#16478 softgpu: Interpolate Z for 3D lines
  GPU/Software/Rasterizer.cpp
Labels: Software Rasterizer

#16480 softgpu: Cull verts outside post-viewport Z
  GPU/Software/TransformUnit.cpp
Labels: Software Rasterizer

#16481 Cleanup some GE debugger logspam, small texture proj optimization
  GPU/Common/ShaderId.cpp
  GPU/Debugger/Debugger.cpp
  GPU/Software/Rasterizer.cpp
Labels: Software Rasterizer

#16485 softgpu: Handle infnan fog coefficients better
  Common/Math/expression_parser.cpp
  GPU/Common/GPUDebugInterface.cpp
  GPU/Software/TransformUnit.cpp
Labels: Software Rasterizer

#16486 softgpu: Apply optimizations to states generically
  GPU/Software/BinManager.cpp
  GPU/Software/BinManager.h
  GPU/Software/DrawPixel.cpp
  GPU/Software/DrawPixel.h
  GPU/Software/Rasterizer.cpp
  GPU/Software/Rasterizer.h
  GPU/Software/Sampler.cpp
  GPU/Software/Sampler.h
  GPU/Software/SoftGpu.cpp
Labels: Software Rasterizer

#16458 Implement MSAA support for desktop GPUs in Vulkan
  Common/Data/Convert/SmallDataConvert.h
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanBarrier.cpp
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.h
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Core/Config.cpp
  Core/Config.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUCommon.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  UI/GameSettingsScreen.cpp
  headless/Headless.cpp
  unittest/TestShaderGenerators.cpp
Labels: Vulkan, GE emulation

#16487 Safer and simpler alternative to commit cbfa4bf.
  Core/System.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
Labels: Code Cleanup

#16489 Small fixes
  Common/Thread/ThreadManager.cpp
  Core/Util/GameManager.cpp
  UI/ReportScreen.cpp
Labels: Code Cleanup

#16491 Quick cleanup
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Core/HLE/scePsmf.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/Vulkan/VulkanUtil.cpp
Labels: Code Cleanup

#16492 Reorganize the display layout screen
  Common/File/Path.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  GPU/Common/PostShader.cpp
  GPU/Common/PostShader.h
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
Labels: User Interface

#16495 Cleanup shader module lifetime handling for Vulkan
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan

#16494 Force "Lower resolution for effects" off in Ratchet & Clank and a few other games
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  assets/compat.ini
Labels: GE emulation

#16500 Fixes to recently introduced warnings and a couple older ones
  CMakeLists.txt
  Common/Serialize/SerializeSet.h
  Common/Serialize/Serializer.cpp
  Core/MemMap.cpp
  GPU/GPUCommon.h
  GPU/Software/TransformUnit.cpp
  ext/libzstd.vcxproj
Labels: Code Cleanup

#16504 GPU: Use accurate depth for depth range hack
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUState.cpp
  GPU/GPUState.h
Labels: Code Cleanup

#16503 softgpu: Fix double rectangle drawing at halfpixel
  GPU/Software/Rasterizer.cpp
Labels: Software Rasterizer

#16502 A few more softgpu optimizations for alpha blend/test
  GPU/Software/Rasterizer.cpp
  GPU/Software/Rasterizer.h
Labels: Software Rasterizer

#16505 Minor UI polish, Swedish translation work
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Core/Config.cpp
  Core/Config.h
  Core/Dialog/PSPOskDialog.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  assets/lang/sv_SE.ini
Labels: User Interface

#16509 softgpu: Fix w culling of triangles combined as rectangles
  GPU/Software/RasterizerRectangle.cpp
Labels: Software Rasterizer

#16512 softgpu: Avoid checking UVs for sprites w/o textures
  GPU/Software/RasterizerRectangle.cpp
Labels: Software Rasterizer

#16517 Darkstalkers/Vampire Chronicles perf improvements
  Common/Data/Convert/ColorConv.h
  GPU/Software/RasterizerRectangle.cpp
Labels: Software Rasterizer, GE emulation

#16518 softgpu: Expand fast path to all fb formats
  Common/Data/Convert/ColorConv.h
  GPU/Software/BinManager.cpp
  GPU/Software/DrawPixel.cpp
  GPU/Software/DrawPixel.h
  GPU/Software/Rasterizer.cpp
  GPU/Software/Rasterizer.h
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/Sampler.cpp
  GPU/Software/Sampler.h
  unittest/TestSoftwareGPUJit.cpp
Labels: Software Rasterizer

#16524 Add new images to touch controls
  UI/GamepadEmu.h
Labels: Input/Controller, User Interface

#16520 LittleBigPlanet: Compat flag to work around smoke rendering problem
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  assets/compat.ini
Labels: GE emulation

#16526 Added vertical layout for display layout screen
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MainScreen.cpp
  UI/MainScreen.h
  UI/PauseScreen.cpp
  UI/RemoteISOScreen.cpp
Labels: User Interface

#16513 Libretro: Set Interpreter as default CPU and get CPU from setting
  libretro/libretro.cpp
Labels: Platform-specific (iOS), Libretro

#16506 Fix the Qt/SDL window icon path
  Qt/mainwindow.cpp
  SDL/SDLMain.cpp
Labels: SDL2, Qt

#16514 Libretro: Cheat Support
  libretro/libretro.cpp
Labels: Libretro

#16536 Fix regression in Tactics Ogre - the mipmap level hack broke
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation, Mipmaps

#16535 Some minor initialization fixes, and fix for a potential crash found by static analysis
  Common/Data/Encoding/Utf8.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/Render/DrawBuffer.cpp
  Common/UI/Root.cpp
  Common/UI/UIScreen.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/GPU.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  Windows/GPU/WindowsGLContext.cpp
Labels: Code Cleanup

#16539 GE Debugger: Fix src/dst stride formatting
  Common/Thread/ThreadManager.cpp
  Common/Thread/ThreadManager.h
  GPU/GeDisasm.cpp
Labels: Code Cleanup

#16488 OpenXR - Fixes for release candidate
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Core/Config.cpp
  GPU/Common/PresentationCommon.cpp
  UI/GameSettingsScreen.cpp
  android/build.gradle
  android/jni/app-android.cpp
Labels: VR

#16543 Windows: Fix cleanup order on shutdown
  Core/Debugger/DebugInterface.h
  Core/MIPS/MIPSDebugInterface.h
  Windows/MainWindow.cpp
  Windows/main.cpp
Labels: Platform-specific (Windows)

#16548 Minor translation fixes
  UI/DevScreens.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#16550 Hide the D3D9 option on Intel Xe graphics.
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  UI/GameSettingsScreen.cpp
Labels: D3D9

#16553 Make the string "PPSSPP Homebrew Store" translatable in one more place
  UI/Store.cpp
Labels: Translation

#16555 Add VR translation lines to the ini files
  Tools/langtool/src/inifile.rs
  Tools/langtool/src/main.rs
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#16564 UI: Avoid crash on axis input during shutdown
  UI/NativeApp.cpp
Labels: Input/Controller

#16563 Postshader: Don't save default setting values
  Core/Config.cpp
  Core/CwCheat.cpp
  GPU/Common/PostShader.cpp
  GPU/Common/PresentationCommon.cpp
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
Labels: User Interface

#16570 Add accessors for use flags, hide the variable
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUState.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  UI/DevScreens.cpp
Labels: Code Cleanup

#16572 Vulkan pipeline cache: Make it more lenient to useFlags changes
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan

#16575 Cleanup some logspam
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Core/Config.cpp
  Core/ConfigValues.h
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Code Cleanup

#16573 Disable geometry shader culling by default
  Core/Config.cpp
Labels: Vulkan

#16580 Add stub symbol for 'utimensat', making it work on Android 2.3 again
  android/jni/app-android.cpp
Labels: Platform-specific (Android)

#16579 Multisampling level: Don't read directly from g_Config
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
Labels: GE emulation

#16595 Transparent background option
  Core/Config.cpp
  Core/Config.h
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#16599 Vulkan: Remove the new 0th descriptor set, move everything else back to desc set 0
  Common/GPU/ShaderTranslation.cpp
  Common/GPU/ShaderWriter.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/VulkanUtil.cpp
  UI/GPUDriverTestScreen.cpp
Labels: Vulkan

#16602 Supply some extra info in asserts (currently game ID and name).
  Common/Log.cpp
  Common/Log.h
  UI/EmuScreen.cpp
Labels: Platform-specific (Android)

#16611 Move the "Take insets into account when centering" setting to the display layout screen
  UI/DevScreens.cpp
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#16614 GPU: Keep prevPrim_ set on flush
  GPU/Common/DrawEngineCommon.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#16617 GE Debugger: Prevent double init
  GPU/Debugger/Record.cpp
Labels: Debugger

#16619 Debugger: Don't hang memory dump if stepping in GE
  Core/Core.cpp
Labels: Debugger

#16620 Build: Allow compiling without armips
  CMakeLists.txt
  Core/Debugger/SymbolMap.cpp
  Core/MIPS/MIPSAsm.cpp
  ext/CMakeLists.txt
Labels: Debugger

#16615 D3D9: Support old-style user clip planes
  Common/GPU/D3D9/D3D9StateCache.h
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/thin3d.h
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GPUCommon.cpp
Labels: D3D9

#16626 GL: Cleanup a check to use ARB instead
  Common/Data/Convert/SmallDataConvert.h
  GPU/GLES/DepthBufferGLES.cpp
Labels: Code Cleanup

#16629 Build: Cleanup MSVC project files
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  UI/ReadMe.txt
  Windows/PPSSPP.vcxproj
  Windows/PPSSPP.vcxproj.filters
  ext/SPIRV-Cross.vcxproj
  ext/SPIRV-Cross.vcxproj.filters
  ext/discord-rpc-build/discord-rpc.vcxproj
  ext/discord-rpc-build/discord-rpc.vcxproj.filters
  ext/glslang.vcxproj
  ext/glslang.vcxproj.filters
  ext/libarmips.vcxproj
  ext/libarmips.vcxproj.filters
  ext/miniupnpc.vcxproj
  ext/miniupnpc.vcxproj.filters
Labels: Code Cleanup

#16608 Cleanup value corrections in config load/save
  Common/Data/Text/I18n.cpp
  Common/Data/Text/I18n.h
  Core/Compatibility.cpp
  Core/Config.cpp
  Core/Config.h
Labels: Code Cleanup

#16634 Android OpenGL: delete dead code
  CMakeLists.txt
  Common/GPU/OpenGL/thin3d_gl.cpp
  UI/NativeApp.cpp
  Windows/PPSSPP.vcxproj
  Windows/PPSSPP.vcxproj.filters
  android/jni/Android.mk
  android/jni/AndroidEGLContext.cpp
  android/jni/AndroidEGLContext.h
  android/jni/app-android.cpp
  android/src/main/.gitignore
Labels: Platform-specific (Android), OpenGL

#16641 Delete more dead code in app-android.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/NativeApp.java
Labels: Code Cleanup

#16645 Fix vertex shader range culling - the driver bug check was wrong.
  GPU/GPUCommon.cpp
Labels: Guardband / Range Culling, GE emulation

#16647 Found a bug where we tried to look up queue family -1 when initializing the frame profiler.
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanProfiler.cpp
Labels: Vulkan

#16651 Libretro: skip leading zeros in IP address.
  libretro/libretro.cpp
Labels: Libretro

#16652 Implement basic RISC-V crash handler, tweaks
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/MachineContext.h
  Core/MIPS/fake/FakeJit.cpp
  Core/MIPS/fake/FakeJit.h
  Core/MemFault.cpp
  git-version.cmake
  headless/SDLHeadlessHost.cpp
Labels: OpenGL

#16656 Fix rendering of lines with the same x/y but different z.
  GPU/Common/SoftwareTransformCommon.cpp
  assets/compat.ini
Labels: GE emulation

#16657 Vulkan: Remove some unused values
  Common/GPU/Vulkan/thin3d_vulkan.cpp
Labels: Code Cleanup

#16658 Remove the unused filter stuff from store.
  UI/Store.cpp
  UI/Store.h
Labels: Code Cleanup

#16659 A very minor optimization to GS ID computation
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
Labels: Code Cleanup

#16671 Add some extra room to the alt stack for exception handlers.
  Common/ExceptionHandlerSetup.cpp
Labels: Platform-specific (Android)

#16673 Show bluescreen properly on memory errors that we failed to ignore.
  Core/Core.cpp
  Core/Core.h
  Core/MemFault.cpp
  UI/EmuScreen.cpp
Labels: User Interface

#16681 Cleanup some mic data reading
  Core/HLE/sceUsbMic.cpp
Labels: Audio

#16678 Debugger: Correct errors in breakpoint create
  Windows/Debugger/BreakpointWindow.cpp
Labels: Debugger

#16688 Debugger: Correct check of pending list item
  Windows/Debugger/Debugger_Lists.cpp
  Windows/W32Util/Misc.cpp
  Windows/W32Util/Misc.h
Labels: Debugger
