Repository hrydgard/ppsspp, pull requests merged in 2022-11, with the labels that each got.

#16314 UI: Install textures as a zip if supported
  Core/TextureReplacer.cpp
  Core/Util/GameManager.cpp
  Core/Util/GameManager.h
Labels: User Interface

#16321 GE Debugger: Try harder to identify unchanged VRAM
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Record.cpp
Labels: Debugger

#16333 OpenXR - Defines cleanup
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Common/VR/VRBase.cpp
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRInput.cpp
  Common/VR/VRRenderer.cpp
  android/jni/app-android.cpp
Labels: VR

#16310 OpenXR - Map controller gestures
  Common/Input/KeyCodes.h
  Common/VR/PPSSPPVR.cpp
  Core/Config.cpp
  Core/Config.h
  Core/KeyMap.cpp
  UI/GameSettingsScreen.cpp
Labels: Input/Controller, VR

#16336 Support Android file intents with up to 3 dots in path
  android/AndroidManifest.xml
Labels: Platform-specific (Android)

#16338 VK: Move the rarely used "u_rotation" uniform to the frame uniform buffer.
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: Vulkan

#16340 Fix parsing ampersands in server listings for streaming
  Common/StringUtils.cpp
Labels: User Interface

#16337 Vulkan: Switch RenderPassType to be a "proper" bitfield enum.
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
Labels: Code Cleanup

#16342 Gradle upgrade, lock NDK version
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  android/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Platform-specific (Android)

#16343 VR: Separate float parameters, to avoid ugly/dangerous scale hacks
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRRenderer.cpp
  Common/VR/VRRenderer.h
Labels: VR

#16344 Mostly remove the use of the OPENXR ifdef
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/VR/OpenXRLoader.cpp
  Common/VR/OpenXRLoader.h
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Common/VR/VRBase.cpp
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRInput.cpp
  Common/VR/VRRenderer.cpp
  Core/Compatibility.cpp
  Core/Config.cpp
  Core/KeyMap.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  UI/NativeApp.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/PPSSPP_UWPMain.cpp
  android/jni/Android.mk
  android/jni/AndroidEGLContext.cpp
  android/jni/app-android.cpp
  assets/compatvr.ini
  libretro/Makefile.common
Labels: VR

#16346 Change the "Retain changed textures" option into a compat.ini option.
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/Config.cpp
  Core/Config.h
  GPU/Common/TextureCacheCommon.cpp
  UI/GameSettingsScreen.cpp
  assets/compat.ini
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  libretro/libretro.cpp
  libretro/libretro_core_options.h
Labels: User Interface, Code Cleanup

#16348 Speed hack setting reorganization
  Core/Config.cpp
  Core/Config.h
  Core/HLE/sceDisplay.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  Qt/mainwindow.cpp
  Qt/mainwindow.h
  Tools/langtool/src/section.rs
  UI/DisplayLayoutScreen.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  Windows/MainWindowMenu.cpp
  Windows/ppsspp.rc
  Windows/resource.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  headless/Headless.cpp
  libretro/libretro.cpp
  libretro/libretro_core_options.h
Labels: User Interface

#16347 Always skin in decode for software transform and rendering
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SplineCommon.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GPUCommon.cpp
  GPU/GPUState.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Software/TransformUnit.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
  Windows/GEDebugger/TabVertices.cpp
  unittest/TestVertexJit.cpp
Labels: Code Cleanup

#16354 Vulkan: Use the very same view as input attachment and color attachment, not just the same image
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: Vulkan

#16355 Properly buildfix GL/VR again
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
Labels: OpenGL, VR

#16357 Vulkan: Better pipeline creation error handling
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/LogManager.cpp
  Common/Thread/Channel.h
  Common/Thread/Promise.h
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  android/jni/app-android.cpp
Labels: Vulkan

#16358 TexCache: Fix 16->32 colors with CLUT start pos
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
Labels: GE emulation

#16356 OpenXR - Camera adjust using any controller
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Core/KeyMap.cpp
  Core/KeyMap.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GPUCommon.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  assets/compatvr.ini
Labels: VR

#16363 OpenGL ES: Bail as early as possible if things are bad
  Common/GPU/OpenGL/thin3d_gl.cpp
  UI/NativeApp.cpp
  android/jni/AndroidJavaGLContext.cpp
  android/jni/app-android.cpp
Labels: Platform-specific (Android), OpenGL

#16365 Fix GLSL compilation issues on really old Adreno drivers.
  GPU/Common/VertexShaderGenerator.cpp
Labels: OpenGL, Confirmed Driver Bug, Adreno GPU

#16367 Mpeg: Correct YUV order from decode
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#16366 TexCache: Cleanup BGRA flag dirtying
  GPU/Common/TextureCacheCommon.cpp
  GPU/GPUState.h
Labels: Code Cleanup

#16361 GPU: Avoid clears for non-simple depth values
  GPU/Common/DrawEngineCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: GE emulation

#16369 GPU: Correct vertex decoder in software transform.
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#16370 OpenXR - Sonic Rivals fixed
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Common/VR/VRMath.cpp
  Common/VR/VRMath.h
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/GLES/ShaderManagerGLES.cpp
  assets/compatvr.ini
Labels: VR

#16378 Cleanup some minor warnings
  Common/Serialize/SerializeFuncs.h
  Common/UI/View.cpp
  Common/UI/View.h
  Common/UI/ViewGroup.cpp
  Common/VR/VRFramebuffer.cpp
Labels: Code Cleanup

#16379 Fix alpha/stencil replace on Adreno when color masked
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: Vulkan

#16384 softgpu: Correct tex on fogged rectangles
  GPU/Software/Clipper.cpp
Labels: Software Rasterizer

#16385 softgpu: Fix off-by-one rendering after half-pixel
  GPU/Software/Rasterizer.cpp
Labels: Software Rasterizer

#16387 softgpu: Use threads on self-render if safe
  GPU/Software/BinManager.cpp
  GPU/Software/BinManager.h
Labels: Software Rasterizer

#16386 UI: Show standard back button on touch layout
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#16388 Twinbee Portable: Add compat flag to avoid game bug with some languages
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/sceImpose.cpp
  Core/HLE/sceUtility.cpp
  assets/compat.ini
Labels: HLE/Kernel

#15438 Fix grid align
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#16394 OpenXR - UX improvements
  Common/UI/ViewGroup.cpp
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRFramebuffer.h
  Common/VR/VRRenderer.cpp
  Common/VR/VRRenderer.h
  GPU/Common/PresentationCommon.cpp
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  UI/PauseScreen.cpp
  android/jni/app-android.cpp
Labels: VR

#16395 GPU: Prefer raster for depth blit if supported
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#16396 Correct misbehavior on uninitialized values in IR
  Core/MIPS/IR/IRCompVFPU.cpp
Labels: IRInterpreter

#16397 Debugger: Combine mem info on duplicates
  Core/Debugger/MemBlockInfo.cpp
Labels: Debugger

#16398 Pause screen: Orient Save State / Load State buttons horizontally
  UI/PauseScreen.cpp
Labels: User Interface

#16402 softgpu: Throw away all inverted polygons
  GPU/Software/Clipper.cpp
Labels: Software Rasterizer

#16401 GE Debugger: Correct texture address corruption in playback
  GPU/Debugger/Playback.cpp
Labels: Debugger

#16408 softgpu: Fix compile hazard while running
  GPU/Software/BinManager.cpp
  GPU/Software/DrawPixel.cpp
  GPU/Software/DrawPixel.h
  GPU/Software/Rasterizer.cpp
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/Sampler.cpp
  GPU/Software/Sampler.h
Labels: Software Rasterizer

#16404 Make the pause screen "transparent"
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  UI/EmuScreen.cpp
  UI/PauseScreen.cpp
  UI/PauseScreen.h
Labels: User Interface

#16411 Extract the Vulkan descriptor binding cleanup from #16345
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  assets/lang/en_US.ini
  assets/lang/sv_SE.ini
Labels: Code Cleanup

#16410 Move AsyncImageFileView to Common
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Render/ManagedTexture.cpp
  Common/Render/ManagedTexture.h
  Common/UI/AsyncImageFileView.cpp
  Common/UI/AsyncImageFileView.h
  Common/UI/Context.cpp
  UI/EmuScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/GameScreen.cpp
  UI/NativeApp.cpp
  UI/PauseScreen.cpp
  UI/PauseScreen.h
  UI/ReportScreen.cpp
  UI/SavedataScreen.cpp
  UI/SavedataScreen.h
  UI/Store.cpp
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#16414 Pause menu background: Remove complicated transparency tricks
  Common/UI/Context.h
  UI/EmuScreen.cpp
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/PauseScreen.cpp
  UI/PauseScreen.h
Labels: User Interface

#16416 OpenXR - Menu background transparency fixed
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  GPU/Common/FramebufferManagerCommon.cpp
Labels: VR

#16415 Display layout editor - Remove editing widget, just use the background directly
  CMakeLists.txt
  UI/DisplayLayoutEditor.cpp
  UI/DisplayLayoutEditor.h
  UI/DisplayLayoutScreen.cpp
  UI/DisplayLayoutScreen.h
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/PauseScreen.cpp
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  android/jni/Android.mk
Labels: User Interface

#16417 Move post processing settings to the Display Layout Editor
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  UI/ComboKeyMappingScreen.h
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/CwCheatScreen.cpp
  UI/CwCheatScreen.h
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/DisplayLayoutScreen.cpp
  UI/DisplayLayoutScreen.h
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  UI/TouchControlLayoutScreen.cpp
  UI/TouchControlLayoutScreen.h
  UI/TouchControlVisibilityScreen.cpp
  UI/TouchControlVisibilityScreen.h
  headless/Headless.cpp
Labels: User Interface

#16419 Stick input: Fix issue where deadzone noise from one device could drown out signal from another.
  Common/Input/InputState.h
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/KeyMapDefaults.cpp
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  assets/ui_atlas.meta
  assets/ui_atlas.zim
  source_assets/image/trashcan.png
  ui_atlasscript.txt
Labels: Input/Controller

#16420 Add a way to view GPU_USE flags at runtime
  Common/GPU/DataFormat.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/thin3d.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUState.cpp
  GPU/GPUState.h
  UI/DevScreens.cpp
Labels: User Interface, Debugger

#16422 Add compat flag / bug check for games on old Adreno/GL affected by #16015
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/GLES/GPU_GLES.cpp
  assets/compat.ini
Labels: OpenGL, Confirmed Driver Bug, Adreno GPU

#16426 Rebind framebuffer after LoadCLUT-from-framebuffer
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  GPU/Common/TextureCacheCommon.cpp
Labels: Vulkan, GE emulation

#16428 Vulkan validation cleanups, remove "GetCurrentStepId" based invalidation
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/MiscTypes.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
Labels: Vulkan, Code Cleanup

#16425 (Libretro) Huge MSVC Build Overhaul
  libretro/Makefile
  libretro/README_WINDOWS.txt
  libretro/VSWhere.sh
Labels: Libretro

#16432 Cleanup graphics settings list
  UI/DevScreens.cpp
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/PauseScreen.cpp
  Windows/ppsspp.rc
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#16431 Snap from screen center
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#16434 Vulkan: Use stencil export when available
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/DataFormat.h
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/StencilCommon.cpp
  GPU/Common/StencilCommon.h
  unittest/TestShaderGenerators.cpp
Labels: GE emulation

#16436 Add basic CI support for build-testing the Android-based VR build.
  .github/workflows/build.yml
  android/jni/Android.mk
Labels: VR

#16435 More post-shader UI improvements
  Common/UI/UIScreen.cpp
  Common/UI/View.cpp
  UI/DisplayLayoutScreen.cpp
Labels: User Interface

#16440 softgpu: Allow inversions when w >= -1.0
  GPU/Software/Clipper.cpp
Labels: Software Rasterizer

#16439 PPGe: Respect 512 texture limit
  Core/Util/PPGeDraw.cpp
Labels: Software Rasterizer

#16441 Exposed more emulator things to devctl api
  Core/HLE/sceIo.cpp
Labels: Plugins

#16442 Vulkan: Only use geometry shaders with accurate depth
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Depth / Z

#16443 Break out VKRFramebuffer/VKRRenderpass from VulkanRenderManager
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#16446 Aspect ratio configuration fixes
  Core/HLE/sceIo.cpp
  UI/DisplayLayoutScreen.cpp
Labels: User Interface

#16448 Empirical attempt at fixing #15661
  GPU/Common/SoftwareTransformCommon.cpp
Labels: GE emulation

#16450 UI: Fix right analog with single button
  UI/GamepadEmu.cpp
Labels: User Interface

#16451 UI: Add a slight glow around PSP in control map
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  UI/ControlMappingScreen.cpp
Labels: User Interface

#16452 GE Debugger: Correct LastVRAM mirror wrap around
  GPU/Debugger/Record.cpp
Labels: Debugger

#16454 GPU: Support framebuf depal from rendered CLUT
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#16449 Blind workaround for Shining Ark circle button problem
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/Dialog/PSPDialog.cpp
  Core/Dialog/PSPDialog.h
  Core/Dialog/PSPNetconfDialog.cpp
  Core/Dialog/PSPOskDialog.cpp
  Core/HLE/sceImpose.cpp
  Core/HLE/sceUtility.cpp
  assets/compat.ini
Labels: Input/Controller, HLE/Kernel

#16460 Translation string fixes
  Tools/langtool/src/main.rs
  UI/GameSettingsScreen.cpp
  UI/MiscScreens.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#16461 Fix Burnout Dominator lens flare on OpenGL ES
  Common/GPU/OpenGL/thin3d_gl.cpp
  GPU/Common/FramebufferManagerCommon.cpp
Labels: OpenGL, GE emulation

#16464 Let the running game show through the background of all the PromptScreen dialogs.
  UI/EmuScreen.cpp
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/PauseScreen.cpp
Labels: User Interface

#16462 Fragment shader generator: Move the framebuffer fetch bit to the shader ID.
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Code Cleanup

#16466 Control UI fix attempts
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#16467 Redo the control UI screen layout, slightly update the look
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#16456 SoftGPU: Range check block copies.
  GPU/GPUCommon.cpp
  GPU/Software/SoftGpu.cpp
Labels: Software Rasterizer
