Repository hrydgard/ppsspp, pull requests merged in 2022-04, with the labels that each got.

#15466 Detect number of cores in build script
  b.sh
Labels: Platform-specific (Linux/POSIX), Platform-specific (Mac OS X)

#15467 Net: Ignore SIGPIPE errors on POSIX systems
  .editorconfig
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  SDL/SDLMain.mm
  headless/Headless.cpp
  ios/main.mm
Labels: Networking / adhoc

#15470 Threading manager stresstest and fixes
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Thread/Barrier.h
  Common/Thread/Event.h
  Common/Thread/Waitable.h
  Common/TimeUtil.cpp
  Common/TimeUtil.h
  Core/TextureReplacer.cpp
  unittest/TestThreadManager.cpp
  unittest/UnitTest.h
Labels: Multithreading

#15472 ThreadManager: Improve waitable destruction
  Common/Thread/Waitable.h
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
Labels: Multithreading

#15476 Merge separate NEON functions into the normal functions.
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Convert/ColorConv.cpp
  Common/Data/Convert/ColorConv.h
  Common/Data/Convert/ColorConvNEON.cpp
  Common/Data/Convert/ColorConvNEON.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Util/AudioFormat.cpp
  Core/Util/AudioFormat.h
  Core/Util/AudioFormatNEON.cpp
  Core/Util/AudioFormatNEON.h
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureDecoder.cpp
  GPU/Common/TextureDecoder.h
  GPU/Common/TextureDecoderNEON.cpp
  GPU/Common/TextureDecoderNEON.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/GPUCommon.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  UI/NativeApp.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/UnitTest.cpp
Labels: Code Cleanup

#15477 ARM32: Remove a lot of non-NEON fallback paths
  Common/Math/fast/fast_math.c
  Common/Math/fast/fast_math.h
  Core/MIPS/ARM/ArmAsm.cpp
  Core/MIPS/ARM/ArmCompVFPU.cpp
  Core/MIPS/ARM/ArmRegCacheFPU.cpp
  Core/MIPS/ARM/ArmRegCacheFPU.h
  Core/MIPS/JitCommon/JitState.cpp
  GPU/Common/TextureDecoder.cpp
  GPU/Common/VertexDecoderArm.cpp
  UI/NativeApp.cpp
Labels: armjit, Code Cleanup

#15482 Delete a lot of specialized alpha checking code.
  Core/TextureReplacer.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureDecoder.cpp
  GPU/Common/TextureDecoder.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
Labels: GE emulation, Code Cleanup

#15484 Add contributed data about a couple of prototypes to auto-expand memory to 64MB
  Core/HDRemaster.cpp
Labels: HLE/Kernel

#15487 Save textures on background tasks when texture dumping is enabled.
  Common/MemoryUtil.h
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: User Interface

#15493 Fix checks for the "fake mipmap" situation.
  GPU/Common/TextureCacheCommon.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation

#15495 Vulkan texture mip level load fix
  Common/DbgNew.h
  Common/GPU/Vulkan/VulkanImage.h
  Common/MemoryUtil.cpp
  Core/TextureReplacer.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan, GE emulation

#15494 Add key bind to hotswap internal screen rotation
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/EmuScreen.cpp
Labels: User Interface

#15464 Allow to change atlas per theme
  Common/UI/Context.cpp
  Common/UI/Context.h
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  UI/Theme.cpp
  UI/Theme.h
Labels: User Interface

#15501 Make the existing ReinterpretFramebuffers/ShaderColorBitmask path work for Split/Second
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/Common/ShaderId.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
  assets/compat.ini
Labels: GE emulation

#15502 Simplify alphasum checking for DXT textures, and fix a regression
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureDecoder.cpp
Labels: GE emulation

#15511 Detect ISO files from file contents if extensions are wrong.
  Core/Loaders.cpp
  Core/Loaders.h
  UI/GameInfoCache.cpp
Labels: Loader

#15512 Better default control config for the Retroid handheld Android console
  Core/KeyMap.cpp
  Core/KeyMap.h
  Core/KeyMapDefaults.cpp
  Core/KeyMapDefaults.h
Labels: Input/Controller

#15498 Fix lazy loading of metadata
  UI/Theme.cpp
Labels: User Interface
