Repository hrydgard/ppsspp, pull requests merged in 2022-10, with the labels that each got.

#16138 Basic groundwork for geometry shaders
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/ShaderTranslation.cpp
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/ShaderId.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  UI/DevScreens.cpp
  UI/GPUDriverTestScreen.cpp
  unittest/TestShaderGenerators.cpp
Labels: Vulkan

#16141 Debugger: Fix game.reset by adding a reboot status
  Core/Debugger/WebSocket.cpp
  Core/Debugger/WebSocket/GameBroadcaster.cpp
  Core/Debugger/WebSocket/GameSubscriber.cpp
  Core/System.cpp
  Core/System.h
  UI/EmuScreen.cpp
Labels: Debugger

#16139 Tighten up some color format checks with displays and copies
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#16146 UI: Prevent rendering during reboot
  UI/EmuScreen.cpp
Labels: Debugger

#16142 Implement geometry shader for range culling
  CMakeLists.txt
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Core/Config.cpp
  Core/Config.h
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/GeometryShaderGenerator.h
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUState.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
  UI/DevScreens.cpp
  UI/GameSettingsScreen.cpp
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
  unittest/TestShaderGenerators.cpp
Labels: Vulkan

#16160 GPU: Use flags to fix triggered upload/download
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Debugger/Record.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/SoftGpu.h
Labels: GE emulation

#16162 Implement negative Z clipping in geometry shader
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GPUCommon.cpp
  assets/compat.ini
Labels: Vulkan

#16165 Vulkan: Clip clamped depth in geometry shader
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GLES/ShaderManagerGLES.cpp
Labels: Vulkan, Mali GPU

#16168 Shader uniforms (VK/D3D11): Fix issue where we could overwrite values in the fourth component padding.
  Common/Data/Convert/SmallDataConvert.h
  GPU/Common/ShaderUniforms.cpp
Labels: Vulkan, D3D11

#16179 Correct size and YUV order for jpeg decoding
  Core/HLE/sceJpeg.cpp
  Core/HLE/sceJpeg.h
  Core/HLE/sceMpeg.h
  Core/HLE/sceUtility.cpp
Labels: HLE/Kernel

#16181 Add rendered CLUT handling to D3D9
  Common/GPU/D3D9/thin3d_d3d9.cpp
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Directx9/TextureCacheDX9.cpp
Labels: D3D9

#16182 GLES: Use GL_LUMINANCE on GLES for indexed tex
  Common/GPU/D3D9/D3D9StateCache.h
  Common/GPU/OpenGL/DataFormatGL.cpp
Labels: OpenGL

#16188 Fix depal bounds with dynamic CLUT. Fixes lens flare glitches in Ridge Racer
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#16152 Vulkan: Create depth/stencil buffers on demand
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/UI/Context.cpp
Labels: Vulkan

#16194 Fix crash setting breakpoints while in GE debugger
  Core/Debugger/Breakpoints.cpp
  Core/MIPS/MIPS.cpp
  Core/MIPS/MIPS.h
  Core/MIPS/MIPSAsm.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/main.cpp
Labels: Debugger

#16193 Loader: Get rid of overalloc on module exec
  Core/ELF/ElfReader.cpp
  Core/ELF/ElfReader.h
  Core/HLE/sceKernelModule.cpp
Labels: Code Cleanup

#16192 D3D11: Correct depth readback
  Common/GPU/D3D11/thin3d_d3d11.cpp
  GPU/Common/FramebufferManagerCommon.cpp
Labels: D3D11

#16195 GLES: Use Draw for depth readback shader
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GLES/DepthBufferGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
Labels: OpenGL, GE emulation

#16200 Vulkan: Fix initial depth copy w/o existing depth
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
Labels: Vulkan

#16199 MIPS: Fix non standard layout offsets
  Core/MIPS/MIPS.h
Labels: Debugger

#16198 Readback stencil buffer for debugger on GLES
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/GLQueueRunner.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/StencilCommon.cpp
  GPU/GLES/DepthBufferGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
Labels: OpenGL, Debugger

#16201 GE Debugger: Normalize framebuffer texture preview
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/thin3d.cpp
  Core/Debugger/WebSocket/GPUBufferSubscriber.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUDebugInterface.cpp
  GPU/Common/GPUDebugInterface.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Debugger/Stepping.cpp
  GPU/Debugger/Stepping.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/SoftGpu.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  Windows/GEDebugger/GEDebugger.cpp
  Windows/GEDebugger/GEDebugger.h
  Windows/GEDebugger/SimpleGLWindow.cpp
Labels: D3D9, Debugger

#16089 [AdhocMatching] Fix assertion issue when playing Cars over public adhoc server.
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#16205 Better arm32 forcecheck fix
  Core/CoreTiming.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/JitCommon/JitState.cpp
  Core/MIPS/MIPS.cpp
Labels: armjit

#16206 Remove the OpenGL bFragmentTestCache ini option, autodetect instead
  Core/Config.cpp
  Core/Config.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/GLES/FragmentTestCacheGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPUState.h
  headless/Headless.cpp
Labels: GE emulation

#16197 More uniform optimization, fixes
  Common/GPU/Shader.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPUCommon.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
  unittest/TestShaderGenerators.cpp
Labels: Code Cleanup

#16214 Revert on-demand depth buffer creation. Also adds a couple new debugging utils
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/UI/Context.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
Labels: Vulkan

#16232 D3D9: Correct scissor state cache in Draw
  Common/GPU/D3D9/thin3d_d3d9.cpp
Labels: D3D9

#16236 Add draft mp4msv module
  Core/HLE/HLETables.cpp
  Core/HLE/sceMp4.cpp
  Core/HLE/sceMp4.h
Labels: PSMF / MPEG

#16240 Remove some more unnecessary reporting
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernelMutex.cpp
  Core/HLE/sceKernelSemaphore.cpp
Labels: Code Cleanup

#16243 Rename GPU_SUPPORTS_* to GPU_USE_*
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/DepthBufferGLES.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUState.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup

#16241 softgpu: Correct linear interp for uneven positions
  GPU/Software/Rasterizer.cpp
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/RasterizerRectangle.h
  GPU/Software/TransformUnit.cpp
Labels: Software Rasterizer

#16246 VR: Add the VR code to all builds. Remove IsVRBuild calls from the renderer.
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/File/DirListing.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/TimeUtil.cpp
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRBase.cpp
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRFramebuffer.h
  Common/VR/VRInput.cpp
  Common/VR/VRMath.cpp
  Common/VR/VRRenderer.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUState.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
  UI/NativeApp.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/Package.appxmanifest
  android/jni/Android.mk
  android/jni/Locals.mk
  libretro/Makefile.common
Labels: Code Cleanup, VR

#16253 OpenXR - Mirroring in some games fixed
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRRenderer.h
  GPU/GLES/ShaderManagerGLES.cpp
Labels: VR

#16255 SDL: fix glew on wayland by ignore glx
  SDL/SDLGLGraphicsContext.cpp
Labels: Platform-specific (Linux/POSIX), OpenGL

#16257 Kernel: Fix reported StopThread error
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Core/HLE/HLEHelperThread.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Code Cleanup

#16258 Remove "attachment" parameter from BindFramebufferAsTexture everywhere.
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/GLES/DepthBufferGLES.cpp
Labels: Code Cleanup

#16265 GPU: Respect world matrix and reverse flag w/o normals
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Software/TransformUnit.cpp
Labels: GE emulation

#16268 Minor refactoring in PresentationCommon
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
Labels: Code Cleanup

#16270 OpenXR - Refactor compatvr.ini file
  Core/Compatibility.cpp
  Core/Compatibility.h
  assets/compatvr.ini
Labels: VR

#16271 OpenXR - Fix for Outrun 2006
  Common/VR/PPSSPPVR.cpp
Labels: VR

#16272 Make it possible to specify extensions for Vulkan in the ShaderWriter
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  unittest/TestShaderGenerators.cpp
Labels: Vulkan, Code Cleanup

#16276 softgpu: Better approximate slope mip level mode
  GPU/Software/Rasterizer.cpp
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/Sampler.cpp
  GPU/Software/Sampler.h
  GPU/Software/SamplerX86.cpp
  unittest/TestSoftwareGPUJit.cpp
Labels: Software Rasterizer

#16278 Minor refactor of ShaderWriter flags.
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
Labels: Code Cleanup

#16279 Vulkan: Use v2 feature checks, and add check for multiview features.
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Vulkan, Code Cleanup

#16280 GE Debugger: Allow reading tex on D3D11
  GPU/D3D11/TextureCacheD3D11.cpp
Labels: Debugger

#16283 Minor ShaderWriter refactor, prep for later changes
  Common/GPU/Shader.h
  Common/GPU/ShaderWriter.cpp
  Common/GPU/ShaderWriter.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/ReinterpretFramebuffer.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureShaderCommon.cpp
Labels: GE emulation

#16287 OpenXR - Stereo for Lego Star Wars games
  assets/compatvr.ini
Labels: VR

#16290 jit: Reduce some include pollution
  Core/MIPS/ARM/ArmCompALU.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/ARM/ArmRegCache.h
  Core/MIPS/ARM/ArmRegCacheFPU.h
  Core/MIPS/ARM64/Arm64CompALU.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MIPS/ARM64/Arm64RegCache.h
  Core/MIPS/ARM64/Arm64RegCacheFPU.h
  Core/MIPS/JitCommon/JitBlockCache.h
  Core/MIPS/x86/CompALU.cpp
  Core/MIPS/x86/Jit.cpp
  Core/MIPS/x86/JitSafeMem.cpp
  Core/MIPS/x86/RegCache.h
  Core/MIPS/x86/RegCacheFPU.h
  unittest/TestArmEmitter.cpp
Labels: Code Cleanup

#16291 Vulkan: Reserve descriptor set 0 for frame-global data, move everything else to set 1
  Common/GPU/ShaderTranslation.cpp
  Common/GPU/ShaderWriter.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/VulkanUtil.cpp
  GPU/Vulkan/VulkanUtil.h
  UI/GPUDriverTestScreen.cpp
Labels: Code Cleanup

#16294 Vulkan: Fix validation errors with "null" textures
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: Vulkan

#16299 Fix a few more warnings
  Common/GPU/thin3d.h
  UWP/Common/DeviceResources.cpp
  ext/native/tools/atlastool/atlastool.vcxproj
Labels: Code Cleanup

#16301 Cleanup debugger memory reference usage, API validation bug
  Core/Debugger/WebSocket/InputSubscriber.cpp
  Core/HLE/ReplaceTables.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/x86/Jit.cpp
  Core/SaveState.cpp
  GPU/Common/GPUDebugInterface.cpp
Labels: Debugger

#16302 Handle vrot overlap and vscl/vmscl prefixes more accurately
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
  Core/MIPS/MIPSVFPUUtils.cpp
Labels: IRInterpreter

#16293 OpenXR - Modify camera parameters in realtime
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Common/VR/VRRenderer.cpp
  Common/VR/VRRenderer.h
  Core/Config.cpp
  Core/Config.h
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
Labels: Input/Controller, User Interface, VR

#16305 irjit: Fix unordered float compares
  Core/MIPS/IR/IRCompALU.cpp
  Core/MIPS/IR/IRCompFPU.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/MIPSIntVFPU.cpp
Labels: IRInterpreter

#16306 irjit: Correct prefix validation
  Core/MIPS/IR/IRCompVFPU.cpp
Labels: IRInterpreter
