Repository hrydgard/ppsspp, pull requests merged in 2023-09, with the labels that each got.

#18036 Analog stick gesture
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
Labels: Input/Controller, User Interface

#18041 More translation strings
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#18047 x86jit: Implement float to integer
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRJit.h
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#18046 x86jit: Reduce bloat further
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompLoadStore.cpp
  Core/MIPS/x86/X64IRJit.cpp
Labels: x86jit

#18048 IR: Add a pass to keep things in vec4 more
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRPassSimplify.h
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRJit.h
Labels: IRInterpreter, x86jit

#18055 x86jit: Avoid R15 for jitbase if near ctxreg
  Core/MIPS/x86/X64IRAsm.cpp
Labels: x86jit

#18054 HLE: Capture better allocation names
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceHeap.cpp
  Core/HLE/sceKernelHeap.cpp
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceKernelMsgPipe.cpp
  Core/HLE/sceKernelThread.cpp
Labels: Debugger

#18053 x86jit: Handle breakpoints
  Core/Debugger/Breakpoints.cpp
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRInterpreter.h
  Core/MIPS/x86/X64IRCompSystem.cpp
Labels: IRInterpreter, x86jit

#18060 x86jit: Bake emuhack mask into jitbase
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/RiscV/RiscVAsm.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  Core/MIPS/RiscV/RiscVRegCache.cpp
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit, RISC-V

#18062 irjit: Correct metadata on Vec2 packing ops
  Core/MIPS/IR/IRInst.cpp
Labels: IRInterpreter

#18064 arm64jit: Implement exits and a few system ops
  Core/MIPS/ARM64/Arm64IRCompBranch.cpp
  Core/MIPS/ARM64/Arm64IRCompSystem.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
Labels: arm64jit

#18061 arm64jit: Implement most ALU and load/store in IR jit
  Common/Arm64Emitter.h
  Core/MIPS/ARM64/Arm64IRCompALU.cpp
  Core/MIPS/ARM64/Arm64IRCompLoadStore.cpp
  Core/MIPS/ARM64/Arm64IRJit.h
  Core/MIPS/ARM64/Arm64IRRegCache.cpp
  Core/MIPS/ARM64/Arm64IRRegCache.h
  Core/MIPS/RiscV/RiscVCompLoadStore.cpp
  Core/MIPS/x86/X64IRCompLoadStore.cpp
Labels: arm64jit

#18065 Add ability to dismiss notifications
  Common/System/OSD.cpp
  Common/System/OSD.h
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/OnScreenDisplay.cpp
  UI/OnScreenDisplay.h
Labels: User Interface

#18067 Allow using a file browser to choose UMDs during disc change.
  Core/HLE/sceUmd.cpp
  UI/MainScreen.cpp
  UI/MainScreen.h
  UI/PauseScreen.cpp
  UI/PauseScreen.h
Labels: User Interface

#18071 arm64jit: Implement IR multiplies and divides
  Core/MIPS/ARM64/Arm64IRCompALU.cpp
Labels: arm64jit

#18068 arm64jit: Implement shuffle optimizer
  Common/Arm64Emitter.cpp
  Common/Arm64Emitter.h
  Core/MIPS/ARM64/Arm64IRCompVec.cpp
Labels: arm64jit

#18075 SasAudio: Some cleanup and debug overlay improvements
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  UI/DebugOverlay.cpp
Labels: Audio

#18077 Avoid double-processing of input events caused by the overlay screen.
  Common/UI/Screen.cpp
  Common/UI/UIScreen.h
  UI/OnScreenDisplay.cpp
  UI/OnScreenDisplay.h
Labels: User Interface

#18073 arm64jit: Implement several other Vec4 IR ops
  .github/workflows/build.yml
  Common/Arm64Emitter.cpp
  Common/Arm64Emitter.h
  Core/MIPS/ARM64/Arm64IRCompVec.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
Labels: arm64jit

#18080 x86jit: Correct jitbase range comparison
  Core/MIPS/x86/X64IRAsm.cpp
Labels: x86jit

#18082 Retroachievements logspam fix, edge case fixes
  Common/System/NativeApp.h
  Core/Loaders.cpp
  Core/RetroAchievements.cpp
  Core/RetroAchievements.h
  Core/System.cpp
  UI/NativeApp.cpp
  UI/RetroAchievementScreens.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
  unittest/UnitTest.cpp
Labels: RetroAchievements

#18083 Add some texture loading safety checks
  GPU/Common/TextureCacheCommon.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: GE emulation

#18088 Vulkan: Fix ordering issue in tex loading - decided on color swizzle too early
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan

#18087 Vulkan: Fix disabling VSync on SDL platforms that support IMMEDIATE but not MAILBOX
  Common/GPU/Vulkan/VulkanContext.cpp
  SDL/SDLVulkanGraphicsContext.cpp
  android/jni/AndroidVulkanContext.cpp
Labels: SDL2, Vulkan

#18076 SasAudio: Always reinitialize the VAG decoder on sceSasSetVoice, even if already playing
  Core/HLE/sceSas.cpp
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
Labels: Audio

#18093 VS2017 buildfix
  Common/System/OSD.cpp
  Core/MIPS/ARM64/Arm64IRJit.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
Labels: Code Cleanup

#18092 Update gamecontrollerdb.txt with the latest from the community maintained DB
  assets/gamecontrollerdb.txt
Labels: Input/Controller

#18096 Ctrl+X -> Ctrl+H for closing the bottom tabs
  Windows/ppsspp.rc
Labels: User Interface

#18095 Swedish translation updates, add reminder for save new textures
  GPU/Common/TextureReplacer.cpp
  assets/lang/sv_SE.ini
Labels: User Interface

#18099 Build: Add some missing include guards.
  Common/Data/Format/JSONReader.h
  Common/Data/Format/JSONWriter.h
  Common/Input/GestureDetector.h
  Core/HLE/KernelThreadDebugInterface.h
  Core/HLE/sceMd5.cpp
  Core/HLE/sceMt19937.cpp
  Core/HW/AsyncIOManager.h
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/MIPS.h
  Core/SaveState.h
  Core/Util/DisArm64.h
  Core/WebServer.h
  GPU/Debugger/GECommandTable.h
  GPU/GeDisasm.h
  UI/CwCheatScreen.h
Labels: Code Cleanup

#18101 Android: Fix developer tools -> run tests
  Common/System/Request.cpp
  Core/PSPLoaders.cpp
Labels: Platform-specific (Android), Debugger

#18100 UI: Fix search within savedata screen
  UI/SavedataScreen.cpp
Labels: User Interface

#18102 New logging channel "PRINTF" for SceKernelPrintf
  Common/Log.h
  Common/LogManager.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelMemory.cpp
Labels: HLE/Kernel

#18103 Implement the remaining arm64jit IR ops
  Common/Arm64Emitter.cpp
  Common/Arm64Emitter.h
  Core/MIPS/ARM64/Arm64IRCompFPU.cpp
  Core/MIPS/ARM64/Arm64IRCompSystem.cpp
  Core/MIPS/ARM64/Arm64IRCompVec.cpp
  Core/MIPS/MIPSIntVFPU.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
Labels: arm64jit

#18113 Have unthrottle override alternate speeds, like before.
  Core/HLE/sceDisplay.cpp
Labels: User Interface

#18123 Fix GL hang with buffered commands = off
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/UI/IconCache.cpp
  Common/UI/Screen.cpp
Labels: OpenGL

#18126 PPGe: Use texture windows for atlas text
  Core/Util/PPGeDraw.cpp
  GPU/Common/TextureCacheCommon.cpp
Labels: Software Rasterizer

#18127 Move RetroAchievements to the tools tab, fix leaderboard submitted notification positioning
  Common/System/OSD.cpp
  Common/UI/PopupScreens.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
Labels: RetroAchievements

#18128 Restore touch D-Pad behavior
  Core/ControlMapper.cpp
  UI/GamepadEmu.cpp
  Windows/RawInput.cpp
Labels: Input/Controller

#18129 Fix the semantics of DenseHashMap to be consistent even when inserting nulls
  Common/Data/Collections/Hashmaps.h
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/Software/DrawPixel.cpp
  GPU/Software/DrawPixel.h
  GPU/Software/Sampler.cpp
  GPU/Software/Sampler.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  GPU/Vulkan/VulkanUtil.cpp
  GPU/Vulkan/VulkanUtil.h
Labels: Code Cleanup

#18132 Add reporting for GLSL shader gen errors
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  UI/MiscScreens.cpp
Labels: OpenGL

#18133 More sensible approach to the sc problem that broke Beats
  Core/MIPS/x86/CompLoadStore.cpp
  Core/MIPS/x86/Jit.h
Labels: x86jit

#18135 Fix closing the chat window with ESC, add some asserts
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/UI/UIScreen.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  UI/EmuScreen.cpp
Labels: User Interface

#18137 WAV file error message fix
  UI/BackgroundAudio.cpp
  UI/RetroAchievementScreens.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface, RetroAchievements

#18140 x86jit: Fix spill on sc in longer block
  Core/MIPS/x86/CompLoadStore.cpp
Labels: x86jit

#18141 Fix the chat window closing on pressing the X key.
  UI/EmuScreen.cpp
  UI/EmuScreen.h
Labels: User Interface

#18142 Revert "Merge pull request #18008 from hrydgard/naruto-video-flicker-heuristic"
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#18147 Vulkan: Fix validation error in Beats, some logging/assert improvements
  Common/MemoryUtil.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
Labels: Vulkan

#18143 Fix UMD disc swap with Retroachievements enabled
  Core/HLE/sceUmd.cpp
  Core/Loaders.cpp
  Core/Loaders.h
  Core/RetroAchievements.cpp
  Core/RetroAchievements.h
Labels: RetroAchievements

#18151 GPU, VFS, UI: Fixed minor memleaks
  Common/File/VFS/ZipFileReader.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  UI/BackgroundAudio.cpp
Labels: Code Cleanup

#18152 Fix a valgrind warning
  Common/UI/IconCache.cpp
  Core/HLE/sceMpeg.cpp
Labels: Code Cleanup

#18154 Core, UI, Windows: Removed excess converting C-string in params
  Common/Data/Format/IniFile.cpp
  Common/UI/PopupScreens.cpp
  Common/UI/View.cpp
  Core/Loaders.cpp
  Core/PSPLoaders.cpp
  UI/MainScreen.cpp
  UI/SavedataScreen.cpp
  UI/TabbedDialogScreen.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
Labels: Code Cleanup

#18164 HTTP: Ignore failed connects when trying to select
  Common/Net/HTTPClient.cpp
Labels: Platform-specific (Linux/POSIX)

#18165 x86jit: Fix flush for special-purpose reg
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/x86/X64IRRegCache.cpp
Labels: x86jit

#18168 SDL ttf rendering: Try two 4444 tex formats to find one that works.
  Common/Render/Text/draw_text_sdl.cpp
Labels: Platform-specific (Linux/POSIX)

#18169 Better handling of shadergen failures, other minor things
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/ShaderId.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GPUState.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: GE emulation

#18174 Disable Wayland if USE_WAYLAND_WSI is off
  CMakeLists.txt
Labels: SDL2, Platform-specific (Linux/POSIX)

#18182 Backend change from Win32 menu: Add quick workaround for instance counter misbehavior
  Windows/main.cpp
Labels: Platform-specific (Windows)

#18183 Pipeline/shader race-condition-during-shutdown crash fix
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan

#18184 Add memory bounds-check when expanding points, rects and lines to triangles
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#18185 Store: Fix race condition causing crashes if looking at another game before an icon finishes downloading
  Common/UI/IconCache.cpp
  Common/UI/IconCache.h
  Core/HW/SasAudio.cpp
  UI/Store.cpp
Labels: User Interface

#18186 Vulkan: Remove an assert that didn't give much actionable information
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  GPU/GPUCommon.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/PipelineManagerVulkan.cpp
Labels: Vulkan

#18189 Be a bit smarter when loading the shader cache, avoid duplicating work
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan

#18194 Cleanups and comment clarifications
  Common/Data/Format/IniFile.cpp
  Common/File/DirListing.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Core/Util/PPGeDraw.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  UI/OnScreenDisplay.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Code Cleanup

#18214 Implement a few leftover x64 ops
  Core/MIPS/ARM64/Arm64IRCompALU.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRJit.h
Labels: x86jit

#18213 IR: Improve fcmp/vfpu compare jit
  Core/MIPS/ARM64/Arm64IRCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
Labels: x86jit

#18208 x86jit: Speed up float to int conversions
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRJit.h
Labels: x86jit

#18216 Don't load the shader cache on a separate thread - all it does is already async
  Common/Data/Collections/Hashmaps.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
Labels: Vulkan

#18218 Vulkan: Simplify GetShaders and DirtyLastShader, making them internally consistent.
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
Labels: Vulkan

#18221 Some cleanups and fixes to obscure crashes
  Common/Net/HTTPClient.cpp
  Common/Net/HTTPClient.h
  Common/UI/Screen.cpp
  Core/FileSystems/BlockDevices.cpp
  Core/HLE/sceIo.cpp
Labels: Code Cleanup

#18220 Add some missing locking in KeyMap.cpp.
  Core/KeyMap.cpp
  UI/NativeApp.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Input/Controller

#18224 irjit: Describe native offsets better
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/x86/X64IRJit.cpp
Labels: x86jit

#18227 x86jit: Flush floats together if possible
  Core/MIPS/ARM64/Arm64IRRegCache.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#18228 unittest: Add jit compare for jit IR
  Core/MIPS/ARM64/Arm64IRCompLoadStore.cpp
  Core/MIPS/RiscV/RiscVCompLoadStore.cpp
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRCompLoadStore.cpp
  unittest/JitHarness.cpp
  unittest/UnitTest.cpp
Labels: IRInterpreter

#18226 x86jit: Improve memory breakpoint speed
  Core/MIPS/ARM64/Arm64IRCompSystem.cpp
  Core/MIPS/ARM64/Arm64IRJit.cpp
  Core/MIPS/ARM64/Arm64IRJit.h
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRJit.cpp
  Core/MIPS/x86/X64IRJit.h
Labels: arm64jit, x86jit

#18232 x86jit: Correct spill on IR lane extract
  Core/MIPS/x86/X64IRCompFPU.cpp
Labels: x86jit

#18121 IR: Add mini native jit MIPS block profiler
  Core/MIPS/ARM64/Arm64IRAsm.cpp
  Core/MIPS/ARM64/Arm64IRCompFPU.cpp
  Core/MIPS/ARM64/Arm64IRCompSystem.cpp
  Core/MIPS/ARM64/Arm64IRJit.cpp
  Core/MIPS/ARM64/Arm64IRJit.h
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/RiscV/RiscVAsm.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRJit.cpp
  Core/MIPS/x86/X64IRJit.h
Labels: arm64jit, x86jit, RISC-V

#18235 irjit: Handle VDet
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
Labels: IRInterpreter

#18230 Android: Minor activity lifecycle stuff
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/SizeManager.java
Labels: Platform-specific (Android), Vulkan, OpenGL

#18234 x86jit: Perform vector transfers instead of flushing to memory
  Common/x64Emitter.cpp
  Common/x64Emitter.h
  Core/MIPS/ARM64/Arm64IRRegCache.cpp
  Core/MIPS/ARM64/Arm64IRRegCache.h
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/RiscV/RiscVRegCache.cpp
  Core/MIPS/RiscV/RiscVRegCache.h
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#18249 arm64jit: Avoid fused multiplies in vcrsp.t
  Core/MIPS/ARM64/Arm64CompVFPU.cpp
Labels: arm64jit

#18250 Separate out accelerometer events from joystick axis events
  Common/Input/InputState.h
  Common/Input/KeyCodes.h
  Common/System/NativeApp.h
  Core/TiltEventProcessor.cpp
  Core/TiltEventProcessor.h
  Qt/QtMain.cpp
  UI/NativeApp.cpp
  UI/TiltAnalogSettingsScreen.cpp
  UI/TiltAnalogSettingsScreen.h
  android/jni/app-android.cpp
Labels: Platform-specific (Android), Qt, Input/Controller

#18256 ControlMapper: Fix a range check and array size. In reality, probably not a danger.
  Core/ControlMapper.cpp
  Core/ControlMapper.h
Labels: Code Cleanup

#18261 Revert "Merge pull request #18184 from hrydgard/expand-lines-mem-fix"
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#18266 irjit: Fix vhtfm instruction
  Core/MIPS/IR/IRCompVFPU.cpp
Labels: IRInterpreter

#18229 arm64jit: Enable in UI
  UI/GameSettingsScreen.cpp
Labels: arm64jit

#18172 Make clear detection a bit more lenient
  GPU/Common/SoftwareTransformCommon.cpp
Labels: GE emulation

#18176 Vulkan: Renderpass dependency fix
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
Labels: GE emulation

#18125 arm64jit: Optimize weight loading a bit
  Common/Arm64Emitter.cpp
  Common/Arm64Emitter.h
  GPU/Common/VertexDecoderArm64.cpp
Labels: arm64jit

#18193 assets/lang: Update zh_CN.ini
  assets/lang/zh_CN.ini
Labels: Translation

#18251 Control: Remove the axis event dupe filtering, batch events deeper
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/NativeApp.cpp
Labels: Input/Controller

#18268 SDL: Use an "EmuThread" in Vulkan mode
  SDL/SDLMain.cpp
Labels: SDL2

#18272 Change global UI messages to use an enum instead of strings.
  Common/System/System.h
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Core/PSPLoaders.cpp
  Core/RetroAchievements.cpp
  Qt/QtMain.cpp
  Qt/mainwindow.cpp
  Qt/mainwindow.h
  SDL/CocoaBarItems.mm
  SDL/SDLMain.cpp
  UI/DisplayLayoutScreen.cpp
  UI/DisplayLayoutScreen.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MainScreen.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/NativeApp.cpp
  UI/PSPNSApplicationDelegate.mm
  UI/RetroAchievementScreens.cpp
  UI/RetroAchievementScreens.h
  UI/SavedataScreen.cpp
  UI/SavedataScreen.h
  UI/TabbedDialogScreen.cpp
  UI/TabbedDialogScreen.h
  UWP/App.cpp
  UWP/UWPHelpers/LaunchItem.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
  android/jni/app-android.cpp
  headless/Headless.cpp
  ios/AppDelegate.mm
  libretro/libretro.cpp
  unittest/UnitTest.cpp
Labels: Code Cleanup

#18276 UI: Fix crash on input with no screens
  Common/UI/Screen.cpp
Labels: User Interface
