Repository hrydgard/ppsspp, pull requests merged in 2023-04, with the labels that each got.

#17212 More accurate check for LoadCLUT from framebuffer margins.
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#17214 softgpu: Fix over-optimization of alpha test
  GPU/Software/RasterizerRectangle.cpp
  headless/HeadlessHost.cpp
  headless/HeadlessHost.h
Labels: Software Rasterizer

#17216 OpenXR - Render glitches fixed
  Common/VR/PPSSPPVR.cpp
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/GLES/ShaderManagerGLES.cpp
  assets/compatvr.ini
Labels: VR

#17215 Control map multiple keys to one output
  Common/Data/Collections/TinySet.h
  Common/Input/GestureDetector.cpp
  Common/Input/InputState.cpp
  Common/Input/InputState.h
  Core/ControlMapper.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  Core/KeyMapDefaults.cpp
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  Windows/DinputDevice.cpp
  Windows/MainWindowMenu.cpp
  unittest/UnitTest.cpp
Labels: Input/Controller

#17217 Controls: Logic fix, optimization, remove hack
  Core/KeyMap.cpp
  UI/ControlMappingScreen.cpp
Labels: Input/Controller

#17218 Vulkan: Disable framebuffer fetch (through input attachments) for now.
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Vulkan

#17219 Vulkan: Fix a couple of validation errors
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
Labels: Vulkan

#17221 Use "If constexpr". Just #17197 rebased on master with some parts removed
  Core/MIPS/IR/IRInterpreter.cpp
  GPU/Common/SplineCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Software/BinManager.h
  GPU/Software/Rasterizer.cpp
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/Sampler.cpp
  GPU/Software/TransformUnit.cpp
Labels: Code Cleanup

#17222 Turn off light ubershader generation on Broadcom GPUs.
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Platform-specific (Linux/POSIX), Vulkan, GE emulation

#17225 SaveState: Attempt to recover from missing files
  Core/FileSystems/DirectoryFileSystem.cpp
Labels: Savestate

#17224 Add support for integer scale factor for display
  Core/Config.cpp
  Core/Config.h
  Core/HLE/sceIo.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  Tools/langtool/Cargo.lock
  UI/DisplayLayoutScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#17227 Libretro audio simplification
  libretro/Makefile.common
  libretro/README_WINDOWS.txt
  libretro/libretro.cpp
Labels: Libretro

#17232 Don't use inaccurate depth with Vulkan on any GPU
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Depth / Z, Vulkan, GE emulation

#17236 Integer scale tweaks
  Core/Config.cpp
  Core/Config.h
  Core/MIPS/MIPSStackWalk.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Software/SoftGpu.cpp
  Qt/mainwindow.cpp
  Qt/mainwindow.h
  UI/DisplayLayoutScreen.cpp
  Windows/MainWindowMenu.cpp
Labels: User Interface, Code Cleanup

#17237 Slider setting defaults
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Core/Config.cpp
  UI/ControlMappingScreen.cpp
  UI/CwCheatScreen.cpp
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/RemoteISOScreen.cpp
  UI/TiltAnalogSettingsScreen.cpp
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#17240 OpenXR - Game compatibility workarounds
  Core/Config.cpp
  Core/Config.h
  GPU/GLES/ShaderManagerGLES.cpp
  UI/GameSettingsScreen.cpp
  assets/compatvr.ini
Labels: VR

#17241 Chat window fixes
  UI/EmuScreen.cpp
Labels: User Interface

#17244 Debugger: Trigger mem breakpoints for mirrors
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/Breakpoints.h
  Core/MIPS/ARM/ArmCompFPU.cpp
  Core/MIPS/ARM/ArmCompLoadStore.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/ARM64/Arm64CompFPU.cpp
  Core/MIPS/ARM64/Arm64CompLoadStore.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MIPS/MIPSAnalyst.cpp
  Core/MIPS/MIPSDis.cpp
  Core/MIPS/MIPSInt.cpp
  Core/MIPS/x86/JitSafeMem.cpp
Labels: Debugger

#17247 Always tell Android we handled the BUTTON_MODE key
  UI/NativeApp.cpp
Labels: Platform-specific (Android)

#17238 Config refactoring, a first step
  CMakeLists.txt
  Core/Config.cpp
  Core/Config.h
  Core/ConfigSettings.cpp
  Core/ConfigSettings.h
  Core/ConfigValues.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#17252 Presentation: Switch from indexed trilist to plain tristrip
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
Labels: Code Cleanup

#17256 Debugger: Add named watch expressions
  CMakeLists.txt
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/Debugger_Disasm.h
  Windows/Debugger/Debugger_Lists.cpp
  Windows/Debugger/Debugger_Lists.h
  Windows/Debugger/WatchItemWindow.cpp
  Windows/Debugger/WatchItemWindow.h
  Windows/PPSSPP.vcxproj
  Windows/PPSSPP.vcxproj.filters
  Windows/W32Util/ContextMenu.h
  Windows/ppsspp.rc
  Windows/resource.h
Labels: Debugger

#17259 A few more debugger things
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Core/MIPS/MIPSDis.cpp
  Core/MIPS/MIPSDisVFPU.cpp
  Core/MIPS/MIPSIntVFPU.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/Debugger_Disasm.cpp
Labels: Debugger

#17260 Debugger: Accept format for watches and stack walk tweak
  Common/UI/PopupScreens.cpp
  Core/MIPS/MIPSStackWalk.cpp
  Windows/Debugger/Debugger_Lists.cpp
  Windows/Debugger/Debugger_Lists.h
  Windows/Debugger/WatchItemWindow.cpp
  Windows/Debugger/WatchItemWindow.h
  Windows/ppsspp.rc
  Windows/resource.h
Labels: Debugger

#17261 PresentationCommon: Simplify Y flip handling.
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
Labels: Code Cleanup

#17263 Debugger: sceKernelPrintf improvement, QOL adjustments
  Core/HLE/sceKernelMemory.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/MainWindowMenu.cpp
  Windows/ppsspp.rc
Labels: Debugger

#17269 Debugger: Avoid unaligned reads in expressions
  Core/Debugger/DisassemblyManager.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MemMap.h
  GPU/Common/GPUDebugInterface.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/Debugger_Lists.cpp
Labels: Debugger

#17254 Update Russian translation
  assets/lang/ru_RU.ini
Labels: Translation

#17270 Debugger: Add memory breakpoint conditions
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/Breakpoints.h
  Core/Debugger/WebSocket/BreakpointSubscriber.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/JitCommon/JitState.h
  Core/MIPS/MIPSAnalyst.cpp
  Core/MIPS/x86/CompFPU.cpp
  Core/MIPS/x86/CompLoadStore.cpp
  Core/MIPS/x86/CompVFPU.cpp
  Core/MIPS/x86/Jit.cpp
  Core/MIPS/x86/Jit.h
  Core/MIPS/x86/JitSafeMem.cpp
  Core/MIPS/x86/JitSafeMem.h
  Windows/Debugger/BreakpointWindow.cpp
  Windows/Debugger/BreakpointWindow.h
Labels: Debugger

#17273 OpenGL texture filtering: enforce key.mipEnable when we're forcing mip filtering on.
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#17272 More translation fixes
  Tools/langtool/Cargo.lock
  Tools/langtool/src/section.rs
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#17286 Control cleanup and fixes
  Core/Config.cpp
  Core/Config.h
  Core/ControlMapper.cpp
  UI/EmuScreen.cpp
  assets/lang/sv_SE.ini
Labels: Input/Controller

#17289 Properly fix the analog limiter feature ("lightly").
  Core/Config.cpp
  Core/Config.h
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  UI/EmuScreen.cpp
Labels: Input/Controller

#17291 Apply the fix to avoid jit clearing for rewind savestates to all platforms
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MIPS/MIPS/MipsJit.cpp
  Core/MIPS/fake/FakeJit.cpp
Labels: armjit, arm64jit

#17293 Camera on Android: Choose the preview framerate closest to 30fps.
  android/src/org/ppsspp/ppsspp/CameraHelper.java
Labels: Platform-specific (Android), Camera/Microphone

#17295 Optimize lighting for softgpu a bit
  GPU/Software/BinManager.cpp
  GPU/Software/BinManager.h
  GPU/Software/Lighting.cpp
  GPU/Software/Lighting.h
  GPU/Software/TransformUnit.cpp
Labels: Software Rasterizer

#17296 x86jit: Correct wrong PC after bad mem access, other minor
  Core/Core.cpp
  Core/HLE/HLE.cpp
  Core/HLE/sceKernelModule.cpp
  Core/MIPS/x86/Jit.cpp
Labels: Debugger

#17298 Don't try to present from little temp framebuffers used by Godfather to draw text
  Core/HLE/sceKernelModule.cpp
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#17297 Workaround for some SOCOM games' misuse of CLUT8 to texture from framebuffer
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureDecoder.cpp
  GPU/Common/TextureDecoder.h
  GPU/GLES/ShaderManagerGLES.h
  assets/compat.ini
Labels: GE emulation

#17302 Android: Update target version to SDK 33
  android/AndroidManifest.xml
  android/build.gradle
  android/jni/app-android.cpp
Labels: Platform-specific (Android)

#17303 Android: Upgrade gradle to the latest version
  android/build.gradle
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: Platform-specific (Android)

#17312 List Vulkan present modes in system info, show the current one
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  UI/DevScreens.cpp
Labels: User Interface

#17316 Apply the SOCOM fix to D3D9/ES2 depal shaders too
  GPU/Common/DepalettizeShaderCommon.cpp
Labels: D3D9, OpenGL

#17311 Resurrect and refactor the AxisSwap feature
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/EmuScreen.cpp
Labels: Input/Controller

#17317 Fix night vision in SOCOM games (in fact, fix the CLUT8 effect properly)
  GPU/Common/DepalettizeShaderCommon.cpp
Labels: GE emulation

#17318 PSPOskDialog: Add range check on keyboard layouts
  Core/Dialog/PSPOskDialog.cpp
  Core/Dialog/PSPOskDialog.h
Labels: HLE/Kernel

#17321 Fix an oversight when saving replacement textures on scoped storage
  Common/File/Path.cpp
  GPU/Common/TextureReplacer.cpp
Labels: Platform-specific (Android)

#17323 Add function UnescapeMenuString
  Common/StringUtils.cpp
  Common/StringUtils.h
  unittest/UnitTest.cpp
Labels: User Interface

#17322 Recognized types and Debug NSMenu for OS X
  CMakeLists.txt
  SDL/CocoaBarItems.h
  SDL/CocoaBarItems.mm
  SDL/SDLMain.cpp
  UI/PSPNSApplicationDelegate.h
  UI/PSPNSApplicationDelegate.mm
  macOS/Info.plist
Labels: Platform-specific (Mac OS X), User Interface

#17326 Native 'About' panel
  CMakeLists.txt
  SDL/CocoaBarItems.mm
  SDL/PPSSPPAboutViewController.h
  SDL/PPSSPPAboutViewController.m
Labels: Platform-specific (Mac OS X)

#17331 SDL: Enable precise (smooth touchpad) scrolling.
  SDL/SDLMain.cpp
Labels: Platform-specific (Linux/POSIX), Platform-specific (Mac OS X)

#17334 Add "Open Memory Stick" to File menu on Mac
  SDL/CocoaBarItems.mm
  SDL/SDLMain.cpp
  Windows/MainWindowMenu.cpp
Labels: Platform-specific (Mac OS X), User Interface

#17337 Fix iOS build
  CMakeLists.txt
Labels: Platform-specific (iOS), Platform-specific (Mac OS X)

#17332 Fix texcoord issue with SOCOM post effect
  Core/HLE/sceKernelModule.cpp
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#17338 Some fixes around popup lists and translations
  Common/Data/Text/I18n.h
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  GPU/Common/DepalettizeShaderCommon.cpp
  b.sh
Labels: User Interface

#17340 Mac translation work
  Core/Config.cpp
  SDL/CocoaBarItems.mm
  assets/lang/en_US.ini
  assets/lang/sv_SE.ini
Labels: Platform-specific (Mac OS X), User Interface

#17342 fix open in folder on macOS, avoid spawning the open command to open URLs
  SDL/CocoaBarItems.h
  SDL/CocoaBarItems.mm
  SDL/SDLMain.cpp
Labels: Platform-specific (Mac OS X)

#17346 Some more MacOS work
  SDL/CocoaBarItems.mm
  SDL/README.TXT
  Windows/MainWindowMenu.cpp
  assets/lang/sv_SE.ini
  macOS/Info.plist
  macOS/InfoGold.plist
Labels: Platform-specific (Mac OS X)

#17349 Memory safety: Replace many sprintf with snprintf
  Common/Buffer.cpp
  Common/Data/Text/Parsers.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/Math/expression_parser.cpp
  Common/Math/expression_parser.h
  Common/StringUtils.cpp
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Common/UI/View.cpp
  Core/CoreTiming.cpp
  Core/Debugger/DebugInterface.h
  Core/Debugger/DisassemblyManager.cpp
  Core/HLE/HLE.cpp
  Core/HLE/KernelThreadDebugInterface.h
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernel.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/JitCommon/JitBlockCache.cpp
  Core/MIPS/MIPSAnalyst.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/MIPSDebugInterface.h
  Core/MIPS/MIPSTables.cpp
  Core/MIPS/MIPSVFPUUtils.cpp
  Core/Util/PortManager.cpp
  Core/WebServer.cpp
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/GPUDebugInterface.cpp
  UI/MainScreen.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlDisAsmView.h
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/CtrlMemView.h
  Windows/Debugger/CtrlRegisterList.cpp
  Windows/Debugger/CtrlRegisterList.h
  Windows/Debugger/Debugger_MemoryDlg.cpp
  Windows/Debugger/Debugger_MemoryDlg.h
  Windows/Debugger/Debugger_VFPUDlg.cpp
  Windows/Debugger/DumpMemoryWindow.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/MainWindow.cpp
  Windows/W32Util/ShellUtil.cpp
  android/jni/app-android.cpp
Labels: Code Cleanup

#17351 Mac/Linux: Restart app on backend change
  SDL/CocoaBarItems.mm
  SDL/SDLMain.cpp
  SDL/SDLMain.mm
  UI/DarwinFileSystemServices.h
  UI/DarwinFileSystemServices.mm
Labels: Platform-specific (Linux/POSIX), Platform-specific (Mac OS X)

#17353 Don't try to use precise mousewheel events on old SDL versions.
  SDL/SDLMain.cpp
Labels: Platform-specific (Linux/POSIX)

#17358 Don't use the cpu_features library on Android arm32.
  Common/ArmCPUDetect.cpp
  android/build.gradle
Labels: Platform-specific (Android)

#17359 Less broken behavior with integer scale factor + auto render resolution
  GPU/Common/PresentationCommon.cpp
Labels: User Interface

#17360 Mac menu fixes
  Common/GPU/OpenGL/GLRenderManager.h
  SDL/CocoaBarItems.mm
Labels: Platform-specific (Mac OS X)

#17361 Fix wrong "game is running slow" warning on high-refresh-rate devices.
  Core/HW/Display.cpp
Labels: User Interface
