Repository hrydgard/ppsspp, pull requests merged in 2023-08, with the labels that each got.

#17823 More achievement UI work
  Common/System/OSD.cpp
  Common/System/OSD.h
  Common/UI/View.cpp
  Common/UI/ViewGroup.cpp
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  GPU/Common/DrawEngineCommon.cpp
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/EmuScreen.cpp
  UI/OnScreenDisplay.cpp
  UI/RetroAchievementScreens.cpp
  assets/lang/en_US.ini
  assets/lang/sv_SE.ini
Labels: User Interface, RetroAchievements

#17828 Leaderboard: Choose whether to see top players, or "around me"
  UI/RetroAchievementScreens.cpp
  UI/RetroAchievementScreens.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#17830 Updated brazilian portuguese translation
  assets/lang/pt_BR.ini
Labels: Translation

#17831 Vulkan: Don't use multithreaded rendering if buffer commands (frames in flight) is set to 1
  Common/GPU/thin3d.h
  SDL/SDLVulkanGraphicsContext.cpp
  Windows/GPU/WindowsVulkanContext.cpp
  android/jni/AndroidVulkanContext.cpp
  libretro/LibretroVulkanContext.cpp
Labels: Vulkan

#17833 Debug overlays: Refactor a pile of bools to an enum
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Core/HLE/sceDisplay.cpp
  Core/HW/Display.cpp
  GPU/Common/TextureCacheCommon.cpp
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  Windows/MainWindowMenu.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  headless/Headless.cpp
Labels: User Interface

#17834 OpenCFile: Fix Android content-uri append mode
  Common/File/FileUtil.cpp
Labels: Cheats

#17835 Move the debug overlay rendering out from EmuScreen into DebugOverlay.cpp
  CMakeLists.txt
  UI/DebugOverlay.cpp
  UI/DebugOverlay.h
  UI/EmuScreen.cpp
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  android/jni/Android.mk
Labels: Code Cleanup

#17758 SDL: support HiDPI on wayland
  Core/Core.cpp
  SDL/SDLMain.cpp
  macOS/Info.plist
  macOS/InfoGold.plist
Labels: SDL2

#17840 Vulkan: Use VK_KHR_present_wait to get numbers on how much latency we have to the screen
  Common/GPU/MiscTypes.h
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  UI/DebugOverlay.cpp
Labels: Vulkan, GE emulation

#17841 Linux/Mac/iOS: time_now_d(): Switch from gettimeofday() to clock_gettime(CLOCK_MONOTONIC)
  Common/TimeUtil.cpp
  Common/TimeUtil.h
Labels: Platform-specific (iOS), Platform-specific (Android), Platform-specific (Linux/POSIX), Platform-specific (Mac OS X)

#17843 Android: Measure display timing using VK_GOOGLE_display_timing
  Common/GPU/MiscTypes.h
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/TimeUtil.cpp
  Common/TimeUtil.h
  UI/DebugOverlay.cpp
  UI/DevScreens.cpp
  UI/RetroAchievementScreens.cpp
Labels: Platform-specific (Android)

#17838 Micro-optimize SubmitPrim, remove outdated mitigation
  GPU/Common/DrawEngineCommon.cpp
Labels: GE emulation

#17847 D3D11: Allow setting the max frame latency
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/GPU/thin3d_create.h
  UI/GameSettingsScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/GPU/D3D11Context.cpp
Labels: Platform-specific (Windows), Platform-specific (UWP), D3D11

#17849 MainScreen on Android TV: Add a button to enter a path by text input
  UI/MainScreen.cpp
Labels: Platform-specific (Android), User Interface, Scoped Storage

#17852 IR: centralize common parts of native backend
  CMakeLists.txt
  Common/CodeBlock.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/MIPS/IR/IRJit.h
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/RiscV/RiscVAsm.cpp
  Core/MIPS/RiscV/RiscVCompALU.cpp
  Core/MIPS/RiscV/RiscVCompBranch.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompLoadStore.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: RISC-V

#17854 Implement color emoji support for Android
  Common/Data/Encoding/Utf8.cpp
  Common/Data/Encoding/Utf8.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Render/Text/draw_text_android.cpp
  Common/Render/Text/draw_text_uwp.cpp
  UI/DevScreens.cpp
  UI/MiscScreens.cpp
  android/src/org/ppsspp/ppsspp/TextRenderer.java
Labels: Platform-specific (Android), User Interface

#17857 irjit: Fix mfvc eating prefixes
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRRegCache.cpp
Labels: IRInterpreter

#17856 Windows UWP: Enable color emoji rendering through DirectWrite
  Common/Data/Encoding/Utf8.h
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/Render/Text/draw_text_android.cpp
  Common/Render/Text/draw_text_uwp.cpp
  UI/MiscScreens.cpp
  Windows/GPU/D3D11Context.cpp
Labels: User Interface

#17859 irjit: Use Vec4 a bit more
  Core/MIPS/IR/IRCompFPU.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRFrontend.h
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
Labels: IRInterpreter

#17855 Achievement list: Support the more detailed categorization.
  UI/DebugOverlay.cpp
  UI/RetroAchievementScreens.cpp
  assets/lang/en_US.ini
Labels: RetroAchievements

#17861 Don't crash if VK_KHR_present_id / VK_KHR_present_wait are not exposed
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
Labels: Vulkan, intel gpu

#17862 Add yield() function to tell the CPU that we're busy-waiting (rare)
  Common/TimeUtil.cpp
  Common/TimeUtil.h
  Core/HLE/sceDisplay.cpp
  UI/EmuScreen.cpp
Labels: Platform-specific (Windows)

#17863 Merge NativeUpdate and NativeRender, we always call them together.
  Common/System/NativeApp.h
  Common/System/Request.h
  Core/Core.cpp
  UI/NativeApp.cpp
  UWP/PPSSPP_UWPMain.cpp
  android/jni/app-android.cpp
  headless/Headless.cpp
  ios/ViewController.mm
  libretro/libretro.cpp
  unittest/JitHarness.cpp
Labels: Code Cleanup

#17866 SDL: Break out event processing from main loop
  Core/Core.cpp
  Core/Core.h
  SDL/SDLJoystick.cpp
  SDL/SDLJoystick.h
  SDL/SDLMain.cpp
Labels: SDL2

#17867 Fix mac bundle version string.
  SDL/macbundle.sh
Labels: Platform-specific (Mac OS X)

#17868 Turn off the present-wait thread
  Common/GPU/MiscTypes.h
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  UI/DebugOverlay.cpp
Labels: Vulkan

#17871 Add back the self-render check that kept Ridge Racer working.
  GPU/Common/DrawEngineCommon.cpp
Labels: GE emulation

#17873 IR: Fix vqmul / Vec4Shuffle overlap
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  Core/MIPS/RiscV/RiscVRegCacheFPU.cpp
  Core/MIPS/RiscV/RiscVRegCacheFPU.h
Labels: IRInterpreter

#17874 IR: Simplify exits to ExitToConst when viable
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
Labels: IRInterpreter

#17875 RISC-V: Implement a few more ops
  Common/RiscVEmitter.cpp
  Common/RiscVEmitter.h
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/RiscV/RiscVAsm.cpp
  Core/MIPS/RiscV/RiscVCompALU.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
Labels: RISC-V

#17879 Call draw->Begin/EndFrame from outside the screen manager.
  Common/UI/UIScreen.cpp
  UI/EmuScreen.cpp
  UI/NativeApp.cpp
Labels: Code Cleanup

#17882 Vulkan: Split EndFrame and Present
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  UI/NativeApp.cpp
  Windows/GPU/D3D11Context.cpp
  Windows/GPU/D3D11Context.h
  Windows/GPU/D3D9Context.cpp
  Windows/MainWindow.cpp
  Windows/W32Util/Misc.cpp
  Windows/W32Util/Misc.h
  android/jni/AndroidVulkanContext.cpp
  android/jni/AndroidVulkanContext.h
Labels: Vulkan

#17884 Update gradle to 8.1.0
  build.gradle
Labels: Platform-specific (Android)

#17887 Separate submit/present for OpenGL as well
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  libretro/libretro.cpp
Labels: OpenGL, Code Cleanup

#17890 D3D presentation refactoring
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/GPU/thin3d_create.h
  Common/GraphicsContext.h
  Core/Core.cpp
  Qt/QtMain.h
  SDL/SDLGLGraphicsContext.h
  SDL/SDLMain.cpp
  SDL/SDLVulkanGraphicsContext.h
  UI/NativeApp.cpp
  UWP/App.cpp
  UWP/PPSSPP_UWPMain.cpp
  UWP/PPSSPP_UWPMain.h
  Windows/GPU/D3D11Context.cpp
  Windows/GPU/D3D11Context.h
  Windows/GPU/D3D9Context.cpp
  Windows/GPU/D3D9Context.h
  Windows/GPU/WindowsGLContext.cpp
  Windows/GPU/WindowsGLContext.h
  Windows/GPU/WindowsGraphicsContext.h
  Windows/GPU/WindowsVulkanContext.h
  android/jni/AndroidJavaGLContext.h
  android/jni/AndroidVulkanContext.h
  headless/SDLHeadlessHost.cpp
  headless/WindowsHeadlessHost.cpp
  ios/ViewController.mm
  libretro/LibretroGraphicsContext.h
  libretro/libretro.cpp
Labels: Code Cleanup

#17892 Revert "OpenGL: Separate submit/present for this backend as well"
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  libretro/libretro.cpp
Labels: OpenGL

#17893 riscv: Enable block linking
  Common/RiscVEmitter.cpp
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRJit.h
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/JitCommon/JitState.cpp
  Core/MIPS/RiscV/RiscVCompBranch.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
  UI/DevScreens.cpp
  ext/riscv-disas.cpp
Labels: RISC-V

#17895 IniFile: Store sections in unique_ptrs, instead of directly.
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Common/Data/Text/I18n.cpp
  GPU/Common/PostShader.cpp
  UI/Theme.cpp
Labels: User Interface

#17896 Frame timing struct
  Common/File/PathBrowser.cpp
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/CoreParameter.h
  Core/FrameTiming.cpp
  Core/FrameTiming.h
  Core/HLE/sceDisplay.cpp
  UI/NativeApp.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  android/jni/app-android.cpp
  libretro/Makefile.common
Labels: Code Cleanup

#17900 irjit: Implement vsge/vslt
  Core/MIPS/IR/IRCompFPU.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/x86/IRToX86.cpp
Labels: IRInterpreter

#17899 Minor RISC-V cleanups, frame profiler fix
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompLoadStore.cpp
  GPU/Common/TextureDecoder.cpp
  UI/EmuScreen.cpp
Labels: RISC-V

#17897 OpenGL: Separate submit and present, take 2
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  SDL/SDLGLGraphicsContext.cpp
  Windows/GPU/WindowsGLContext.cpp
  headless/SDLHeadlessHost.cpp
  libretro/libretro.cpp
Labels: OpenGL

#17901 riscv: Add debug log of block disasm
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
Labels: RISC-V

#17898 irjit: Cleanup/purge FPU/VFPU temps
  Core/MIPS/IR/IRAnalysis.cpp
  Core/MIPS/IR/IRAnalysis.h
  Core/MIPS/IR/IRPassSimplify.cpp
Labels: IRInterpreter

#17902 Some debug overlays don't make sense when not in-game, disable them
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Core/Core.cpp
  UI/DebugOverlay.cpp
  UI/EmuScreen.cpp
  libretro/LibretroGraphicsContext.h
Labels: User Interface

#17904 Fix crash from fontconfig
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Render/Text/draw_text_sdl.cpp
Labels: SDL2

#17907 riscv: Implement vs2i
  Core/MIPS/RiscV/RiscVCompVec.cpp
Labels: RISC-V

#17906 riscv: Fix crash on clear icache
  Core/MIPS/IR/IRNativeCommon.cpp
Labels: RISC-V

#17905 irjit: Implement some missing, handle partial Vec4s more
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/JitCommon/JitState.h
Labels: IRInterpreter

#17903 Present modes refactor
  CMakeLists.txt
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  Common/GPU/thin3d_create.h
  Common/GraphicsContext.h
  Core/Config.cpp
  Core/FrameTiming.cpp
  Core/FrameTiming.h
  Core/HLE/sceDisplay.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/Vulkan/GPU_Vulkan.cpp
  Qt/QtMain.h
  SDL/SDLGLGraphicsContext.cpp
  SDL/SDLGLGraphicsContext.h
  SDL/SDLVulkanGraphicsContext.h
  UI/DebugOverlay.cpp
  UI/DevScreens.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  UWP/PPSSPP_UWPMain.h
  Windows/GPU/D3D11Context.cpp
  Windows/GPU/D3D11Context.h
  Windows/GPU/D3D9Context.cpp
  Windows/GPU/D3D9Context.h
  Windows/GPU/WindowsGLContext.cpp
  Windows/GPU/WindowsGLContext.h
  Windows/GPU/WindowsVulkanContext.h
  android/jni/AndroidJavaGLContext.cpp
  android/jni/AndroidJavaGLContext.h
  android/jni/AndroidVulkanContext.cpp
  android/jni/AndroidVulkanContext.h
  headless/SDLHeadlessHost.cpp
  ios/ViewController.mm
  libretro/LibretroGLContext.cpp
  libretro/LibretroGLCoreContext.cpp
  libretro/LibretroGraphicsContext.h
  libretro/libretro.cpp
Labels: GE emulation

#17350 UWP Improvements
  Common/File/DirListing.cpp
  Common/File/DiskFree.cpp
  Common/File/FileUtil.cpp
  Common/File/Path.cpp
  Core/PSPLoaders.cpp
  Core/System.cpp
  UI/CwCheatScreen.cpp
  UI/DevScreens.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MemStickScreen.cpp
  UI/MemStickScreen.h
  UI/NativeApp.cpp
  UWP/App.cpp
  UWP/PPSSPP_UWPMain.cpp
  UWP/Package.appxmanifest
  UWP/PackageGold.appxmanifest
  UWP/PackageNormal.appxmanifest
  UWP/UWP.vcxproj
  UWP/UWP.vcxproj.filters
  UWP/UWPHelpers/LaunchItem.cpp
  UWP/UWPHelpers/LaunchItem.h
  UWP/UWPHelpers/StorageAccess.cpp
  UWP/UWPHelpers/StorageAccess.h
  UWP/UWPHelpers/StorageAsync.cpp
  UWP/UWPHelpers/StorageAsync.h
  UWP/UWPHelpers/StorageManager.cpp
  UWP/UWPHelpers/StorageManager.h
  UWP/UWPHelpers/StoragePickers.cpp
  UWP/UWPHelpers/StoragePickers.h
  ext/libzip/zip_source_file_win32_utf16.c
Labels: Platform-specific (UWP)

#17912 (UWP) Remove Win32/x86 Support
  UWP/Armips_UWP/Armips_UWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/PPSSPP_UWP.sln
  UWP/PPSSPP_UWPMain.cpp
  UWP/SPIRVCross_UWP/SPIRVCross_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UWP.vcxproj
  UWP/build_uwp.proj
  UWP/cpu_features_UWP/cpu_features_UWP.vcxproj
  UWP/glslang_UWP/glslang_UWP.vcxproj
  UWP/libkirk_UWP/libkirk_UWP.vcxproj
  UWP/libzstd_UWP/libzstd_UWP.vcxproj
  UWP/miniupnpc_UWP/miniupnpc_UWP.vcxproj
  UWP/rcheevos_UWP/rcheevos_UWP.vcxproj
  UWP/zlib_UWP/zlib_UWP.vcxproj
Labels: Platform-specific (UWP)

#17922 Add checkboxes in developer tools to allow disabling ubershaders
  Core/Config.cpp
  Core/Config.h
  GPU/Common/ShaderUniforms.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUCommonHW.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/en_US.ini
Labels: GE emulation

#17919 GamedataInstall: Add simple progress bar
  Core/Dialog/PSPGamedataInstallDialog.cpp
  Core/Dialog/PSPGamedataInstallDialog.h
  assets/lang/en_US.ini
Labels: HLE/Kernel

#17920 Minor debug text optimizations
  Common/Data/Encoding/Utf8.cpp
  Common/Data/Text/WrapText.cpp
  UI/DebugOverlay.cpp
Labels: User Interface, Code Cleanup

#17924 SDL: Actually use the chosen Vulkan device
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/PostShader.cpp
  SDL/SDLVulkanGraphicsContext.cpp
Labels: SDL2, Platform-specific (Linux/POSIX), Vulkan

#17925 Windows: Make switching UMD through "Emulation->Switch UMD" threadsafe
  UI/MainScreen.cpp
  UI/MainScreen.h
  Windows/MainWindowMenu.cpp
Labels: Platform-specific (Windows), User Interface

#17926 Windows: Fix "Create desktop shortcut" functionality
  UI/GameScreen.cpp
  UI/GameScreen.h
  Windows/W32Util/ShellUtil.cpp
  Windows/main.cpp
Labels: Platform-specific (Windows), User Interface

#17927 Windows: Memstick directory creation cleanup
  Common/GPU/thin3d.cpp
  Core/RetroAchievements.cpp
  Core/System.cpp
  Core/System.h
  GPU/GPUCommon.h
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  headless/Headless.cpp
  headless/WindowsHeadlessHost.h
Labels: Platform-specific (Windows), Code Cleanup

#17930 Enable anisotropic filtering for replacement textures with mipmaps
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation, Texture replacement

#17928 Unify memstick PSP/subdirectory creation
  Common/System/System.h
  Core/Config.cpp
  Core/System.cpp
  Core/System.h
  SDL/SDLMain.cpp
  UI/NativeApp.cpp
  Windows/main.cpp
Labels: Code Cleanup

#17935 irjit: Cleanup Write() calls with extra const
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInst.h
Labels: IRInterpreter

#17934 RISC-V: Centralize IR regcaches
  Core/HLE/sceKernel.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/RiscV/RiscVCompALU.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompLoadStore.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
  Core/MIPS/RiscV/RiscVRegCache.cpp
  Core/MIPS/RiscV/RiscVRegCache.h
  Core/MIPS/RiscV/RiscVRegCacheFPU.cpp
  Core/MIPS/RiscV/RiscVRegCacheFPU.h
Labels: Code Cleanup, RISC-V

#17937 Reduce time spent in IR compile
  Core/MIPS/IR/IRAnalysis.cpp
  Core/MIPS/IR/IRAnalysis.h
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
Labels: IRInterpreter

#17939 irjit: Implement vtfm 4x4 using dots
  Core/MIPS/IR/IRCompVFPU.cpp
Labels: IRInterpreter

#17938 Centralize IR regcache from RISC-V
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/RiscV/RiscVAsm.cpp
  Core/MIPS/RiscV/RiscVCompALU.cpp
  Core/MIPS/RiscV/RiscVCompBranch.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompLoadStore.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/RiscV/RiscVJit.h
  Core/MIPS/RiscV/RiscVRegCache.cpp
  Core/MIPS/RiscV/RiscVRegCache.h
  Core/MIPS/RiscV/RiscVRegCacheFPU.cpp
  Core/MIPS/RiscV/RiscVRegCacheFPU.h
Labels: RISC-V

#17941 riscv: Use a single reg for LO/HI
  Core/MIPS/RiscV/RiscVCompALU.cpp
Labels: RISC-V

#17942 irjit: Fix regalloc clobber on exit
  Core/MIPS/IR/IRAnalysis.cpp
Labels: RISC-V

#17914 [Windows] OSVersion improvements
  Common/OSVersion.cpp
  UWP/PPSSPP_UWPMain.cpp
  UWP/UWPHelpers/LaunchItem.cpp
Labels: Platform-specific (Windows)

#17947 [Adhocctl] Fix for Metal Gear Acid issue
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#17948 x86jit: Fix some issues in 32-bit
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/RiscV/RiscVRegCache.cpp
  Core/MIPS/RiscV/RiscVRegCache.h
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompLoadStore.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRJit.cpp
  Core/MIPS/x86/X64IRJit.h
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#17944 Implement a few ALU ops in the x86 JIT-IR backend.
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRRegCache.cpp
Labels: x86jit

#17953 jit: Skip known prefix writes
  Core/MIPS/ARM/ArmCompVFPU.cpp
  Core/MIPS/ARM/ArmCompVFPUNEON.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/ARM64/Arm64CompVFPU.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/JitCommon/JitState.h
  Core/MIPS/MIPSTables.cpp
  Core/MIPS/MIPSTables.h
  Core/MIPS/x86/CompVFPU.cpp
  Core/MIPS/x86/Jit.cpp
Labels: CPU emulation

#17954 x86jit: Fix Ext8to32/Ext16to32, some reg issues
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/x86/X64IRCompALU.cpp
Labels: x86jit

#17955 Update Vulkan headers
  ext/vulkan/vk_enum_string_helper.h
  ext/vulkan/vk_icd.h
  ext/vulkan/vk_layer.h
  ext/vulkan/vk_platform.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std_encode.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std_encode.h
  ext/vulkan/vk_video/vulkan_video_codecs_common.h
  ext/vulkan/vulkan.h
  ext/vulkan/vulkan_android.h
  ext/vulkan/vulkan_beta.h
  ext/vulkan/vulkan_core.h
  ext/vulkan/vulkan_directfb.h
  ext/vulkan/vulkan_fuchsia.h
  ext/vulkan/vulkan_ggp.h
  ext/vulkan/vulkan_ios.h
  ext/vulkan/vulkan_macos.h
  ext/vulkan/vulkan_metal.h
  ext/vulkan/vulkan_screen.h
  ext/vulkan/vulkan_vi.h
  ext/vulkan/vulkan_wayland.h
  ext/vulkan/vulkan_win32.h
  ext/vulkan/vulkan_xcb.h
  ext/vulkan/vulkan_xlib.h
  ext/vulkan/vulkan_xlib_xrandr.h
Labels: Vulkan

#17958 irjit: Fix vmin/vmax NAN handling
  Core/MIPS/IR/IRInterpreter.cpp
Labels: IRInterpreter

#17959 Update translation files with new strings.
  Tools/langtool/Cargo.lock
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#17961 Fix ordering problem with screenshots that was causing crashes.
  Common/UI/Screen.cpp
  Core/Screenshot.cpp
  SDL/CocoaBarItems.mm
  UI/NativeApp.cpp
Labels: User Interface

#17964 Implement more x86 vec4 ops, float compares, etc.
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRCompVec.cpp
  Core/MIPS/x86/X64IRJit.h
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#17962 Add mappable key to toggle networking
  Common/System/OSD.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/EmuScreen.cpp
  assets/lang/en_US.ini
Labels: User Interface

#17960 Controls: Make the analog/digital mapping clash resolution more gentle.
  Common/Input/InputState.h
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
Labels: Input/Controller

#17967 Android/controls: Fix pad autoconfigure bug
  Core/KeyMap.cpp
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
Labels: Platform-specific (Android)

#17965 Add compat flag to not load CLUTs from old framebuffers
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/TextureCacheCommon.cpp
  assets/compat.ini
Labels: GE emulation

#17970 Make System_ShowFileInFolder a "request"
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/W32Util/Misc.cpp
  Windows/W32Util/Misc.h
  Windows/main.cpp
  android/jni/app-android.cpp
  ios/ViewController.mm
Labels: Code Cleanup

#17971 Add "Create frame dump" to the in-game developer menu
  Core/Debugger/WebSocket/GPURecordSubscriber.cpp
  GPU/Debugger/Record.cpp
  GPU/Debugger/Record.h
  UI/DevScreens.cpp
  Windows/GEDebugger/GEDebugger.cpp
  assets/lang/en_US.ini
Labels: User Interface

#17972 Allow disabling HTTPS through the config file
  Common/Net/HTTPRequest.cpp
  Core/Config.cpp
  Core/Config.h
  SDL/SDLMain.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
Labels: Networking / adhoc

#17975 More x86 IR JIT
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompBranch.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRCompVec.cpp
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#17977 Log level/type: Use enum class instead of the awkward namespace trick.
  Common/ConsoleListener.cpp
  Common/ConsoleListener.h
  Common/Log.h
  Common/LogManager.cpp
  Common/LogManager.h
  Core/Debugger/WebSocket.cpp
  Core/Debugger/WebSocket/LogBroadcaster.cpp
  Core/Debugger/WebSocket/WebSocketUtils.h
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.h
  Core/HLE/HLE.cpp
  Core/HLE/HLE.h
  Core/MIPS/ARM64/Arm64Jit.cpp
  UI/DevScreens.cpp
  UI/NativeApp.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
Labels: Code Cleanup

#17979 Show the RetroAchievements icon in a bunch of notifications
  Common/StringUtils.h
  Core/RetroAchievements.cpp
  UI/DevScreens.cpp
  UI/OnScreenDisplay.cpp
Labels: User Interface, RetroAchievements

#17982 [Adhoc] An attempt to fix winsock error 10022 on Monster Hunter Freedom
  Core/HLE/proAdhoc.h
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#17984 RetroAchievements: Warn the user if has token and not logged in on start of game
  Core/RetroAchievements.cpp
Labels: RetroAchievements

#17989 irjit: Cleanup temp purging on exit
  Core/MIPS/IR/IRAnalysis.cpp
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRRegCache.cpp
Labels: x86jit

#17990 x86jit: Implement divides and a couple more ALUs
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#17991 x86jit: Improve vdot performance
  Core/MIPS/IR/IRCompVFPU.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/x86/X64IRCompVec.cpp
Labels: x86jit

#17994 x86: Use LEA in a few sensible places
  Core/MIPS/x86/X64IRCompALU.cpp
Labels: x86jit

#17992 x86jit: Implement trig instructions, couple other FPU
  Common/x64Emitter.cpp
  Common/x64Emitter.h
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVRegCache.cpp
  Core/MIPS/RiscV/RiscVRegCache.h
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRCompVec.cpp
  Core/MIPS/x86/X64IRJit.h
  Core/MIPS/x86/X64IRRegCache.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#17993 x86jit: Replacements, expose for profiling better
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/MIPS.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/x86/IRToX86.cpp
  Core/MIPS/x86/IRToX86.h
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRJit.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
Labels: x86jit

#17995 RetroAchievements: More connection notifications
  Core/RetroAchievements.cpp
  Core/RetroAchievements.h
  UI/RetroAchievementScreens.cpp
  assets/lang/en_US.ini
Labels: RetroAchievements

#17998 Minor: Correct RA login retry behavior if disabled, improved logging in CLUTLoad case
  Core/RetroAchievements.cpp
  GPU/Common/TextureCacheCommon.cpp
Labels: RetroAchievements

#18005 x86jit: Optimize slow memory
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
Labels: x86jit

#18004 x86jit: Small cleanup and tweaks, downcountInRegster, GetFPRLaneCount bugfix
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRCompALU.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/MIPS/x86/X64IRJit.cpp
  Core/MIPS/x86/X64IRRegCache.h
Labels: x86jit

#18006 x86jit: A few more ops, float literal pool
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MIPS/x86/X64IRCompFPU.cpp
  Core/MIPS/x86/X64IRCompVec.cpp
  Core/MIPS/x86/X64IRJit.cpp
  Core/MIPS/x86/X64IRJit.h
Labels: x86jit

#18007 x86jit: Implement CondStore
  Core/MIPS/x86/X64IRCompLoadStore.cpp
Labels: x86jit

#18001 Enable the FakeMipmapChange flag for US/EU Tactics Ogre, fixing replacement problem.
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  assets/compat.ini
Labels: Texture replacement

#18009 Enable [DisallowFramebufferAtOffset] for WWE SvR 2006.
  assets/compat.ini
Labels: GE emulation

#18010 Revert unnecessary log changes
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  GPU/Common/TextureReplacer.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Texture replacement

#18016 Bump gradle, after updating Android Studio again
  build.gradle
Labels: Platform-specific (Android)

#17644 Fix enabling of native keyboard input on Switch
  Core/Config.cpp
  Core/Dialog/PSPOskDialog.cpp
  SDL/SDLMain.cpp
Labels: Platform-specific (Switch), User Interface

#18019 Add more display information to the system info screen
  UI/ControlMappingScreen.cpp
  UI/DevScreens.cpp
  android/jni/app-android.cpp
Labels: User Interface

#18018 Shrink TexCacheEntry by 4 bytes and clean up a naming issue
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
Labels: Code Cleanup

#18013 Replace a too-simple heuristic with a compat flag, fixing Castlevania flicker.
  GPU/Common/FramebufferManagerCommon.cpp
  assets/compat.ini
Labels: GE emulation

#18025 x86jit: Fix a vec4 clobber issue
  Core/MIPS/IR/IRRegCache.cpp
Labels: x86jit

#18026 x86jit: Fix vsat0 saturate
  Core/MIPS/x86/X64IRCompFPU.cpp
Labels: x86jit

#18011 Detect the simplest Tactics Ogre case (US/EU) early
  GPU/Common/TextureCacheCommon.cpp
  assets/compat.ini
Labels: GE emulation, Texture replacement

#18022 Android: Fix changing display resolution scale in-game
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPUCommonHW.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/NativeApp.cpp
Labels: Platform-specific (Android)

#18028 Simplify the touch d-pad code.
  Core/HLE/sceCtrl.cpp
  UI/GamepadEmu.cpp
Labels: Code Cleanup

#18027 Debugger: Reduce cost of small copy tracking
  Core/Debugger/MemBlockInfo.cpp
Labels: Debugger

#18029 Control: Change internal interfaces to batch-process input axis updates
  Common/System/NativeApp.h
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Qt/QtMain.cpp
  SDL/SDLJoystick.cpp
  SDL/SDLMain.cpp
  UI/NativeApp.cpp
  Windows/DinputDevice.cpp
  Windows/WindowsHost.cpp
  Windows/XinputDevice.cpp
  android/jni/app-android.cpp
  ios/ViewController.mm
Labels: Input/Controller, Code Cleanup

#18030 Touch controls: Add an option for "Sticky D-Pad".
  Core/Config.h
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
Labels: Input/Controller
