Repository hrydgard/ppsspp, pull requests merged in 2023-11, with the labels that each got.

#18392 Record Atrac library version
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  Core/HLE/sceKernelModule.cpp
Labels: Atrac3+

#18369 Add Simulate UMD slow reading speed in UI
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/ConfigValues.h
  Core/HLE/sceIo.cpp
  UI/GameSettingsScreen.cpp
  assets/compat.ini
  libretro/libretro.cpp
Labels: I/O

#18372 Add empty shape to custom keys
  UI/GamepadEmu.h
  assets/ui_atlas.meta
  assets/ui_atlas.zim
  source_assets/image/empty.png
  ui_atlasscript.txt
Labels: User Interface

#18403 Fixes for tilt control bugs
  Common/Data/Format/IniFile.cpp
  Common/System/System.h
  Common/UI/PopupScreens.cpp
  Common/UI/View.cpp
  Core/TiltEventProcessor.cpp
  GPU/Common/GPUStateUtils.h
  SDL/SDLMain.cpp
  UI/GameSettingsScreen.cpp
  UI/TiltAnalogSettingsScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  android/jni/app-android.cpp
  ios/main.mm
Labels: Input/Controller

#18407 skip xinput trigger threshold check
  Windows/XinputDevice.cpp
Labels: Input/Controller

#18408 UI: Remove unnecessary mutexes, assorted cleanup
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/UI/Root.cpp
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  GPU/Vulkan/DrawEngineVulkan.h
  UI/EmuScreen.cpp
  Windows/XinputDevice.cpp
  Windows/XinputDevice.h
Labels: User Interface, Code Cleanup

#18413 Cache and hash data for DrawPixels
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
  GPU/ge_constants.h
Labels: GE emulation

#18416 Optimize DrawPixels for 16-bit RGB565 copies
  Common/Data/Convert/ColorConv.cpp
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#18414 Fix atrac sound loop problem
  Core/HLE/sceAtrac.cpp
Labels: Atrac3+

#18418 thin3d/backends: Remove code that pretended that we supported multiple vertex streams
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Render/DrawBuffer.cpp
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/StencilCommon.cpp
  GPU/GLES/DrawEngineGLES.cpp
Labels: Code Cleanup

#18419 Clean up the checks for triangle-button-for-info on the main screen
  Common/Input/InputState.cpp
  Common/Input/InputState.h
  Common/UI/View.cpp
  Common/UI/View.h
  Core/KeyMap.cpp
  UI/MainScreen.cpp
Labels: User Interface

#18425 RetroAchievements: Add option to allow saving, but not loading, in challenge / hardcore mode.
  Core/Config.cpp
  Core/Config.h
  Core/SaveState.cpp
  UI/PauseScreen.cpp
  UI/RetroAchievementScreens.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: RetroAchievements

#18428 Forgot some cases where I need to enable save (but not load) state in challenge mode, if the option is set
  Core/RetroAchievements.cpp
  Core/RetroAchievements.h
  UI/EmuScreen.cpp
  Windows/MainWindowMenu.cpp
Labels: Saving issue, RetroAchievements

#18435 An attempt to fix Tekken 6 stuck issue when exiting Lobby
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#18433 Fix building on OpenGL ES 2.0 (RPI VideoCore IV)
  Common/GPU/OpenGL/DataFormatGL.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
Labels: Platform-specific (Linux/POSIX)

#18438 OpenXR - Projection matrix on Quest 3 fixed
  Common/VR/PPSSPPVR.cpp
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: VR

#18446 Minor bbox optimizations, assorted bugfixes
  Common/VR/VRFramebuffer.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  Tools/langtool/Cargo.lock
  Tools/langtool/src/inifile.rs
  Tools/langtool/src/section.rs
  Windows/MainWindow.cpp
Labels: Code Cleanup

#18445 Make 3 games into compat
  assets/compat.ini
Labels: I/O

#18448 Android: Add *.chd and *.CHD to allowed path patterns for shortcut/intents
  android/AndroidManifest.xml
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Platform-specific (Android)

#18442 Track time-played per game
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Common/Data/Text/Parsers.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/Net/HTTPHeaders.cpp
  Common/TimeUtil.cpp
  Common/TimeUtil.h
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Core/Config.cpp
  Core/Config.h
  Core/RetroAchievements.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GameScreen.cpp
  UI/GameScreen.h
  android/jni/app-android.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18430 Handle SCE_UTILITY_SAVEDATA_TYPE_SAVE then SCE_UTILITY_SAVEDATA_TYPE_WRITEDATA
  Core/Dialog/SavedataParam.cpp
Labels: Saving issue

#18450 Enable some NEON optimizations on ARM32 that we only had on ARM64 before
  Core/MIPS/IR/IRInterpreter.cpp
  GPU/GPUCommon.cpp
  GPU/Math3D.h
  ppsspp_config.h
Labels: Code Cleanup
