Repository hrydgard/ppsspp, pull requests merged in 2023-01, with the labels that each got.

#16689 Vulkan: Avoid race in compile thread exit
  Common/GPU/Vulkan/VulkanRenderManager.cpp
Labels: Vulkan

#16690 softgpu: Detect binner alloc fail and bail
  Core/System.cpp
  GPU/GPU.cpp
  GPU/GPU.h
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/SoftGpu.h
  GPU/Software/TransformUnit.cpp
  GPU/Software/TransformUnit.h
Labels: Software Rasterizer

#16693 Add range checks in replaced memcpy/memset functions.
  Core/HLE/ReplaceTables.cpp
  Core/MemMap.h
  Core/MemMapFunctions.cpp
Labels: HLE/Kernel

#16697 Check for valid memory range when doing fast bone matrix loads
  GPU/GPUCommon.cpp
Labels: GE emulation

#16698 Screen background fixes
  UI/DevScreens.h
  UI/GameSettingsScreen.cpp
  UI/RemoteISOScreen.cpp
  UI/RemoteISOScreen.h
Labels: User Interface

#16676 Add disassembler for RISC-V
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/MIPS/JitCommon/JitBlockCache.cpp
  Core/MIPS/JitCommon/JitCommon.cpp
  Core/MIPS/JitCommon/JitCommon.h
  Core/MemFault.cpp
  GPU/Common/VertexDecoderCommon.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  ext/riscv-disas.cpp
  ext/riscv-disas.h
  unittest/JitHarness.cpp
  unittest/TestRiscVEmitter.cpp
Labels: RISC-V

#16699 Fix smooth touchpad scrolling on Windows
  Common/UI/ViewGroup.cpp
Labels: User Interface

#16701 Debugger: Allow copy of byte range from memview
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/CtrlMemView.h
Labels: Debugger

#16715 Eliminate GPU readbacks in the DTM Race Driver series.
  assets/compat.ini
Labels: GE emulation

#16610 Font: Avoid late load on save state
  Core/HLE/sceFont.cpp
Labels: PGF / sceFont

#16584 Pass in the vertex decoder to the shader ID computation
  GPU/Common/DrawEngineCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/VertexDecoderCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.h
Labels: Code Cleanup

#16628 Make fog-enable driven by uniform instead of fragment shader flag bit
  Common/GPU/D3D11/thin3d_d3d11.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUCommon.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: GE emulation

#16497 Cheats: Cleanup sizes of invalidates and checks
  Core/CwCheat.cpp
Labels: Cheats

#16624 Remove lmode shader flag from FS/GS
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/GeometryShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: GE emulation

#16726 GPU stat cleanups
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: Code Cleanup

#16729 Debugger: Fix mem lock with optimizations disabled
  Core/Debugger/WebSocket/MemorySubscriber.cpp
  Core/MIPS/JitCommon/JitCommon.cpp
  Windows/Debugger/CtrlMemView.cpp
Labels: Debugger

#16730 D3D9: Fix backbuffer screenshots
  Common/GPU/D3D9/thin3d_d3d9.cpp
Labels: D3D9

#16716 Android JNI: Try a bit harder to properly detach threads from the JVM when they exit
  Common/File/PathBrowser.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/Net/HTTPClient.cpp
  Common/Thread/ThreadManager.cpp
  Common/Thread/ThreadUtil.cpp
  Common/Thread/ThreadUtil.h
  Core/Config.cpp
  Core/Dialog/PSPSaveDialog.cpp
  Core/FileLoaders/CachingFileLoader.cpp
  Core/FileLoaders/RamCachingFileLoader.cpp
  Core/HLE/sceIo.cpp
  Core/HW/MemoryStick.cpp
  Core/PSPLoaders.cpp
  Core/Reporting.cpp
  Core/SaveState.cpp
  Core/Util/GameManager.cpp
  Core/WebServer.cpp
  UI/RemoteISOScreen.cpp
  android/README.TXT
  android/jni/app-android.cpp
  android/jni/app-android.h
Labels: Platform-specific (Android)

#16732 Debugger: Make sure we don't restore twice
  Core/Debugger/WebSocket/MemorySubscriber.cpp
Labels: Debugger

#16725 Windows: Adjust window sleep interval in idle menus to refresh rate
  Core/Core.cpp
  Windows/main.cpp
Labels: User Interface

#16696 Account for the GPU cycle cost of loading bone matrices.
  GPU/GPUCommon.cpp
Labels: GE emulation

#16737 GLES: Avoid a shader constant error
  GPU/Common/VertexShaderGenerator.cpp
Labels: GE emulation

#16743 D3D9: Force branch usage for fog compute
  GPU/Common/VertexShaderGenerator.cpp
Labels: D3D9

#16753 Use NEON intrinsics in software renderer
  GPU/Math3D.h
  GPU/Software/DrawPixel.cpp
  GPU/Software/Lighting.cpp
  GPU/Software/Rasterizer.cpp
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/Sampler.cpp
Labels: Software Rasterizer

#16762 Vulkan: Fix pipeline cache clearing.
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan

#16759 Better pipeline descriptions
  Common/Thread/Promise.h
  Common/UI/View.cpp
  Common/UI/View.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  UI/DevScreens.cpp
Labels: Debugger

#16765 Trying to improve sceMpegAvcDecode
  Core/HLE/sceMpeg.cpp
Labels: PSMF / MPEG

#16763 Shader generator: Move FS_TEX_ALPHA to a uniform bool.
  Core/Util/PPGeDraw.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Common/ShaderCommon.h
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/ShaderUniforms.h
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GPUCommon.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: GE emulation

#16720 Remove return values from Axis and Touch input functions
  Common/System/NativeApp.h
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/NativeApp.cpp
  UI/TiltAnalogSettingsScreen.cpp
  UI/TiltAnalogSettingsScreen.h
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeApp.java
  android/src/org/ppsspp/ppsspp/NativeGLView.java
  android/src/org/ppsspp/ppsspp/NativeSurfaceView.java
Labels: Input/Controller, Code Cleanup

#16309 Add InterruptManagerForKernel
  Core/HLE/HLETables.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelInterrupt.h
Labels: HLE/Kernel

#16771 Core: A bit more GetPointer cleanup.
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceP3da.cpp
  Core/HLE/sceRtc.cpp
  Core/HLE/sceUtility.cpp
  Core/MIPS/JitCommon/JitBlockCache.cpp
  Core/MemMap.h
  Core/TextureReplacer.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
Labels: Code Cleanup

#16779 UI theme improvements
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Common/UI/View.cpp
  Common/UI/View.h
  UI/MiscScreens.cpp
  UI/Theme.cpp
  assets/themes/defaultthemes.ini
Labels: User Interface

#16769 Uniform dirty-bits: Make room for four more uniforms.
  GPU/Common/ShaderCommon.h
Labels: GE emulation, Code Cleanup

#16782 GLES: Delete LinkedShaders after the program
  Common/GPU/OpenGL/GLRenderManager.h
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
Labels: OpenGL

#16783 GLES: Remove some unused depth related code
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
Labels: Code Cleanup

#16784 Break out ScrollView from ViewGroup.h, and PopupScreens from UIScreen.h
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Common/UI/Screen.cpp
  Common/UI/ScrollView.cpp
  Common/UI/ScrollView.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  UI/ChatScreen.cpp
  UI/ControlMappingScreen.cpp
  UI/DevScreens.h
  UI/DisplayLayoutScreen.h
  UI/MiscScreens.h
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#16785 UI: Make vertical scrollbars directly draggable
  Common/UI/ScrollView.cpp
  Common/UI/ScrollView.h
Labels: User Interface

#16778 Remove the rather redundant DoTexture flag from vshaders.
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/ShaderId.cpp
  GPU/Common/ShaderId.h
  GPU/Common/ShaderUniforms.h
  GPU/Common/VertexShaderGenerator.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: GE emulation, Code Cleanup

#16787 Vertex shaders: On platforms with uniform buffers, use indexing and loop over the lights.
  GPU/Common/ShaderUniforms.h
  GPU/Common/VertexShaderGenerator.cpp
Labels: Vulkan, D3D11

#16791 Lighting code cleanup and optimization
  Common/Data/Convert/SmallDataConvert.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/GLES/ShaderManagerGLES.cpp
Labels: GE emulation

#16795 Improve the use of space on the main screen in vertical mode.
  UI/MainScreen.cpp
Labels: User Interface

#16794 Remove the Android display resolution selector
  Core/Config.cpp
  Core/Config.h
  UI/ControlMappingScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/NativeApp.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/SizeManager.java
Labels: Platform-specific (Android)

#16734 Vulkan: Don't use non-indexed draws for pure tristrips and fans (only PowerVR for now)
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/IndexGenerator.h
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan, PowerVR GPU

#16095 Add some Sysclib 's nids
  Core/HLE/sceKernelInterrupt.cpp
Labels: HLE/Kernel

#16797 Android: Don't assert on failed Find4GBBase
  Common/MemArenaAndroid.cpp
  Core/MemMap.cpp
Labels: Platform-specific (Android)

#16800 Android: update measurements on UI thread
  android/src/org/ppsspp/ppsspp/SizeManager.java
Labels: Platform-specific (Android)

#16799 ffmpeg: Don't ask for multi-threaded decoding
  Core/HW/MediaEngine.cpp
  Core/HW/SimpleAudioDec.cpp
  Core/MemFault.cpp
Labels: PSMF / MPEG

#16185 Allow to append some configs
  Core/Config.cpp
  Core/Config.h
  UI/NativeApp.cpp
Labels: User Interface

#16804 Fix a race condition during Vulkan shader cache load.
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan

#16805 expose analog-is-circle functionality to libretro
  libretro/libretro.cpp
  libretro/libretro_core_options.h
Labels: Libretro

#16798 Add workaround for hung music notes in Rockman Dash 2
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/sceSas.cpp
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  assets/compat.ini
Labels: Audio

#16818 Fix a few warnings and a debugger emuhack bug on mem access
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Core/Debugger/WebSocket/MemorySubscriber.cpp
  Core/HLE/sceKernelHeap.cpp
  Core/TextureReplacer.cpp
Labels: Debugger

#16828 Add Warriors Orochi to [ReportSmallMemStick]
  assets/compat.ini
Labels: Saving issue

#16833 Memory stick customization option for Darwin platforms + improvements to the build system for iOS
  CMakeLists.txt
  Common/DarwinMemoryStickManager.h
  Common/DarwinMemoryStickManager.mm
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  cmake/Toolchains/ios.cmake
Labels: Platform-specific (iOS)

#16844 Display CRC on crash screen. Thanks sum2012 for the idea.
  Core/Reporting.cpp
  UI/EmuScreen.cpp
Labels: Debugger

#16848 Add more logging in sceFontFindOptimumFont
  Core/HLE/sceFont.cpp
Labels: PGF / sceFont

#16852 Add font's logging of requestedStyle
  Core/HLE/sceFont.cpp
Labels: PGF / sceFont

#16856 Update Russian translation
  assets/lang/en_US.ini
  assets/lang/ru_RU.ini
Labels: Translation

#16855 Add analog to custom button and gesture
  UI/GamepadEmu.h
Labels: Input/Controller

#16857 OpenXR - Control game camera using head rotation
  Common/Input/InputState.cpp
  Common/Input/InputState.h
  Common/Input/KeyCodes.h
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRRenderer.cpp
  Common/VR/VRRenderer.h
  Core/Config.cpp
  Core/Config.h
  Core/KeyMap.cpp
  UI/GameSettingsScreen.cpp
Labels: VR

#16861 UI: Show expected FPS if speed+FPS is on
  UI/EmuScreen.cpp
Labels: User Interface

#16864 GL refactor: Breakout a couple of commits
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
Labels: OpenGL

#16868 Update Vulkan headers to SDK 1.3.239
  ext/vulkan/vk_enum_string_helper.h
  ext/vulkan/vk_icd.h
  ext/vulkan/vk_layer.h
  ext/vulkan/vk_sdk_platform.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std_encode.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std_encode.h
  ext/vulkan/vk_video/vulkan_video_codecs_common.h
  ext/vulkan/vulkan_beta.h
  ext/vulkan/vulkan_core.h
  ext/vulkan/vulkan_profiles.h
Labels: Vulkan

#16867 Initialization cleanups
  Common/Net/NetBuffer.cpp
  Common/UI/Context.cpp
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Common/UI/Screen.cpp
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Core/Config.cpp
  Core/Core.cpp
  SDL/SDLMain.cpp
  UI/EmuScreen.cpp
  UI/NativeApp.cpp
Labels: Code Cleanup

#16704 Windows Dark Mode: initial support
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/Debugger_Disasm.h
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
  Windows/PPSSPP.vcxproj
  Windows/PPSSPP.vcxproj.filters
  Windows/W32Util/DarkMode.cpp
  Windows/W32Util/DarkMode.h
  Windows/W32Util/IatHook.h
  Windows/W32Util/UAHMenuBar.cpp
  Windows/W32Util/UAHMenuBar.h
  Windows/main.cpp
Labels: User Interface

#16156 OpenGL threading refactor
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Core/Core.cpp
  Core/Core.h
  Core/CoreTiming.cpp
  GPU/GLES/GPU_GLES.cpp
  Qt/QtMain.h
  SDL/SDLGLGraphicsContext.cpp
  SDL/SDLGLGraphicsContext.h
  Windows/EmuThread.cpp
  Windows/GPU/WindowsGLContext.cpp
  Windows/PPSSPP.vcxproj.filters
  android/jni/AndroidJavaGLContext.cpp
  android/jni/AndroidJavaGLContext.h
  android/jni/app-android.cpp
  headless/SDLHeadlessHost.cpp
  ios/ViewController.mm
  libretro/LibretroGLContext.h
  libretro/LibretroGLCoreContext.h
Labels: OpenGL

#16879 Fix vulkan mac libretro crash due to not creating the surface
  libretro/LibretroVulkanContext.cpp
  libretro/libretro_vulkan.cpp
Labels: Platform-specific (Mac OS X), Libretro

#16878 Restore settings to default - let you choose what to reset
  Common/UI/UIScreen.h
  Common/UI/View.cpp
  Common/UI/View.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  Windows/.gitignore
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface
