Repository hrydgard/ppsspp, pull requests merged in 2023-12, with the labels that each got.

#18454 Naruto Ultimate Ninja Heroes 2 video flicker fix: Take 3
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#18461 Add a compat.ini setting to allow delayed GPU readbacks
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  assets/compat.ini
Labels: GE emulation

#18462 Framebuffer listing overlay
  Core/ConfigValues.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.h
  UI/DebugOverlay.cpp
  UI/DevScreens.cpp
Labels: GE emulation, User Interface

#18466 Texture replacement: Prioritize ini file [hashes] section over just files in the "root" folder.
  GPU/Common/TextureReplacer.cpp
Labels: Texture replacement

#18468 RetroAchievements: Show rich presence message on pause screen, restriction tweaks
  Core/Config.cpp
  Core/Config.h
  Core/CwCheat.cpp
  Core/HLE/sceDisplay.cpp
  Core/RetroAchievements.cpp
  Core/RetroAchievements.h
  Core/SaveState.cpp
  UI/EmuScreen.cpp
  UI/PauseScreen.cpp
  UI/RetroAchievementScreens.cpp
  Windows/MainWindowMenu.cpp
Labels: RetroAchievements

#18472 Vulkan: Allow MSAA on modern-ish mobile devices, but add a little warning sign.
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Common/UI/ScrollView.cpp
  Common/UI/ScrollView.h
  UI/GameSettingsScreen.cpp
Labels: Vulkan

#18475 Vulkan: Fix double-free in the low-memory fallback. Also, reject too-big textures
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/GPUCommon.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan, GE emulation

#18476 VertexDecoder: Minor optimization for x86/64 CPUs not supporting SSE4.
  GPU/Common/VertexDecoderX86.cpp
Labels: GE emulation

#18477 D3D9: Apply a half-pixel offset in 2D shader draws.
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/ShaderWriter.h
  Common/GPU/thin3d.h
  GPU/Common/Draw2D.cpp
Labels: D3D9, GE emulation

#18478 Handle block transfers from RAM to depth buffers.
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/StencilCommon.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommonHW.cpp
  assets/compat.ini
Labels: GE emulation

#18488 Make some achievement settings (including Hardcore mode) configurable per-game.
  Core/Config.cpp
Labels: RetroAchievements

#18490 Homebrew Store: Do uninstalls on a thread
  Common/File/AndroidStorage.cpp
  Core/Util/GameDB.cpp
  Core/Util/GameManager.cpp
  Core/Util/GameManager.h
  UI/Store.cpp
  UI/Store.h
Labels: User Interface, Code Cleanup

#18493 fix ASAN error in Vec2<float>::Length()
  GPU/Math3D.cpp
Labels: Code Cleanup

#18489 Some changes and comments after running the memory profiler on Windows
  Common/Data/Collections/FixedSizeQueue.h
  Common/Render/DrawBuffer.h
  Common/UI/Context.cpp
  Common/UI/Context.h
  Common/UI/UI.cpp
  Common/UI/UI.h
  Common/UI/View.cpp
  Core/HLE/sceAudio.cpp
  Core/Util/GameDB.cpp
  UI/BackgroundAudio.h
  UI/DevScreens.cpp
  UI/GameInfoCache.cpp
  UI/NativeApp.cpp
Labels: Code Cleanup

#18485 Beats: Fix file permissions on FAT so it can see custom MP3s.
  Core/HLE/sceIo.cpp
Labels: I/O

#18497 Android: Batch motion events.
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/InputDeviceState.java
  android/src/org/ppsspp/ppsspp/NativeApp.java
  android/src/org/ppsspp/ppsspp/NativeGLView.java
  android/src/org/ppsspp/ppsspp/NativeSurfaceView.java
Labels: Platform-specific (Android)

#17808 Frustum-cull small draws
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Math/CrossSIMD.h
  Common/UI/View.cpp
  Core/Config.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  ppsspp_config.h
Labels: GE emulation

#18498 Use __loongarch_lp64 instead of __loongarch64 as it is deprecated
  ppsspp_config.h
Labels: LoongArch64

#18500 Implement full support for mouse input on Android
  Common/System/NativeApp.h
  SDL/SDLMain.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  Windows/RawInput.cpp
  Windows/WindowsHost.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/NativeApp.java
  android/src/org/ppsspp/ppsspp/NativeSurfaceView.java
Labels: Platform-specific (Android), Input/Controller, User Interface

#18505 Fix slowdown on zero-vertex draw calls
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/Common/VertexDecoderCommon.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#18506 [iOS] Update JIT enable method from project UTM
  ios/main.mm
Labels: Platform-specific (iOS)

#18511 Screen manager refactoring, preparation for running the game behind the pause screen
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/System/System.h
  Common/UI/Context.cpp
  Common/UI/Context.h
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/DisplayLayoutScreen.cpp
  UI/DisplayLayoutScreen.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GPUDriverTestScreen.cpp
  UI/GPUDriverTestScreen.h
  UI/GameScreen.cpp
  UI/GameScreen.h
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MemStickScreen.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/NativeApp.cpp
  UI/OnScreenDisplay.cpp
  UI/OnScreenDisplay.h
  UI/ReportScreen.cpp
  UI/ReportScreen.h
Labels: Code Cleanup

#18515 Run behind pause screen
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  Common/UI/View.h
  Common/UI/ViewGroup.cpp
  Core/Config.cpp
  Core/Config.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUInterface.h
  UI/BackgroundAudio.cpp
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GPUDriverTestScreen.cpp
  UI/GPUDriverTestScreen.h
  UI/GameScreen.cpp
  UI/GameScreen.h
  UI/MemStickScreen.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/NativeApp.cpp
  UI/OnScreenDisplay.cpp
  UI/OnScreenDisplay.h
  UI/PauseScreen.cpp
  UI/PauseScreen.h
  UI/ReportScreen.cpp
  UI/ReportScreen.h
  assets/ui_atlas.meta
  assets/ui_atlas.zim
  buildatlas.sh
  source_assets/image/pause.png
  ui_atlasscript.txt
Labels: User Interface

#18517 Run-behind-pause: Fix some edge cases with the transparent background setting
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  UI/EmuScreen.cpp
Labels: User Interface

#18519 Enable texture replacement filtering overrides even if file is missing
  GPU/Common/TextureCacheCommon.cpp
Labels: Texture replacement

#18520 OpenGL: Fix some confusion between gpu->BeginHostFrame and gpu->BeginFrame
  Core/HLE/sceDisplay.cpp
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/GPUInterface.h
Labels: GE emulation

#18508 [iOS] Little cleanup
  ios/main.mm
Labels: Platform-specific (iOS), Code Cleanup

#18524 Minor Android code cleanup
  Common/System/NativeApp.h
  UI/NativeApp.cpp
  android/jni/app-android.cpp
Labels: Platform-specific (Android), Code Cleanup

#18525 [GPU/GLES] Using reserve if possible
  GPU/Common/PostShader.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPUCommon.cpp
Labels: Code Cleanup

#18533 Tilt: Bugfix, make the deadzone circular, in addition to the inverse (low end radius).
  Core/Config.cpp
  Core/Config.h
  Core/TiltEventProcessor.cpp
  UI/TiltAnalogSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Input/Controller

#18535 Eliminate inf values resulting from depth range computation.
  Common/Math/math_util.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
Labels: GE emulation

#18534 Use the universally supported Vulkan "565" 16-bit texture format
  Core/HLE/sceDisplay.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/VulkanUtil.cpp
  GPU/Vulkan/VulkanUtil.h
Labels: Vulkan

#18537 UI image loading refactor
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Render/ManagedTexture.cpp
  Common/Render/ManagedTexture.h
  Common/UI/AsyncImageFileView.cpp
  Common/UI/Context.cpp
  Common/UI/Context.h
  Common/UI/Screen.cpp
  UI/EmuScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/MainScreen.cpp
  UI/MiscScreens.cpp
  UI/SavedataScreen.cpp
  UI/Store.cpp
Labels: Code Cleanup

#18538 Async texture load on Pause screen
  Common/Render/ManagedTexture.cpp
  Common/Render/ManagedTexture.h
  Common/Thread/Waitable.h
  Common/UI/AsyncImageFileView.cpp
  Common/UI/AsyncImageFileView.h
  Common/UI/Context.cpp
  UI/MiscScreens.cpp
  UI/Store.cpp
Labels: User Interface

#18541 Using const reference for C++17 range-based loop and freq used objects
  Common/CPUDetect.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/UI/Screen.cpp
  Core/Debugger/WebSocket/HLESubscriber.cpp
  Core/Dialog/SavedataParam.cpp
  Core/HLE/sceFont.cpp
  Core/HLE/sceKernelModule.cpp
  GPU/Common/PostShader.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  UI/DevScreens.cpp
  UI/GameScreen.cpp
  UI/ReportScreen.cpp
Labels: Code Cleanup

#18540 Expose --escape-exit and --pause-menu-exit to be set from the ini file
  Core/Config.cpp
  Core/Config.h
  UI/NativeApp.cpp
Labels: User Interface

#18542 Add a notification when loading a PPSSPP prx plugin
  Core/HLE/Plugins.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface, Plugins

#18546 [Common Data/Core Dialog HLE/GPU Common Vulkan] Optimize create smart pointers using C++17 std::make_*
  Common/Data/Format/IniFile.cpp
  Common/Data/Text/I18n.cpp
  Core/Dialog/SavedataParam.cpp
  Core/HLE/sceMpeg.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
Labels: Code Cleanup

#18543 Minor debugger-related crash fixes
  Core/Debugger/MemBlockInfo.cpp
  Windows/Debugger/Debugger_Lists.cpp
Labels: User Interface, Debugger

#18547 Fixed all set render state4 after DirectXState::Restore()
  Common/GPU/D3D9/D3D9StateCache.h
Labels: D3D9

#18550 [Common Data Net/Core Debugger HLE/GPU Debugger] Fixed reduction data type size to strict 32-bit integer
  Common/Data/Format/ZIMLoad.cpp
  Common/Net/HTTPServer.cpp
  Core/Debugger/SymbolMap.cpp
  Core/HLE/sceKernelModule.cpp
  GPU/Debugger/Playback.cpp
Labels: Code Cleanup

#18548 Adrenotools followup
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Platform-specific (Android), Adreno GPU

#18551 Mouse refactor, restore smoothing
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Render/ManagedTexture.cpp
  Common/UI/Context.cpp
  Common/UI/Context.h
  Core/TiltEventProcessor.cpp
  Core/TiltEventProcessor.h
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/NativeApp.cpp
  Windows/WindowsHost.cpp
Labels: Input/Controller, Code Cleanup

#18552 Fix issue with misdetection of framebuffer copies.
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#18555 Vulkan: UI texture loading error handling fixes
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/Render/ManagedTexture.cpp
Labels: User Interface

#18558 Enforce a max size for save state screenshot regardless of resolution mode
  Core/SaveState.cpp
  Core/Screenshot.cpp
Labels: User Interface

#18566 Stop opening some context menus when the game's not loaded
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GEDebugger/SimpleGLWindow.cpp
Labels: Debugger

#18568 Mouse wheel: Centralize the sending of KEY_UP events on a timer.
  SDL/SDLMain.cpp
  UI/NativeApp.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/MainWindow.cpp
  android/jni/app-android.cpp
Labels: User Interface, Code Cleanup

#18570 Assorted GE debugger crash fixes
  Core/SaveState.cpp
  GPU/GLES/GPU_GLES.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GEDebugger/CtrlDisplayListView.h
  Windows/GEDebugger/GEDebugger.cpp
Labels: Debugger

#18573 Defer frame waits if possible
  Core/FrameTiming.cpp
  Core/FrameTiming.h
  Core/HLE/sceDisplay.cpp
  UI/NativeApp.cpp
Labels: Vulkan, OpenGL

#18572 Add "Disable culling" as a speedhack for experimentation
  Core/Config.cpp
  Core/Config.h
  GPU/GPUCommonHW.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Guardband / Range Culling, GE emulation

#18579 Minor replaced insert to emplace C++11
  Common/Data/Format/IniFile.cpp
  Common/File/VFS/ZipFileReader.cpp
  Common/Math/expression_parser.cpp
  Common/UI/IconCache.cpp
  Core/MIPS/IR/IRNativeCommon.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
Labels: Code Cleanup

#18580 DescribePtr: Individually describe vertex decoders
  Core/HW/MediaEngine.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/VertexDecoderArm.cpp
  GPU/Common/VertexDecoderArm64.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/Common/VertexDecoderRiscV.cpp
  GPU/GPUCommon.cpp
Labels: GE emulation

#18585 Add setting to configure simulated key-up delay for mouse wheel events
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Input/Controller

#18587 Minor lighting optimization in vshader
  GPU/Common/VertexShaderGenerator.cpp
Labels: Code Cleanup

#18586 DrawEngine: Avoid decoding indices when we don't need them.
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/IndexGenerator.cpp
  GPU/Common/IndexGenerator.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/ge_constants.h
Labels: Code Cleanup

#18588 Vulkan render queue runner: Count commands in debug builds, like the GL backend.
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
Labels: GE emulation

#18592 Fix dir creation regression, improve error handling in homebrew install slightly
  Common/Data/Text/Parsers.cpp
  Common/File/FileUtil.cpp
  Core/Util/GameManager.cpp
  android/jni/app-android.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Platform-specific (Android)

#18591 Allow unpausing with keys bound to pause
  Core/KeyMap.h
  UI/EmuScreen.cpp
  UI/PauseScreen.cpp
  UI/PauseScreen.h
Labels: User Interface

#18589 Control Mappings: Organize bindings into categories
  Common/UI/View.cpp
  Common/UI/View.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  Core/KeyMap.cpp
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18596 More control refactor
  Core/ControlMapper.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  GPU/Common/DrawEngineCommon.cpp
  UI/ControlMappingScreen.cpp
Labels: Code Cleanup

#18599 Tactics Ogre: Remove a redundant GPU readback operation
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  assets/compat.ini
Labels: GE emulation

#18597 Combo key: Only trigger when keys are pressed in the mapped order
  Core/ControlMapper.cpp
  Core/ControlMapper.h
Labels: Input/Controller

#18610 Texture replacer: Fix for texture directories missing an ini file
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
Labels: Texture replacement

#18617 Various fixes and cleanup, thanks Unknown
  Common/UI/Screen.cpp
  Common/UI/ViewGroup.cpp
  Core/Config.cpp
  GPU/GPUCommonHW.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
Labels: Code Cleanup

#18621 Add "Analog trigger threshold" setting, for conversion of analog trigger inputs to digital button inputs.
  Core/Config.cpp
  Core/Config.h
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/KeyMap.cpp
  Core/KeyMap.h
  GPU/Common/TextureReplacer.cpp
  Tools/langtool/Cargo.lock
  UI/ControlMappingScreen.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Input/Controller

#18627 Remote game streaming: Add an option to put a tab on the main screen
  Core/Config.cpp
  Core/Config.h
  UI/MainScreen.cpp
  UI/MainScreen.h
  UI/RemoteISOScreen.cpp
  UI/RemoteISOScreen.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18628 Remote ISO: Allow streaming .chd, add reload button to game browser
  Common/File/Path.cpp
  Common/File/PathBrowser.h
  Core/WebServer.cpp
  UI/EmuScreen.cpp
  UI/MainScreen.cpp
Labels: User Interface

#18631 Remote ISO: Prepare to allow sharing folders directly
  Common/Net/HTTPClient.cpp
  Common/Net/HTTPHeaders.h
  Common/Net/HTTPServer.cpp
  Common/Net/Sinks.cpp
  Common/Net/Sinks.h
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Core/WebServer.cpp
  UI/RemoteISOScreen.cpp
Labels: Code Cleanup

#18633 Remote ISO: Add working support for streaming CHD files over the network
  Core/FileSystems/BlockDevices.cpp
  Core/FileSystems/BlockDevices.h
  Core/WebServer.cpp
  UI/RemoteISOScreen.cpp
Labels: User Interface

#18634 Misc fixes and cleanups (touch control opacity, etc)
  Common/ArmEmitter.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/ShaderTranslation.cpp
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/LogManager.cpp
  Common/LoongArchCPUDetect.cpp
  Common/Net/HTTPServer.cpp
  Common/Net/URL.cpp
  Common/Net/URL.h
  Common/RiscVCPUDetect.cpp
  Common/UI/PopupScreens.h
  Common/UI/View.h
  Core/Config.cpp
  Core/Dialog/SavedataParam.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/MIPSDisVFPU.cpp
  Core/MIPS/MIPSTables.cpp
  Core/PSPLoaders.cpp
  Core/Replay.cpp
  Core/RetroAchievements.cpp
  Core/SaveState.h
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexShaderGenerator.cpp
  GPU/Debugger/RecordFormat.h
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GeDisasm.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  UI/TiltAnalogSettingsScreen.cpp
  UI/TiltAnalogSettingsScreen.h
  UI/TouchControlLayoutScreen.cpp
  ios/iCade/iCadeReaderView.m
Labels: Code Cleanup

#18635 Add bindings for toggling mouse control and touch screen controls
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/EmuScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18636 Debugger: Add usec for breakpoint logging
  Core/MIPS/MIPSDebugInterface.cpp
Labels: Debugger

#18637 Add some more RISC-V extensions to emitter
  Common/CPUDetect.h
  Common/RiscVCPUDetect.cpp
  Common/RiscVEmitter.cpp
  Common/RiscVEmitter.h
  Core/HLE/sceAudio.cpp
  Core/MIPS/RiscV/RiscVCompFPU.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/RiscV/RiscVCompVec.cpp
  GPU/Common/VertexDecoderRiscV.cpp
Labels: RISC-V

#18638 Fix two minor tex replacement issues
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureReplacer.cpp
Labels: Texture replacement

#18640 Various fixes to PathBrowser etc to handle browsing HTTP subfolders
  Common/File/Path.cpp
  Common/File/PathBrowser.cpp
  Common/Net/URL.cpp
  UI/RemoteISOScreen.cpp
Labels: User Interface

#18639 Various changes to the webserver to handle serving HTTP subfolders
  Common/UI/PopupScreens.cpp
  Core/WebServer.cpp
Labels: User Interface

#18642 Vulkan barrier optimizations
  Common/GPU/Vulkan/VulkanBarrier.cpp
  Common/GPU/Vulkan/VulkanBarrier.h
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.h
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
Labels: Vulkan

#18644 Fix sceKernelExitGame (regressed with the run-in-background stuff)
  UI/EmuScreen.cpp
Labels: User Interface

#18645 Fix warning in scepsmf
  Core/HLE/scePsmf.cpp
Labels: PSMF / MPEG

#18650 Allow merging framebuffers vertically like the old Juiced 2 fix.
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  assets/compat.ini
Labels: GE emulation

#18647 Enforce run-behind-pause-screen if ad-hoc multiplayer active
  Core/Core.cpp
  Core/Core.h
  Core/HLE/sceNetAdhoc.cpp
  Core/HLE/sceNetAdhoc.h
  UI/EmuScreen.cpp
Labels: Networking / adhoc, User Interface

#18651 HTTPS through naett: Get the body of the response even if code isn't 200
  Common/Net/HTTPNaettRequest.cpp
Labels: RetroAchievements

#18654 Joystick: Bias down the axis-to-button threshold if the "co-axis" is active.
  Core/ControlMapper.cpp
  Core/ControlMapper.h
Labels: Input/Controller

#18655 Stick calibration/input: Fix inverse deadzone
  Common/Render/ManagedTexture.cpp
  Core/ControlMapper.cpp
Labels: Input/Controller
