Repository hrydgard/ppsspp, pull requests merged in 2023-03, with the labels that each got.

#17028 Fix crash in SoftGPU when frameskipping, noticed by sum2012 in Daxter
  GPU/Software/SoftGpu.cpp
Labels: Software Rasterizer

#17027 Vulkan on Android: In non-debug mode, avoid devices that were rejected by VulkanMayBeAvailable
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  android/jni/app-android.cpp
Labels: Platform-specific (Android), Vulkan

#17040 Update gradle
  android/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Platform-specific (Android)

#17042 Implement requested debugger features
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlDisAsmView.h
  Windows/ppsspp.rc
  Windows/resource.h
Labels: Debugger

#17047 riscv: Enable Zba/Zbb by soc compatible
  Common/RiscVCPUDetect.cpp
Labels: RISC-V

#17046 (UWP) More Cleanups
  UWP/UWP.vcxproj
Labels: Platform-specific (UWP)

#17032 Cache framebuffer copies (for self-texturing) until the next TexFlush GPU instruction
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
Labels: GE emulation

#17063 VFS cleanups
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/JSONReader.cpp
  Common/Data/Format/ZIMLoad.cpp
  Common/Data/Text/I18n.cpp
  Common/File/AndroidStorage.cpp
  Common/File/DirListing.h
  Common/File/VFS/AssetReader.h
  Common/File/VFS/DirectoryReader.cpp
  Common/File/VFS/DirectoryReader.h
  Common/File/VFS/VFS.cpp
  Common/File/VFS/VFS.h
  Common/File/VFS/ZipFileReader.cpp
  Common/File/VFS/ZipFileReader.h
  Common/GPU/OpenGL/GLSLProgram.cpp
  Common/Render/ManagedTexture.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/Reporting.cpp
  Core/Util/PPGeDraw.cpp
  Core/WebServer.cpp
  GPU/Common/PostShader.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  Qt/QtMain.h
  SDL/SDLJoystick.cpp
  UI/BackgroundAudio.cpp
  UI/GameInfoCache.cpp
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  UI/Theme.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/Android.mk
  android/jni/app-android.cpp
  headless/Headless.cpp
  headless/SDLHeadlessHost.cpp
  headless/WindowsHeadlessHost.cpp
  ios/PPSSPPUIApplication.mm
  libretro/Makefile.common
  libretro/libretro.cpp
Labels: Code Cleanup

#17072 More VFS work
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Common/Data/Text/I18n.cpp
  Common/File/VFS/DirectoryReader.cpp
  Common/File/VFS/DirectoryReader.h
  Common/File/VFS/VFS.cpp
  Common/File/VFS/VFS.h
  Common/File/VFS/ZipFileReader.cpp
  Common/File/VFS/ZipFileReader.h
  Core/Compatibility.cpp
  Core/Config.cpp
  Core/TextureReplacer.cpp
  GPU/Common/PostShader.cpp
  UI/Theme.cpp
  android/jni/app-android.cpp
  headless/Headless.cpp
Labels: Code Cleanup

#17067 Allow specifying the VFS when loading INI files.
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Common/Data/Text/I18n.cpp
  Common/File/VFS/VFS.h
  Core/Compatibility.cpp
  Core/Config.cpp
  Core/TextureReplacer.cpp
  GPU/Common/PostShader.cpp
  UI/Theme.cpp
Labels: Code Cleanup

#17074 Texture replacer: Faster way to get width/height from a png
  Common/Data/Format/PNGLoad.cpp
  Common/Data/Format/PNGLoad.h
  Core/TextureReplacer.cpp
Labels: Texture replacement

#17073 Use VFS for file access in the texture replacer
  Common/File/VFS/DirectoryReader.cpp
  Common/File/VFS/DirectoryReader.h
  Common/File/VFS/VFS.h
  Common/File/VFS/ZipFileReader.cpp
  Common/File/VFS/ZipFileReader.h
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
Labels: Code Cleanup, Texture replacement

#17034 Fix logic error: assign EGLSurface to EGLConfig
  Common/VR/VRBase.cpp
Labels: VR

#17078 Texture replacer: Make the internal cache model texture-centric instead of miplevel-centric
  Core/TextureReplacer.cpp
  Core/TextureReplacer.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup, Texture replacement

#17084 Remove hidden option ReplaceTextureAllowLate
  Core/Config.cpp
  Core/Config.h
  Core/TextureReplacer.cpp
Labels: Texture replacement

#17086 OpenXR - Foveation implemented (Quest headsets only)
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRBase.cpp
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRFramebuffer.h
  Common/VR/VRRenderer.cpp
  ext/openxr/openxr.h
Labels: VR

#17087 Move the texture replacer to GPU/Common
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  UI/GameSettingsScreen.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#17088 Replacer: Avoid tracking video textures
  Common/GPU/Vulkan/VulkanDebug.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureReplacer.h
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
Labels: Texture replacement

#17089 Texture replacer: Replace three flags with a state field in ReplacedTexture
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/GLES/TextureCacheGLES.cpp
Labels: Code Cleanup

#17090 TextureReplacer code cleanup: Move Populate to ReplacedTexture
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
Labels: Code Cleanup

#17091 Replacement: Do all I/O on threaded tasks
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
Labels: Texture replacement

#17083 DDS texture support in texture replacer
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Format/DDSLoad.cpp
  Common/Data/Format/DDSLoad.h
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/DataFormat.h
  Common/GPU/OpenGL/DataFormatGL.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Texture replacement

#17095 More tex replacement work
  Common/GPU/OpenGL/DataFormatGL.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/GLES/TextureCacheGLES.cpp
Labels: Texture replacement

#17096 Change BGRA to be a texture-specific flag. Fixes R/B swap in DDS textures in D3D11.
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
Labels: Texture replacement

#17098 OpenXR - Enable user to switch between topdown and fps camera
  Common/VR/PPSSPPVR.cpp
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
Labels: VR

#17097 Texture Replacement: Support compressed textures in D3D9 as well
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/DataFormatGL.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
  Common/GPU/OpenGL/GLFeatures.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  Tools/langtool/Cargo.lock
  Tools/langtool/Cargo.toml
  Tools/langtool/src/main.rs
  Tools/langtool/src/section.rs
  UI/DevScreens.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Texture replacement

#17103 Texture replacement: Load DDS mipmaps
  Common/Thread/ParallelLoop.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Texture replacement

#17104 basis_universal support: Add the library
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  GPU/Common/ReplacedTexture.cpp
  android/jni/Android.mk
  ext/basis_universal/basisu.h
  ext/basis_universal/basisu_containers.h
  ext/basis_universal/basisu_containers_impl.h
  ext/basis_universal/basisu_file_headers.h
  ext/basis_universal/basisu_transcoder.cpp
  ext/basis_universal/basisu_transcoder.h
  ext/basis_universal/basisu_transcoder_internal.h
  ext/basis_universal/basisu_transcoder_tables_astc.inc
  ext/basis_universal/basisu_transcoder_tables_astc_0_255.inc
  ext/basis_universal/basisu_transcoder_tables_atc_55.inc
  ext/basis_universal/basisu_transcoder_tables_atc_56.inc
  ext/basis_universal/basisu_transcoder_tables_bc7_m5_alpha.inc
  ext/basis_universal/basisu_transcoder_tables_bc7_m5_color.inc
  ext/basis_universal/basisu_transcoder_tables_dxt1_5.inc
  ext/basis_universal/basisu_transcoder_tables_dxt1_6.inc
  ext/basis_universal/basisu_transcoder_tables_pvrtc2_45.inc
  ext/basis_universal/basisu_transcoder_tables_pvrtc2_alpha_33.inc
  ext/basis_universal/basisu_transcoder_uastc.h
  libretro/Makefile.common
Labels: Texture replacement

#17106 Add translation strings for dark theme and "Scoped Storage"
  UI/DevScreens.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#17114 Vulkan: During texture upload, batch the buffer->image copies to do all the mips at once.
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Vulkan

#17118 OpenGL: Try a different way to exclude desktop tex compression formats in build
  Common/GPU/OpenGL/DataFormatGL.cpp
  Common/GPU/OpenGL/GLFeatures.cpp
Labels: Platform-specific (Linux/POSIX), OpenGL

#17120 More texture replacement fixes
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureReplacer.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
Labels: Texture replacement

#17121 Remove an unused VulkanPushBuffer.
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/TextureCacheVulkan.h
Labels: Vulkan, Code Cleanup

#17129 irjit: Fix vi2us/vi2s with non-consecutive
  Common/GPU/Vulkan/VulkanMemory.cpp
  Common/MemoryUtil.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
Labels: IRInterpreter

#17136 Zstd include fix
  GPU/Common/ReplacedTexture.cpp
  ext/basis_universal/basisu_transcoder.cpp
Labels: Code Cleanup

#17139 Texture replacement: Improve padding support
  Common/MemoryUtil.cpp
  Core/FileSystems/MetaFileSystem.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Texture replacement

#17143 Refactor the replacement "force filtering" feature
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Code Cleanup

#17144 Force mipmapping on when drawing using replacement textures that contain mipmaps
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
Labels: Texture replacement

#17130 Minor leak fix
  Core/HLE/sceAtrac.cpp
  Windows/TouchInputHandler.cpp
Labels: Code Cleanup

#17131 [what][style][gpu] some coding style refine
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
Labels: Code Cleanup

#17146 Improve default replacer ini
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
Labels: Code Cleanup

#17158 More system cleanup: Replace inputbox queue with something more generic
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/System/NativeApp.h
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  Core/Dialog/PSPOskDialog.cpp
  Qt/QtMain.cpp
  Qt/QtMain.h
  README.md
  SDL/SDLMain.cpp
  UI/ChatScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MemStickScreen.cpp
  UI/NativeApp.cpp
  UI/RemoteISOScreen.cpp
  UI/SavedataScreen.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/PPSSPP_UWPMain.cpp
  Windows/MainWindow.cpp
  Windows/main.cpp
  android/jni/Android.mk
  android/jni/app-android.cpp
  headless/Headless.cpp
  ios/main.mm
  libretro/Makefile.common
  libretro/libretro.cpp
  unittest/JitHarness.cpp
Labels: Code Cleanup

#17159 Port image selector to the new request manager
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  Windows/MainWindow.cpp
  Windows/MainWindow.h
  Windows/MainWindowMenu.cpp
  Windows/MainWindowMenu.h
  Windows/main.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/NativeApp.java
Labels: Code Cleanup

#17160 Port file browser to the request manager
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/MainScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  headless/Headless.cpp
  ios/main.mm
  libretro/libretro.cpp
  unittest/JitHarness.cpp
Labels: Platform-specific (iOS), Code Cleanup

#17161 Rtc fix
  Core/HLE/sceRtc.cpp
Labels: HLE/Kernel

#17162 Port folder browser to the request manager
  Common/File/Path.h
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/DarwinFileSystemServices.h
  UI/DarwinFileSystemServices.mm
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MemStickScreen.cpp
  UI/MemStickScreen.h
  UI/NativeApp.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  ios/main.mm
Labels: Platform-specific (Mac OS X)

#17163 Remove System_SendMessage()
  Common/System/Request.h
  Common/System/System.h
  Common/UI/View.cpp
  Core/HLE/sceUsbCam.cpp
  Core/HLE/sceUsbGps.cpp
  Core/HLE/sceUsbMic.cpp
  Core/System.cpp
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MemStickScreen.cpp
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  UI/PauseScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/AndroidVulkanContext.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  headless/Headless.cpp
  ios/ViewController.mm
  ios/main.mm
  libretro/libretro.cpp
  unittest/JitHarness.cpp
Labels: Code Cleanup

#17170 Don't forget to call CheckDepthUsage when using imm draws.
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.h
Labels: GE emulation

#17171 OpenXR - Camera mode offset
  Common/VR/PPSSPPVR.cpp
Labels: VR

#17172 UI: Fix weird misbehavior dragging outside a popup dialog
  Common/Input/GestureDetector.cpp
  Common/UI/UIScreen.cpp
Labels: User Interface

#17174 Remove polling requirement from DSound audio backend
  UI/NativeApp.cpp
  UWP/XAudioSoundStream.cpp
  Windows/DSoundStream.cpp
  Windows/DSoundStream.h
  Windows/WASAPIStream.h
  Windows/WindowsAudio.h
  Windows/WindowsHost.cpp
  Windows/WindowsHost.h
Labels: Code Cleanup

#17176 Move the resampler usage to a common file, AudioCommon.
  CMakeLists.txt
  Common/System/System.h
  Core/HLE/__sceAudio.cpp
  Core/HLE/__sceAudio.h
  Core/HW/StereoResampler.cpp
  Core/HW/StereoResampler.h
  UI/AudioCommon.cpp
  UI/AudioCommon.h
  UI/BackgroundAudio.cpp
  UI/EmuScreen.cpp
  UI/NativeApp.cpp
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  android/jni/Android.mk
  headless/Headless.cpp
  libretro/libretro.cpp
  unittest/UnitTest.cpp
Labels: Code Cleanup

#17178 More Host cleanup
  Common/System/Request.h
  Common/System/System.h
  Core/Debugger/SymbolMap.cpp
  Core/Debugger/SymbolMap.h
  Core/Host.cpp
  Core/Host.h
  Core/PSPLoaders.cpp
  Core/System.cpp
  Qt/QtHost.cpp
  Qt/QtHost.h
  Qt/QtMain.cpp
  UI/HostTypes.h
  UWP/UWPHost.cpp
  UWP/UWPHost.h
  Windows/EmuThread.cpp
  Windows/WindowsHost.cpp
  Windows/WindowsHost.h
  Windows/main.cpp
  headless/StubHost.h
  libretro/libretro.cpp
Labels: Code Cleanup

#17180 Even more "Host" code cleanup
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  Core/Host.h
  Core/PSPLoaders.cpp
  Qt/QtHost.h
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/HostTypes.h
  UI/NativeApp.cpp
  UWP/PPSSPP_UWPMain.cpp
  UWP/UWPHost.cpp
  UWP/UWPHost.h
  Windows/EmuThread.cpp
  Windows/InputDevice.cpp
  Windows/MainWindow.cpp
  Windows/MainWindow.h
  Windows/MainWindowMenu.cpp
  Windows/MainWindowMenu.h
  Windows/RawInput.cpp
  Windows/W32Util/ShellUtil.cpp
  Windows/W32Util/ShellUtil.h
  Windows/WindowsHost.cpp
  Windows/WindowsHost.h
  Windows/main.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
  unittest/UnitTest.cpp
Labels: Code Cleanup

#17181 Tales of Phantasia - Narikiri Dungeon X: Avoid some GPU readbacks.
  assets/compat.ini
Labels: GE emulation, GPU readback

#17177 libretro: Bypass PPSSPP's resampler, since libretro already has one
  UI/AudioCommon.cpp
  libretro/libretro.cpp
Labels: Audio, Libretro

#17188 Add compat setting to force using maximum depth resolution
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/GPUCommonHW.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  assets/compat.ini
Labels: GE emulation

#17190 Debugger: Update symbols properly on prx load
  Core/HLE/sceKernelModule.cpp
Labels: Debugger

#17189 Miscellaneous cleanup from recent changes
  CMakeLists.txt
  Common/System/Request.cpp
  Common/System/Request.h
  Common/System/System.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelModule.cpp
  Core/Host.cpp
  Core/Host.h
  Core/PSPLoaders.cpp
  GPU/Common/ReplacedTexture.cpp
  Qt/QtMain.cpp
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  UI/SavedataScreen.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  Windows/EmuThread.cpp
  Windows/GEDebugger/TabDisplayLists.cpp
  Windows/main.cpp
  android/jni/Android.mk
  headless/Compare.cpp
  headless/Headless.cpp
  headless/Headless.vcxproj
  headless/Headless.vcxproj.filters
  headless/HeadlessHost.cpp
  headless/HeadlessHost.h
  headless/SDLHeadlessHost.h
  headless/WindowsHeadlessHost.h
  ios/ViewController.mm
  libretro/Makefile.common
  libretro/libretro.cpp
Labels: Code Cleanup

#17193 Combo key: Finish rename
  CMakeLists.txt
  Core/Config.cpp
  Core/Config.h
  UI/CustomButtonMappingScreen.cpp
  UI/CustomButtonMappingScreen.h
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  UI/TouchControlLayoutScreen.cpp
  UI/TouchControlVisibilityScreen.cpp
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  android/jni/Android.mk
Labels: Code Cleanup

#17194 headless: Remove printfEmuLog, simplify output
  Common/System/Request.h
  Core/CoreParameter.h
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelModule.cpp
  UI/EmuScreen.cpp
  android/jni/TestRunner.cpp
  headless/Headless.cpp
  headless/HeadlessHost.cpp
  headless/HeadlessHost.h
  headless/WindowsHeadlessHost.cpp
  libretro/libretro.cpp
Labels: Code Cleanup

#17196 UI: Avoid reloading PIC1 BG on game start & add plugin shutdown param
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.h
  UI/EmuScreen.cpp
Labels: Debugger

#17200 More renaming of control mapping stuff
  Common/VR/PPSSPPVR.cpp
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/ELF/PBPReader.h
  Core/KeyMap.cpp
  Core/KeyMap.h
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  UI/MainScreen.cpp
Labels: Input/Controller, Code Cleanup

#17199 Replacement: Save textures even if already replaced, if the texture file is missing.
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/GPUCommonHW.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
Labels: Texture replacement

#16984 VFPU sin/cos
  CMakeLists.txt
  Core/MIPS/MIPSIntVFPU.cpp
  Core/MIPS/MIPSVFPUUtils.cpp
  Core/MIPS/MIPSVFPUUtils.h
  Core/System.cpp
  assets/vfpu/vfpu_asin_lut65536.dat
  assets/vfpu/vfpu_asin_lut_deltas.dat
  assets/vfpu/vfpu_asin_lut_indices.dat
  assets/vfpu/vfpu_exp2_lut.dat
  assets/vfpu/vfpu_exp2_lut65536.dat
  assets/vfpu/vfpu_log2_lut.dat
  assets/vfpu/vfpu_log2_lut65536.dat
  assets/vfpu/vfpu_log2_lut65536_quadratic.dat
  assets/vfpu/vfpu_rcp_lut.dat
  assets/vfpu/vfpu_rsqrt_lut.dat
  assets/vfpu/vfpu_sin_lut8192.dat
  assets/vfpu/vfpu_sin_lut_delta.dat
  assets/vfpu/vfpu_sin_lut_exceptions.dat
  assets/vfpu/vfpu_sin_lut_interval_delta.dat
  assets/vfpu/vfpu_sqrt_lut.dat
  unittest/JitHarness.cpp
  unittest/UnitTest.cpp
Labels: CPU emulation

#17206 Debugger: Fix memory viewer, inverted check
  Windows/Debugger/CtrlMemView.cpp
Labels: Debugger

#17208 Rename KeyDef to InputMapping and give it responsibility for Axis encoding
  Common/Input/InputState.cpp
  Common/Input/InputState.h
  Common/Input/KeyCodes.h
  Common/UI/View.cpp
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Core/ControlMapper.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  Core/KeyMapDefaults.cpp
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/NativeApp.cpp
Labels: Code Cleanup

#17209 ControlMapper: Change the callbacks to be more suitable for the upcoming refactor.
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  Core/HLE/sceCtrl.cpp
  Core/HLE/sceCtrl.h
  UI/ControlMappingScreen.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/JoystickHistoryView.cpp
Labels: Input/Controller, Code Cleanup

#17211 Show a MIPS stack trace on crash screen
  Core/ControlMapper.cpp
  Core/Core.cpp
  Core/Core.h
  Core/HLE/sceKernel.cpp
  Core/MIPS/MIPSStackWalk.cpp
  Core/MIPS/MIPSStackWalk.h
  Core/MemFault.cpp
  Core/MemFault.h
  UI/EmuScreen.cpp
  libretro/Makefile.common
Labels: Debugger
