Repository hrydgard/ppsspp, pull requests merged in 2023-02, with the labels that each got.

#16870 libretro: Probably fix macOS cpu_features build
  libretro/Makefile.common
Labels: Libretro

#16883 Update Simplified Chinese
  assets/lang/zh_CN.ini
Labels: Translation

#16802 Vulkan: Parallel pipeline creation
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  GPU/Vulkan/ShaderManagerVulkan.cpp
Labels: Vulkan

#16898 Fix texture alpha when texturing from full-alpha textures.
  GPU/Common/ShaderUniforms.cpp
  GPU/GPUState.h
Labels: GE emulation

#16901 OpenXR - Fix rendering on PicoOS 5.3
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRRenderer.cpp
Labels: VR

#16903 Attempt at libretro buildfix
  Common/VR/VRFramebuffer.cpp
Labels: Libretro

#16905 Depth readback with built-in stretchblit
  CMakeLists.txt
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: GE emulation, Code Cleanup

#16907 Fix Syphon Filter lens flares by adding compat flag to read back the depth buffer
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/GPU.cpp
  GPU/GPU.h
  assets/compat.ini
Labels: GE emulation

#16908 Quick fix for the lens flare in Burnout
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#16910 Prepare for adding async readback (use VMA for readback allocs, add a param)
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/StencilBufferGLES.cpp
Labels: Vulkan, Code Cleanup

#16914 Some more plumbing of parameters, preparing for readback stuff
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GLES/StencilBufferGLES.cpp
Labels: Code Cleanup

#16921 vulkan: Add the function realization of arm device to kms vulkan
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  SDL/SDLMain.cpp
  SDL/SDLVulkanGraphicsContext.cpp
Labels: Platform-specific (Linux/POSIX), Vulkan

#16919 Move GLFrameData out of GLRenderManager.
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/GPU/OpenGL/GLFrameData.cpp
  Common/GPU/OpenGL/GLFrameData.h
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/OpenGL/GLQueueRunner.h
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#16928 Workaround for sin/cos issue in GTA on Mac (and maybe others)
  Core/MIPS/MIPSVFPUUtils.cpp
Labels: Platform-specific (Mac OS X)

#16930 OpenXR - Option to disable automatic switch between 2D and VR
  Common/VR/PPSSPPVR.cpp
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
Labels: VR

#16932 Eat some cycles in sceGeListSync, count listsyncs and drawsyncs in gpu stats
  Core/HLE/sceGe.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
Labels: GE emulation

#16916 Implement delayed depth readbacks, Vulkan only
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPU.h
  GPU/GPUCommon.cpp
Labels: Vulkan, GE emulation

#16937 Reduce button touch scale
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
Labels: Input/Controller, User Interface

#16945 Format memory tags using less allocations
  Core/Debugger/MemBlockInfo.cpp
  Core/Debugger/MemBlockInfo.h
  Core/HLE/ReplaceTables.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceDeflt.cpp
  Core/HLE/sceDmac.cpp
  Core/HLE/sceKernelInterrupt.cpp
Labels: Code Cleanup

#16947 Depth scale fixes
  GPU/Common/DepalettizeShaderCommon.cpp
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/Draw2D.cpp
  GPU/Common/Draw2D.h
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  unittest/UnitTest.cpp
Labels: GE emulation

#16951 Tilt control: Split the deadzone parameter since it needs to be different for different types
  Core/Config.cpp
  Core/Config.h
  Core/TiltEventProcessor.cpp
  Core/TiltEventProcessor.h
  UI/EmuScreen.cpp
  UI/NativeApp.cpp
  UI/TiltAnalogSettingsScreen.cpp
Labels: Input/Controller

#16953 Stereo rendering minor UI fix
  UI/GameSettingsScreen.cpp
Labels: User Interface

#16957 riscv: Initial vertexjit
  CMakeLists.txt
  Common/CommonFuncs.h
  Common/RiscVEmitter.cpp
  Common/RiscVEmitter.h
  Core/Dialog/PSPOskDialog.cpp
  Core/MIPS/JitCommon/JitBlockCache.cpp
  Core/MIPS/JitCommon/JitState.cpp
  GPU/Common/VertexDecoderArm64.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/Common/VertexDecoderRiscV.cpp
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/Software/RasterizerRegCache.cpp
  GPU/Software/RasterizerRegCache.h
Labels: RISC-V

#16958 Rewind cleanups
  Common/Serialize/Serializer.h
  Core/Config.cpp
  Core/Config.h
  Core/SaveState.cpp
  UI/GameSettingsScreen.cpp
  UI/PauseScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  libretro/libretro.cpp
Labels: User Interface

#16968 riscv: Include morph in vertexjit
  Common/RiscVEmitter.cpp
  GPU/Common/VertexDecoderRiscV.cpp
Labels: RISC-V

#16969 libretro: Update flags for Android ndk-build
  libretro/Makefile.common
Labels: Libretro

#16967 Eat some CPU cycles in sceUtilityOskUpdate. Works around timing bug in Ghost Recon Predator.
  Core/HLE/sceUtility.cpp
Labels: HLE/Kernel

#16961 Add limited support for block transfer of depth buffers. Fixes Iron Man.
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  assets/compat.ini
Labels: GE emulation, Depth Texture

#16971 Add a heuristic avoiding joining framebuffers horizontally...
  GPU/Common/FramebufferManagerCommon.cpp
Labels: GE emulation

#16974 Tilt: Fix sensitivity for digital mappings, simplify things
  Common/GPU/Vulkan/VulkanContext.cpp
  Core/Config.cpp
  Core/Config.h
  Core/TiltEventProcessor.cpp
  Core/TiltEventProcessor.h
  UI/NativeApp.cpp
  UI/TiltAnalogSettingsScreen.cpp
Labels: Input/Controller

#16976 riscv: Implement skinning in vertexjit
  Common/CPUDetect.h
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/RiscVCPUDetect.cpp
  Common/RiscVEmitter.cpp
  Common/RiscVEmitter.h
  GPU/Common/VertexDecoderCommon.h
  GPU/Common/VertexDecoderRiscV.cpp
Labels: RISC-V

#16997 Retarget UWP projects for latest VS version
  UWP/Armips_UWP/Armips_UWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/Package.appxmanifest
  UWP/SPIRVCross_UWP/SPIRVCross_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UWP.vcxproj
  UWP/cpu_features_UWP/cpu_features_UWP.vcxproj
  UWP/cpu_features_UWP/cpu_features_UWP.vcxproj.filters
  UWP/glslang_UWP/glslang_UWP.vcxproj
  UWP/glslang_UWP/glslang_UWP.vcxproj.filters
  UWP/libkirk_UWP/libkirk_UWP.vcxproj
  UWP/libzstd_UWP/libzstd_UWP.vcxproj
  UWP/miniupnpc_UWP/miniupnpc_UWP.vcxproj
  UWP/zlib_UWP/zlib_UWP.vcxproj
Labels: Code Cleanup

#16995 Some minor code cleanups (merge two functions, remove a parameter)
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/UI/UIScreen.cpp
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/StencilBufferGLES.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GLES/TextureCacheGLES.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  UI/EmuScreen.cpp
  UI/MiscScreens.cpp
Labels: Code Cleanup

#16998 Wrap the display globals in a struct
  CMakeLists.txt
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/Render/DrawBuffer.cpp
  Common/Render/Text/draw_text.cpp
  Common/System/Display.cpp
  Common/System/Display.h
  Common/UI/Context.cpp
  Common/UI/Screen.cpp
  Common/UI/UIScreen.cpp
  Core/Core.cpp
  Core/HLE/sceIo.cpp
  Core/Screenshot.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/ShaderUniforms.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  Qt/QtMain.cpp
  Qt/mainwindow.cpp
  SDL/SDLGLGraphicsContext.cpp
  SDL/SDLMain.cpp
  SDL/SDLVulkanGraphicsContext.cpp
  UI/ControlMappingScreen.cpp
  UI/DevScreens.cpp
  UI/DisplayLayoutScreen.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  UI/ReportScreen.cpp
  UI/TouchControlLayoutScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/CtrlRegisterList.cpp
  Windows/Debugger/Debugger_MemoryDlg.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GPU/D3D11Context.cpp
  Windows/GPU/D3D9Context.cpp
  Windows/MainWindow.cpp
  Windows/TouchInputHandler.cpp
  Windows/WindowsHost.cpp
  android/jni/AndroidJavaGLContext.cpp
  android/jni/TestRunner.cpp
  android/jni/app-android.cpp
  ios/DisplayManager.mm
  ios/ViewController.mm
Labels: Code Cleanup

#17000 More rendering cleanup
  GPU/Common/DrawEngineCommon.h
  GPU/D3D11/FramebufferManagerD3D11.cpp
  GPU/D3D11/FramebufferManagerD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/Directx9/FramebufferManagerDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/FramebufferManagerGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.h
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
Labels: Code Cleanup

#17001 Introduce GPUCommonHW (code cleanup)
  CMakeLists.txt
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/Software/SoftGpu.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#17002 Move a bunch of stuff that belongs in GPUCommonHW into it
  Core/HLE/sceDisplay.cpp
  GPU/Common/ShaderCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/Directx9/ShaderManagerDX9.cpp
  GPU/Directx9/ShaderManagerDX9.h
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GLES/ShaderManagerGLES.h
  GPU/GLES/TextureCacheGLES.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/ShaderManagerVulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  GPU/Vulkan/VulkanUtil.cpp
  GPU/Vulkan/VulkanUtil.h
Labels: Code Cleanup

#17004 Move more stuff to GPUCommonHW
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.cpp
  GPU/Vulkan/FramebufferManagerVulkan.h
Labels: Code Cleanup

#17006 Move more stuff to GPUCommonHW
  GPU/Common/DrawEngineCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/D3D11/GPU_D3D11.h
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  GPU/Directx9/DrawEngineDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/Directx9/GPU_DX9.h
  GPU/Directx9/ShaderManagerDX9.h
  GPU/Directx9/TextureCacheDX9.cpp
  GPU/Directx9/TextureCacheDX9.h
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/GPU_GLES.h
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/GPUInterface.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/SoftGpu.h
  GPU/Software/TransformUnit.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  GPU/Vulkan/GPU_Vulkan.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.h
  GPU/Vulkan/VulkanUtil.cpp
  GPU/Vulkan/VulkanUtil.h
  UI/NativeApp.cpp
  libretro/LibretroGraphicsContext.cpp
Labels: Code Cleanup

#17012 (UWP) Small Build Overhaul
  UWP/UWP.vcxproj
  UWP/UWP.vcxproj.filters
Labels: Platform-specific (UWP)

#17017 D3D11: Correct equal clear check
  GPU/D3D11/DrawEngineD3D11.cpp
Labels: D3D11

#17011 Resurrect the Vulkan memory visualizer, but now it's global stats and pushbuffer stats.
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanMemory.cpp
  Common/GPU/Vulkan/VulkanMemory.h
  GPU/Vulkan/DebugVisVulkan.cpp
  UI/DevScreens.cpp
Labels: Vulkan, Debugger

#17022 Android: Make font rendering work even absent support for R4G4B4A4 textures
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Render/Text/draw_text_android.cpp
  Common/Render/Text/draw_text_android.h
  GPU/Common/FramebufferManagerCommon.cpp
Labels: Platform-specific (Android)

#17023 (UWP) Fix Skipped Asset Files
  UWP/UWP.vcxproj
Labels: Debugger

#17020 Rotate Daxter analog stick input
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/HLE/sceCtrl.cpp
  assets/compat.ini
Labels: Input/Controller

#17024 Update PPSSPP-Info.plist
  ios/PPSSPP-Info.plist
Labels: Platform-specific (iOS)

#17026 UI: Forget jit override on user selection
  Core/Config.cpp
  Core/Config.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/VertexDecoderCommon.cpp
  UI/GameSettingsScreen.cpp
  unittest/TestVertexJit.cpp
Labels: Code Cleanup
