Repository hrydgard/ppsspp, pull requests merged in 2024-01, with the labels that each got.

#18668 GPS: Set valid values and request updates on savestate loading
  Core/HLE/sceUsbGps.cpp
Labels: Savestate

#18669 GPS: updates
  Core/HLE/sceUsbGps.cpp
  android/src/org/ppsspp/ppsspp/LocationHelper.java
Labels: Platform-specific (Android)

#18678 Vulkan: Fix trying to compare uninitialized parts of packed descriptors
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/Render/ManagedTexture.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: Vulkan

#18653 Use the Tokimeki / old Juiced 2 method for Breath of Fire III
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  assets/compat.ini
Labels: Code Cleanup

#18683 Handle file type detection of extracted ISO directories better
  Core/FileLoaders/HTTPFileLoader.cpp
  Core/FileSystems/BlockDevices.cpp
  UI/GameInfoCache.cpp
Labels: User Interface

#18670 Fix compilation against newer ffmpeg versions
  Core/AVIDump.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceMpeg.cpp
  Core/HW/MediaEngine.cpp
  Core/HW/SimpleAudioDec.cpp
  Core/HW/SimpleAudioDec.h
Labels: PSMF / MPEG

#18696 Show a notification if a game exits with sceKernelExitGame.
  Common/System/OSD.cpp
  Common/System/OSD.h
  Core/Core.cpp
  Core/Core.h
  Core/HLE/sceKernel.cpp
Labels: User Interface

#18699 Adrenotools driver installation: Fix bad error checks
  Common/Data/Format/JSONReader.h
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/GPU/Vulkan/VulkanLoader.h
  Common/System/Request.h
  Qt/QtMain.cpp
  SDL/SDLVulkanGraphicsContext.cpp
  UI/GameSettingsScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/GPU/WindowsVulkanContext.cpp
  Windows/main.cpp
  android/jni/AndroidVulkanContext.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  libretro/LibretroVulkanContext.cpp
Labels: Platform-specific (Android), Vulkan, Adreno GPU

#18701 More beta crash fixes
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/thin3d.h
  Common/Thread/ThreadManager.h
  Core/FrameTiming.cpp
  Core/HLE/sceIo.cpp
  Core/Util/GameDB.cpp
  Core/Util/GameDB.h
  UI/NativeApp.cpp
Labels: Vulkan

#18704 Revert back to the old way of fitting into 16:9: Crop one line at the top and bottom
  Core/Config.cpp
  Core/Config.h
  GPU/Common/PresentationCommon.cpp
Labels: GE emulation, User Interface

#18706 Remove a bunch of dead code from CoreTiming ("threadsafe" events)
  Common/Serialize/SerializeList.h
  Core/CoreTiming.cpp
  Core/CoreTiming.h
  Core/HLE/sceUmd.cpp
  Core/MIPS/JitCommon/JitBlockCache.cpp
Labels: Code Cleanup

#18711 Don't crash after mapping analog speed to a stick.
  Core/KeyMap.cpp
  UI/GameSettingsScreen.cpp
Labels: Input/Controller, User Interface

#18716 New Vulkan validation fixes
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanFrameData.h
  Common/GPU/Vulkan/VulkanFramebuffer.h
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
Labels: Vulkan

#18717 Fix some gradle deprecation warnings
  android/AndroidManifest.xml
  android/build.gradle
  gradle.properties
Labels: Platform-specific (Android)

#18718 Android: Fix running plain PRXs on scoped storage. Minor cleanup.
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/PSPLoaders.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Platform-specific (Android)

#18723 Fix a particular type of race condition in file dialog requests
  Common/System/Request.cpp
  Common/System/Request.h
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Core/Dialog/PSPOskDialog.cpp
  UI/ChatScreen.cpp
  UI/ChatScreen.h
  UI/CwCheatScreen.cpp
  UI/DriverManagerScreen.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MainScreen.h
  UI/MemStickScreen.cpp
  UI/RemoteISOScreen.cpp
  UI/RetroAchievementScreens.cpp
  UI/SavedataScreen.cpp
  UI/TabbedDialogScreen.cpp
  Windows/MainWindowMenu.cpp
  Windows/MainWindowMenu.h
  headless/Headless.cpp
  libretro/libretro.cpp
Labels: User Interface

#18724 Windows: Add "Restart Graphics" to the debug menu.
  Common/System/System.h
  Core/Core.h
  GPU/Common/TextureReplacer.cpp
  SDL/CocoaBarItems.mm
  UI/NativeApp.cpp
  Windows/MainWindowMenu.cpp
  Windows/ppsspp.rc
  Windows/resource.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: GE emulation, User Interface

#18728 Remove allocation on translation key lookup
  Common/Data/Text/I18n.cpp
  Common/Data/Text/I18n.h
Labels: User Interface

#18732 SDL fonts: Add "Droid Sans Fallback" to the list of fallback fonts.
  Common/Render/Text/draw_text_sdl.cpp
Labels: SDL2, Platform-specific (Linux/POSIX)

#18734 SDL fallback fonts: Add more font names
  Common/Render/Text/draw_text_sdl.cpp
  Common/Render/Text/draw_text_sdl.h
  SDL/SDLMain.cpp
  UI/GameSettingsScreen.h
Labels: SDL2, User Interface

#18736 CwCheats: Retry looking in g_gameInfoCache until the data is there.
  UI/CwCheatScreen.cpp
  UI/CwCheatScreen.h
  UI/GameSettingsScreen.cpp
Labels: Cheats

#18737 Warn that extracted ISOs might not work
  Common/System/OSD.h
  Core/ConfigValues.h
  Core/HLE/sceDisplay.cpp
  Tools/langtool/src/main.rs
  UI/EmuScreen.cpp
  UI/GameInfoCache.cpp
  UI/OnScreenDisplay.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18738 More cleanup and fixes
  Common/System/Request.cpp
  Core/Core.cpp
  Core/Core.h
  Core/HLE/proAdhoc.cpp
  UI/DriverManagerScreen.cpp
  UI/MemStickScreen.cpp
  UI/PauseScreen.cpp
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Code Cleanup

#18741 Fix another game-shutdown race condition
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  GPU/Vulkan/GPU_Vulkan.cpp
Labels: Vulkan

#18740 Store improvements
  Common/File/AndroidStorage.h
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Core/Util/GameManager.cpp
  UI/GameInfoCache.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/NativeApp.cpp
  UI/Store.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Platform-specific (Android)

#18742 Preparations for reworking the memstick folder move functionality
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Util/MemStick.cpp
  Core/Util/MemStick.h
  GPU/Common/TextureReplacer.cpp
  UI/MemStickScreen.cpp
  UI/MemStickScreen.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#18744 Memstick folder move on Android: Speedup and safety
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Core/Util/GameManager.cpp
  Core/Util/MemStick.cpp
  Core/Util/MemStick.h
  GPU/Common/TextureReplacer.cpp
  UI/MemStickScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Platform-specific (Android)

#18747 Texture saving fixes, icon load fix
  Core/ELF/ParamSFO.cpp
  Core/ELF/ParamSFO.h
  Core/PSPLoaders.cpp
  Core/SaveState.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  GPU/Vulkan/TextureCacheVulkan.cpp
  UI/CwCheatScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameScreen.cpp
Labels: Texture replacement

#18743 Change when we call rc_client_do_frame to something that matches libretro
  Core/HLE/sceDisplay.cpp
  UI/EmuScreen.cpp
Labels: RetroAchievements

#18749 HTTPClient: Fix socket leak on connect failure
  Common/Net/HTTPClient.cpp
Labels: Networking / adhoc

#18750 More minor fixes
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  UI/MainScreen.cpp
  UI/RemoteISOScreen.cpp
Labels: GE emulation

#18752 Translation keys etc: Address feedback
  Common/Data/Text/I18n.cpp
  Tools/langtool/src/main.rs
  Tools/langtool/src/section.rs
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#18757 More asserts, move play button on pause screen
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Core/FileLoaders/HTTPFileLoader.cpp
  Core/FileLoaders/HTTPFileLoader.h
  GPU/Vulkan/GPU_Vulkan.cpp
  UI/PauseScreen.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: Platform-specific (Android)

#18760 Cleanup read-file-to-string functions
  Common/ArmCPUDetect.cpp
  Common/CPUDetect.cpp
  Common/Data/Format/IniFile.cpp
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Common/LoongArchCPUDetect.cpp
  Common/MipsCPUDetect.cpp
  Common/RiscVCPUDetect.cpp
  Core/Reporting.cpp
  UI/CwCheatScreen.cpp
  UI/DriverManagerScreen.cpp
  UI/GameInfoCache.cpp
  UI/NativeApp.cpp
  android/jni/TestRunner.cpp
  headless/Compare.cpp
Labels: Code Cleanup

#18762 Folder browser (like when clicking Browse...): Preinitialize with the current folder.
  Common/System/Request.cpp
  Common/System/Request.h
  Common/UI/PopupScreens.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MemStickScreen.cpp
  Windows/MainWindowMenu.cpp
  Windows/W32Util/ShellUtil.cpp
  Windows/W32Util/ShellUtil.h
  Windows/main.cpp
Labels: User Interface

#18766 Mark Dynarec/JIT as the recommended option in developer settings
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18772 Add volume slider for RetroAchievements sound effects
  Core/Config.cpp
  Core/Config.h
  UI/BackgroundAudio.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/RetroAchievementScreens.cpp
Labels: User Interface, RetroAchievements

#18775 GameInfoCache: Keep properly track of what's already loaded, lots of cleanup
  Common/Common.h
  UI/BackgroundAudio.cpp
  UI/CwCheatScreen.cpp
  UI/EmuScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/GameScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/MiscScreens.cpp
  UI/PauseScreen.cpp
  UI/SavedataScreen.cpp
  android/jni/app-android.cpp
Labels: Code Cleanup

#18776 More translation fixes
  UI/DebugOverlay.cpp
  UI/DevScreens.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#18777 Expand primitives: Check the vertex count too.
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GPUCommonHW.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#18779 More fixes
  Common/File/PathBrowser.cpp
  Common/File/VFS/VFS.cpp
  Common/File/VFS/ZipFileReader.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/Render/Text/draw_text_sdl.cpp
  Common/Thread/ThreadManager.cpp
  Core/FrameTiming.cpp
  Core/HLE/scePsmf.cpp
  Core/Reporting.cpp
  GPU/GPUCommonHW.cpp
  UI/BackgroundAudio.cpp
  UI/DevScreens.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/NativeApp.cpp
  UI/SavedataScreen.cpp
  android/jni/OpenSLContext.cpp
  android/jni/app-android.cpp
  assets/lang/sv_SE.ini
Labels: Code Cleanup

#18781 Disable 16-bit textures on PowerVR with Vulkan
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.cpp
  Common/GPU/thin3d.h
  Core/Debugger/MemBlockInfo.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  android/build.gradle
Labels: PowerVR GPU, GE emulation

#18785 Fix issue with the collapsible sections in control mapping collapsing on every change, plus, combo fix
  Common/UI/View.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  Core/Config.cpp
  Core/Config.h
  Core/ControlMapper.cpp
  UI/ControlMappingScreen.cpp
  UI/ControlMappingScreen.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#18786 Release all keys on pause.
  Core/ControlMapper.cpp
  Core/ControlMapper.h
  UI/EmuScreen.cpp
Labels: Input/Controller

#18800 Even more checks and fixes
  Common/Data/Collections/FastVec.h
  Common/GPU/OpenGL/GLMemory.cpp
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/UI/ScrollView.cpp
  Common/UI/View.cpp
  Core/FileSystems/BlockDevices.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceCtrl.cpp
  Core/HW/SasAudio.h
  Core/Util/PPGeDraw.cpp
  UI/GameInfoCache.cpp
  UI/MiscScreens.cpp
  android/src/org/ppsspp/ppsspp/MogaHack.java
Labels: Platform-specific (Android), User Interface

#18803 Warn the user about bad CHDs
  Common/System/OSD.h
  Core/FileSystems/BlockDevices.cpp
  Core/FileSystems/BlockDevices.h
  Core/Reporting.cpp
  README.md
  UI/EmuScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/GameScreen.cpp
  UI/OnScreenDisplay.cpp
  UI/OnScreenDisplay.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface
