Repository hrydgard/ppsspp, pull requests merged in 2024-05, with the labels that each got.

#19102 atrac3: Add a cross platform restrict modifier, use it for the vector math functions
  ext/at3_standalone/atrac3.cpp
  ext/at3_standalone/atrac3plusdsp.cpp
  ext/at3_standalone/compat.h
  ext/at3_standalone/float_dsp.h
Labels: Code Cleanup

#19103 optimize Memory::IsValidNullTerminatedString
  Core/MemMap.h
Labels: Code Cleanup

#19104 Add ability to limit PathBrowser to a specific root folder
  Common/File/Path.cpp
  Common/File/PathBrowser.cpp
  Common/File/PathBrowser.h
  Common/System/System.h
  Core/Config.cpp
  Core/KeyMapDefaults.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/RemoteISOScreen.cpp
  Windows/main.cpp
  ios/main.mm
Labels: User Interface, Code Cleanup

#19106 Make a simpler CMakeLists.txt for zstd
  CMakeLists.txt
  Core/HLE/sceKernelInterrupt.cpp
  ext/zstd-build/CMakeLists.txt
Labels: Code Cleanup

#19109 Assorted cleanup
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Common/StringUtils.cpp
  Common/StringUtils.h
  Core/Dialog/SavedataParam.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelModule.cpp
  Core/MemMap.h
Labels: Code Cleanup

#19121 Fix Digimon audio along with some minor issues
  Core/HLE/sceAtrac.cpp
  Core/MemMap.h
  GPU/GPUCommon.cpp
  Tools/langtool/Cargo.lock
  Windows/MainWindow.cpp
  libretro/libretro.cpp
  libretro/libretro_core_options.h
Labels: Atrac3+

#19122 More minor fixes
  GPU/Common/TextureCacheCommon.cpp
  UI/GameInfoCache.cpp
Labels: GE emulation, User Interface

#19124 Minor IR interpreter optimizations
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRJit.h
  Core/MIPS/MIPSIntVFPU.cpp
Labels: IRInterpreter

#19126 Allow taking screenshots in the app menu
  Core/SaveState.cpp
  Core/Screenshot.cpp
  Core/Screenshot.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  UI/NativeApp.cpp
  UI/ReportScreen.cpp
  Windows/MainWindowMenu.cpp
Labels: User Interface

#19127 OpenXR - Projection matrix (camera issue) fixed
  Common/VR/PPSSPPVR.cpp
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
  assets/compatvr.ini
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: VR

#19128 More IR interpreter optimizations
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRInterpreter.h
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MemMap.h
Labels: IRInterpreter

#19130 Fixes and optimizations for the optimized vertex decoders
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexDecoderHandwritten.cpp
  UI/DevScreens.cpp
Labels: GE emulation

#19135 [Net/Web/Util] Fixed strict reduce types to 32 bit sizes, changed to memsize
  Common/Net/HTTPServer.cpp
  Common/Net/NetBuffer.cpp
  Common/Net/Sinks.cpp
  Core/Util/MemStick.cpp
  Core/WebServer.cpp
Labels: Code Cleanup

#19136 Add basic checkbox UI for GPI switches, add display of GPO LEDs
  Common/UI/View.cpp
  Common/UI/View.h
  Core/Config.cpp
  Core/Config.h
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  Tools/langtool/Cargo.lock
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: HLE/Kernel, User Interface

#19138 Windows: When using "Create shortcut", use the game's icon instead of PPSSPP's
  Windows/W32Util/ShellUtil.cpp
  Windows/W32Util/ShellUtil.h
  Windows/main.cpp
Labels: Platform-specific (Windows)

#19139 Android: Upgrade SDK and target versions, implement shortcut icons
  android/build.gradle
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/ShortcutActivity.java
Labels: Platform-specific (Android)

#19142 Android: Fix issue where shortcuts wouldn't override the currently running game.
  UI/EmuScreen.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
Labels: Platform-specific (Android)

#19153 libretro: Add more options for locked cpu speed
  libretro/libretro_core_options.h
Labels: Libretro

#19155 Add ku_SO translation (contributed by M. Omer)
  assets/lang/ku_SO.ini
  assets/langregion.ini
Labels: Translation

#19156 iOS build changes for app store
  CMakeLists.txt
  Common/File/PathBrowser.cpp
  Common/File/PathBrowser.h
  Core/Config.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhocServer.cpp
  Qt/macbundle.sh
  SDL/SDLMain.cpp
  SDL/macbundle.sh
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  b-appstore.sh
  cmake/Toolchains/ios.cmake
  ext/at3_standalone/CMakeLists.txt
  ext/minimp3/CMakeLists.txt
  ext/native/tools/CMakeLists.txt
  ios/Export.plist
  ios/PPSSPP-AppStore.plist
  ios/PPSSPP-AppStoreGold.plist
  ios/PPSSPPUIApplication.mm
  ios/assets.xcassets/AppIcon.appiconset/Contents.json
  ios/assets.xcassets/AppIcon.appiconset/icon_backfill_1024.png
  ios/assets.xcassets/AppIconGold.appiconset/Contents.json
  ios/assets.xcassets/AppIconGold.appiconset/icon_gold_backfill_1024.png
  ios/assets.xcassets/Contents.json
  ios/assets/IconGold-72.png
  ios/assets/IconGold-72@2x.png
  ios/assets/IconGold-72@3x.png
  ios/assets/IconGold.png
  ios/assets/IconGold@2x.png
  ios/assets/IconGold@3x.png
  ios/iosbundle.sh
  ios/macbundle.sh
  ios/main.mm
  ios/version-transform.pl
Labels: Platform-specific (iOS)

#19157 Workaround for blurry text when high contrast text is enabled in Android Accessibility
  android/src/org/ppsspp/ppsspp/TextRenderer.java
Labels: Platform-specific (Android)

#19160 Change UI event notifications (used for soft-keyboard in UWP mode) from strings to enums
  Common/System/Request.h
  Common/System/System.h
  Common/UI/UIScreen.cpp
  Common/UI/View.cpp
  UWP/PPSSPP_UWPMain.cpp
Labels: Platform-specific (UWP), Code Cleanup

#19161 Add basic soft-keyboard support on iOS
  Common/System/System.h
  Common/UI/PopupScreens.cpp
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  UI/GameSettingsScreen.cpp
  UI/RetroAchievementScreens.cpp
  ios/ViewController.h
  ios/ViewController.mm
  ios/main.mm
Labels: Platform-specific (iOS), User Interface

#19165 UI crash fix in control mapping screen
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  UI/ControlMappingScreen.cpp
Labels: User Interface

#19168 iOS ViewController refactor
  ios/AppDelegate.h
  ios/AppDelegate.mm
  ios/DisplayManager.mm
  ios/ViewController.h
  ios/ViewController.mm
  ios/main.mm
Labels: Platform-specific (iOS), Code Cleanup

#19170 iOS: More ViewController code refactor
  CMakeLists.txt
  ios/Controls.h
  ios/Controls.mm
  ios/DisplayManager.mm
  ios/ViewController.h
  ios/ViewController.mm
  ios/iOSCoreAudio.mm
  ios/main.mm
Labels: Platform-specific (iOS), Code Cleanup

#19171 iOS: Even more viewcontroller refactor
  CMakeLists.txt
  ios/CameraHelper.h
  ios/CameraHelper.mm
  ios/ViewController.h
  ios/ViewController.mm
  ios/ViewControllerCommon.h
  ios/main.mm
Labels: Platform-specific (iOS), Vulkan, Code Cleanup

#19173 IRInterpreter compiler: Reject all vec2ops where the prefix is unknown while compiling
  Core/HLE/sceKernelInterrupt.cpp
  Core/MIPS/IR/IRCompVFPU.cpp
Labels: IRInterpreter

#19175 Add a convenience method to VulkanContext to reduce code duplication
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Core/Util/VulkanEmuThread.cpp
  android/jni/AndroidVulkanContext.cpp
Labels: Code Cleanup

#19178 Text draw refactor part #1
  Common/Data/Text/WrapText.cpp
  Common/Data/Text/WrapText.h
  Common/Render/DrawBuffer.cpp
  Common/Render/DrawBuffer.h
  Common/Render/Text/draw_text.cpp
  Common/Render/Text/draw_text.h
  Common/UI/Context.cpp
  Common/UI/Context.h
  Common/UI/PopupScreens.cpp
  Common/UI/View.cpp
  Common/UI/View.h
  unittest/UnitTest.cpp
Labels: Code Cleanup

#19179 Text draw refactor part #2
  Common/File/VFS/VFS.cpp
  Common/Render/Text/draw_text.cpp
  Common/Render/Text/draw_text.h
  Common/Render/Text/draw_text_android.cpp
  Common/Render/Text/draw_text_android.h
  Common/Render/Text/draw_text_qt.cpp
  Common/Render/Text/draw_text_qt.h
  Common/Render/Text/draw_text_sdl.cpp
  Common/Render/Text/draw_text_sdl.h
  Common/Render/Text/draw_text_uwp.cpp
  Common/Render/Text/draw_text_uwp.h
  Common/Render/Text/draw_text_win.cpp
  Common/Render/Text/draw_text_win.h
  Common/StringUtils.h
  Common/UI/AsyncImageFileView.cpp
  Common/UI/Context.cpp
  Common/UI/Context.h
  Common/UI/PopupScreens.cpp
  Common/UI/View.cpp
  Core/Util/PPGeDraw.cpp
  UI/GPUDriverTestScreen.cpp
  UI/JoystickHistoryView.cpp
  UI/MainScreen.cpp
  UI/OnScreenDisplay.cpp
  UI/RetroAchievementScreens.cpp
Labels: Code Cleanup

#19189 IRInterpreter: Fix issue where we could accidentally optimize out CallReplacement ops.
  Core/HLE/ReplaceTables.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
Labels: IRInterpreter

#19187 iOS: Fix issue with keyboard popping up after file picker.
  Common/System/System.h
  Core/System.cpp
  UI/DarwinFileSystemServices.mm
  UI/GamepadEmu.cpp
  ios/ViewController.mm
  ios/ViewControllerCommon.h
  ios/ViewControllerMetal.mm
  ios/main.mm
Labels: Platform-specific (iOS)

#19191 More iOS polish: Improved gamepad mappings, enable ARC for all the files
  CMakeLists.txt
  Core/KeyMap.cpp
  Core/KeyMapDefaults.cpp
  Core/KeyMapDefaults.h
  ios/AppDelegate.mm
  ios/Controls.mm
  ios/ViewControllerMetal.mm
Labels: Platform-specific (iOS), Input/Controller

#19193 IRInterpreter: Enable some optimizations that accidentally were only enabled on non-ARM64.
  Core/MIPS/ARM64/Arm64IRJit.cpp
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRJit.h
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/JitCommon/JitBlockCache.h
  Core/MIPS/JitCommon/JitState.h
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/x86/X64IRJit.cpp
  UI/DevScreens.cpp
Labels: IRInterpreter

#19200 iOS: Add audio session mode controls
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/System/System.h
  Core/Config.cpp
  Core/Config.h
  UI/GameSettingsScreen.cpp
  ios/DisplayManager.mm
  ios/iOSCoreAudio.h
  ios/iOSCoreAudio.mm
  ios/main.mm
Labels: Platform-specific (iOS)

#19201 Add translation strings for new iOS audio options
  Tools/langtool/Cargo.lock
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Translation

#19203 libretro: context cleanup
  libretro/LibretroGLContext.cpp
  libretro/LibretroGLCoreContext.cpp
  libretro/LibretroGraphicsContext.cpp
  libretro/LibretroVulkanContext.cpp
  libretro/LibretroVulkanContext.h
Labels: Libretro

#19206 More libretro maintenance
  libretro/Makefile
  libretro/Makefile.common
  libretro/libretro.cpp
  libretro/libretro_core_options.h
Labels: Libretro

#19207 SDL: Switch to SDL_WaitEventTimeout instead of SDL_PollEvent when possible.
  SDL/SDLMain.cpp
Labels: SDL2

#19213 iOS: Prevent the Recents list from disappearing a lot
  Common/File/FileUtil.cpp
  Common/GPU/Vulkan/VulkanLoader.cpp
  Core/Config.cpp
  ios/ViewController.mm
  ios/ViewControllerMetal.mm
Labels: Platform-specific (iOS), User Interface

#19214 Fix some Vulkan-related bugs
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/Vulkan/VulkanRenderManager.h
  Core/Config.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  Windows/MainWindow.cpp
  Windows/ppsspp.rc
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Vulkan

#19215 iOS: Fix hang when task switching in GL mode
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/GLRenderManager.h
  UI/GameSettingsScreen.cpp
  ios/ViewController.mm
Labels: Platform-specific (iOS)

#19219 draw_text: Unify DrawString between all platforms
  Common/Render/Text/draw_text.cpp
  Common/Render/Text/draw_text.h
  Common/Render/Text/draw_text_android.cpp
  Common/Render/Text/draw_text_android.h
  Common/Render/Text/draw_text_cocoa.h
  Common/Render/Text/draw_text_cocoa.mm
  Common/Render/Text/draw_text_qt.cpp
  Common/Render/Text/draw_text_qt.h
  Common/Render/Text/draw_text_sdl.cpp
  Common/Render/Text/draw_text_sdl.h
  Common/Render/Text/draw_text_uwp.cpp
  Common/Render/Text/draw_text_uwp.h
  Common/Render/Text/draw_text_win.cpp
  Common/Render/Text/draw_text_win.h
  Core/Util/PPGeDraw.cpp
Labels: User Interface, Code Cleanup

#19221 Rewrite GetFriendlyPath
  Common/File/PathBrowser.cpp
  UI/MainScreen.cpp
Labels: User Interface

#19222 More text rendering code cleanup
  CMakeLists.txt
  Common/Render/DrawBuffer.cpp
  Common/Render/DrawBuffer.h
  Common/Render/Text/draw_text.cpp
  Common/Render/Text/draw_text.h
  Common/Render/Text/draw_text_android.cpp
  Common/Render/Text/draw_text_android.h
  Common/Render/Text/draw_text_cocoa.h
  Common/Render/Text/draw_text_cocoa.mm
  Common/Render/Text/draw_text_qt.cpp
  Common/Render/Text/draw_text_qt.h
  Common/Render/Text/draw_text_sdl.cpp
  Common/Render/Text/draw_text_sdl.h
  Common/Render/Text/draw_text_uwp.cpp
  Common/Render/Text/draw_text_uwp.h
  Common/Render/Text/draw_text_win.cpp
  Common/Render/Text/draw_text_win.h
  UI/DevScreens.cpp
Labels: Code Cleanup
