Repository hrydgard/ppsspp, pull requests merged in 2024-07, with the labels that each got.

#19316 Updated Polish translation & fixed strings not being translated properly
  UI/GameScreen.cpp
  Windows/MainWindowMenu.cpp
  Windows/ppsspp.rc
  assets/lang/pl_PL.ini
Labels: Translation

#19314 Add setting to control the iOS app switching mode
  Common/System/System.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  ios/ViewController.mm
  ios/ViewControllerCommon.h
  ios/ViewControllerMetal.mm
  ios/main.mm
Labels: Platform-specific (iOS)

#19326 OpenXR - Add FBO supersampling
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRRenderer.cpp
  Common/VR/VRRenderer.h
Labels: VR

#19327 allow binding custom right stick to analog
  Core/HLE/sceCtrl.cpp
  Core/HLE/sceCtrl.h
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
  UI/TouchControlVisibilityScreen.cpp
Labels: Input/Controller

#19331 Vulkan: Use VK_EXT_provoking_vertex, when available, to get OpenGL/PSP behavior for flat shading
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanLoader.h
  Common/GPU/Vulkan/VulkanQueueRunner.h
  Common/GPU/Vulkan/VulkanRenderManager.h
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/VR/VRRenderer.cpp
  GPU/Common/FragmentShaderGenerator.cpp
  GPU/Common/FragmentShaderGenerator.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.cpp
  GPU/Vulkan/PipelineManagerVulkan.h
  SDL/SDLVulkanGraphicsContext.cpp
  UI/GPUDriverTestScreen.cpp
  Windows/GPU/WindowsVulkanContext.cpp
  libretro/LibretroVulkanContext.cpp
Labels: Vulkan

#19334 Improved provoking vertex fix
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/IndexGenerator.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/D3D11/D3D11Util.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#19304 Allow "Alt" to act like a normal keyboard input, if it's been mapped to something
  Windows/MainWindow.cpp
Labels: Platform-specific (Windows)

#19338 ARM32: Remove runtime checks for VFPv3 and NEON
  Common/ArmEmitter.cpp
  Core/MIPS/IR/IRJit.cpp
Labels: Code Cleanup

#19337 Add ifdefs to try to be compatible with old SDL versions
  SDL/SDLJoystick.cpp
Labels: SDL2

#19340 sceIoGetStat: Fix retrieving timestamps from directories
  .vscode/launch.json
  .vscode/tasks.json
  Core/FileSystems/DirectoryFileSystem.cpp
Labels: I/O

#19341 Add a clickable notification if "Dump decrypted EBOOT" is enabled
  Core/HLE/sceKernelModule.cpp
Labels: User Interface

#19343 RetroAchievements leaderboard: Show new rank, or personal best, after submission
  Core/RetroAchievements.cpp
  UI/RetroAchievementScreens.cpp
Labels: RetroAchievements

#19345 Minor validation fix in Vulkan init, cosmetic UI tweak
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanFrameData.cpp
  Common/GPU/Vulkan/VulkanFramebuffer.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/UI/PopupScreens.cpp
  Common/UI/View.cpp
  Common/UI/View.h
  GPU/Vulkan/PipelineManagerVulkan.cpp
  UI/DisplayLayoutScreen.cpp
  UI/GameSettingsScreen.cpp
Labels: User Interface, Code Cleanup

#19348 Implement compat flag proposed in #18423, forcing readbacks in Juiced 2
  Core/Compatibility.cpp
  Core/Compatibility.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  UI/EmuScreen.cpp
Labels: GPU readback

#19347 sceFont and savestate fixes
  Common/Render/ManagedTexture.cpp
  Common/Serialize/Serializer.cpp
  Common/Serialize/Serializer.h
  Core/HLE/sceFont.cpp
  Core/HW/SimpleAudioDec.cpp
  Core/SaveState.cpp
  Core/System.cpp
  Core/Util/GameManager.cpp
Labels: Savestate

#19354 Console logging code cleanup
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Log/ConsoleListener.cpp
  Common/Log/ConsoleListener.h
  Common/Log/LogManager.cpp
  Common/Log/LogManager.h
  Common/Log/StdioListener.cpp
  Common/Log/StdioListener.h
  Common/LogReporting.cpp
  Core/Config.cpp
  Core/Debugger/WebSocket/LogBroadcaster.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernelThread.cpp
  Core/System.cpp
  Qt/mainwindow.cpp
  Qt/mainwindow.h
  UI/DevScreens.cpp
  UI/GPUDriverTestScreen.h
  UI/NativeApp.cpp
  UI/Theme.cpp
  UWP/App.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/PPSSPP_UWPMain.cpp
  Windows/Debugger/Debugger_MemoryDlg.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
  android/jni/Android.mk
  android/jni/app-android.h
  headless/Headless.cpp
  libretro/Makefile.common
  libretro/libretro.cpp
Labels: Code Cleanup

#19355 Console log listener code cleanup
  Common/Log/ConsoleListener.cpp
  Common/Log/ConsoleListener.h
  Common/Log/LogManager.cpp
Labels: Code Cleanup

#19356 IR jit/interpreter code cleanup
  Core/MIPS/ARM64/Arm64IRJit.cpp
  Core/MIPS/IR/IRInst.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRJit.h
  Core/MIPS/IR/IRNativeCommon.cpp
  Core/MIPS/IR/IRNativeCommon.h
  Core/MIPS/IR/IRRegCache.cpp
  Core/MIPS/RiscV/RiscVJit.cpp
  Core/MIPS/x86/X64IRJit.cpp
Labels: Code Cleanup

#19357 Disable preloading of function stubs if bPreloadFunctions is off
  Core/HLE/sceKernelModule.cpp
  Core/MIPS/IR/IRJit.cpp
Labels: IRInterpreter

#19360 IR: Disable unworkable overwriting of instructions on invalidation.
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/IR/IRJit.h
Labels: IRInterpreter

#19361 OpenXR - Anti-flickering rendering flow added
  Common/VR/PPSSPPVR.cpp
  Common/VR/VRRenderer.cpp
  Common/VR/VRRenderer.h
  Core/Config.cpp
  Core/Config.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: VR

#19363 VertexDecoder: Remove member function pointers from decoding
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexDecoderCommon.h
Labels: GE emulation

#19366 Misc logging tweaks
  CMakeLists.txt
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceIo.cpp
  Core/HW/MpegDemux.cpp
  SDL/README.TXT
  b.sh
Labels: Code Cleanup

#19367 Fix minor difference between ubershader and specialized vshaders
  GPU/Common/ShaderUniforms.cpp
  GPU/Common/VertexShaderGenerator.cpp
Labels: GE emulation

#19369 Minor cleanups, add new more precise "sleep" function for Windows
  Common/Common.vcxproj.filters
  Common/LogReporting.h
  Common/TimeUtil.cpp
  Common/TimeUtil.h
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhoc.h
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceMt19937.cpp
  Core/HLE/sceNet.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/Loaders.cpp
  Core/Loaders.h
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/IR/IRJit.cpp
  Core/MIPS/MIPS.cpp
  Core/MIPS/MIPS.h
  Core/MemMap.h
  Core/PSPLoaders.cpp
  GPU/Common/ReinterpretFramebuffer.h
  GPU/Common/TextureDecoder.h
  GPU/Common/TextureShaderCommon.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/EmuScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/app-android.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
  unittest/UnitTest.cpp
Labels: Code Cleanup

#19375 Replace call of SetWaitableTimerEx with SetWaitableTimer
  Common/TimeUtil.cpp
Labels: Platform-specific (Windows)
