Repository hrydgard/ppsspp, pull requests merged in 2024-11, with the labels that each got.

#19574 A few misc fixes (Bust-a-move video, scaling issue in touch layout editor)
  Core/Config.cpp
  Core/Config.h
  UI/DiscordIntegration.cpp
  UI/DiscordIntegration.h
  UI/GameSettingsScreen.cpp
  UI/TouchControlLayoutScreen.cpp
  assets/compat.ini
  libretro/libretro.cpp
Labels: User Interface

#19580 GCC/llvm: Enable a lot more warnings, error on missing return value
  CMakeLists.txt
  GPU/Common/PresentationCommon.cpp
  ios/main.mm
Labels: Code Cleanup

#19576 Move CPU stepping logic out of the disassembler window code
  Common/System/System.h
  Core/Core.cpp
  Core/Core.h
  Core/CoreTiming.cpp
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/MemorySubscriber.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  Core/HLE/HLE.cpp
  Core/MIPS/ARM64/Arm64IRCompSystem.cpp
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/MIPSInt.cpp
  Core/MIPS/MIPSTables.cpp
  Core/MIPS/RiscV/RiscVCompSystem.cpp
  Core/MIPS/x86/CompBranch.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  Core/RetroAchievements.cpp
  Core/SaveState.cpp
  SDL/CocoaBarItems.mm
  SDL/SDLMain.cpp
  UI/EmuScreen.cpp
  UI/GamepadEmu.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlDisAsmView.h
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/DebuggerShared.h
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/Debugger_Disasm.h
  Windows/Debugger/DumpMemoryWindow.cpp
  Windows/EmuThread.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
Labels: Debugger

#19569 ImGui integration prototype
  .gitignore
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/DbgNew.h
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/MiscTypes.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Common/Input/InputState.h
  Common/System/Display.cpp
  Common/System/Display.h
  Common/UI/View.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  Core/KeyMapDefaults.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/NativeApp.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  Windows/MainWindow.cpp
  android/jni/Android.mk
  ext/CMakeLists.txt
  ext/imgui/CMakeLists.txt
  ext/imgui/imconfig.h
  ext/imgui/imgui.cpp
  ext/imgui/imgui.h
  ext/imgui/imgui_demo.cpp
  ext/imgui/imgui_draw.cpp
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_impl_platform.h
  ext/imgui/imgui_impl_thin3d.cpp
  ext/imgui/imgui_impl_thin3d.h
  ext/imgui/imgui_internal.h
  ext/imgui/imgui_tables.cpp
  ext/imgui/imgui_widgets.cpp
  ext/imgui/imstb_rectpack.h
  ext/imgui/imstb_textedit.h
  ext/imgui/imstb_truetype.h
  libretro/Makefile.common
Labels: User Interface

#19588 ImGui: Fix resource management
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/UIScreen.cpp
  Common/UI/UIScreen.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/NativeApp.cpp
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_impl_thin3d.cpp
  ext/imgui/imgui_impl_thin3d.h
Labels: Debugger

#19589 Refactor execution: No longer freeze the "EmuThread" when paused in the debugger
  Core/Core.cpp
  Core/Core.h
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  Core/SaveState.cpp
  Core/System.cpp
  GPU/Debugger/Stepping.cpp
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/EmuThread.cpp
  libretro/libretro.cpp
Labels: Debugger

#19596 SDL mouse fix
  CMakeLists.txt
  Common/Render/Text/draw_text_win.cpp
  Core/Debugger/WebSocket/ClientConfigSubscriber.cpp
  SDL/SDLMain.cpp
  ext/imgui/imgui_impl_platform.cpp
Labels: User Interface

#19600 RAIntegration not-found error message fix
  Core/RetroAchievements.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: RetroAchievements

#19605 ImGui integretion: Implement mousewheel and mouse hover
  Common/Input/InputState.h
  Common/UI/View.cpp
  SDL/SDLMain.cpp
  UI/BackgroundAudio.h
  UI/DevScreens.cpp
  Windows/MainWindow.cpp
  Windows/RawInput.cpp
  ext/imgui/imgui_impl_platform.cpp
Labels: Debugger

#19608 Fix for error taking screenshots in Vulkan on many devices
  Common/GPU/Vulkan/VulkanContext.cpp
  Core/Screenshot.cpp
Labels: User Interface

#19609 ImGui debugger
  CMakeLists.txt
  Core/Debugger/DebugInterface.h
  Core/Debugger/SymbolMap.h
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Core/HLE/sceDisplay.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/MIPSDebugInterface.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlDisAsmView.h
  Windows/Debugger/CtrlRegisterList.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/EmuThread.cpp
  android/jni/Android.mk
  ext/imgui/imgui_impl_platform.cpp
Labels: Debugger

#19614 More minor ImGui fixes
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/MIPSStackWalk.cpp
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  ext/imgui/imgui_impl_platform.cpp
Labels: Debugger

#19628 Assorted debugger fixes
  Core/Config.cpp
  Core/Config.h
  Core/Core.cpp
  Core/Debugger/WebSocket/SteppingBroadcaster.cpp
  Core/PSPLoaders.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  Windows/MainWindow.cpp
  ext/imgui/imgui_impl_platform.cpp
Labels: Debugger

#19635 ImDebugger: Add some new minor things
  Core/HLE/AtracCtx.h
  Core/HLE/HLE.cpp
  Core/HLE/HLE.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  Core/MIPS/MIPSStackWalk.cpp
  Core/MemMap.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
Labels: Debugger

#19636 Throttle the display rate when stepping in the debugger.
  UI/EmuScreen.cpp
Labels: Debugger

#19629 Struct viewer debugging tool
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/GhidraClient.cpp
  Common/GhidraClient.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImStructViewer.cpp
  UI/ImDebugger/ImStructViewer.h
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Debugger

#19642 Add a "reason" argument to sleep_ms()
  Common/File/PathBrowser.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/Net/HTTPClient.cpp
  Common/Net/HTTPRequest.cpp
  Common/Net/HTTPRequest.h
  Common/Net/Resolve.cpp
  Common/TimeUtil.cpp
  Common/TimeUtil.h
  Core/Core.cpp
  Core/FileLoaders/CachingFileLoader.cpp
  Core/FileLoaders/RamCachingFileLoader.cpp
  Core/FrameTiming.cpp
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhocServer.cpp
  Core/HLE/sceDisplay.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/System.cpp
  Core/Util/PortManager.cpp
  UI/GameInfoCache.cpp
  UI/NativeApp.cpp
  UI/RemoteISOScreen.cpp
  android/jni/app-android.cpp
  headless/Headless.cpp
  headless/SDLHeadlessHost.cpp
  headless/WindowsHeadlessHost.cpp
  libretro/libretro.cpp
  unittest/TestThreadManager.cpp
Labels: Code Cleanup

#19644 Optimize "Buffer" with a new data structure
  CMakeLists.txt
  Common/Buffer.cpp
  Common/Buffer.h
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Collections/CharQueue.h
  Common/Data/Collections/Slice.h
  Common/Net/NetBuffer.cpp
  unittest/UnitTest.cpp
  unittest/UnitTest.h
Labels: Code Cleanup, Performance

#19645 Optimize Buffer slightly more, fix using touchscreen controls using the mouse
  Common/Buffer.cpp
  Common/Data/Collections/CharQueue.h
  Common/Net/NetBuffer.cpp
  UI/GamepadEmu.cpp
  unittest/UnitTest.cpp
Labels: Input/Controller

#19646 ImGui debugger: Add TTF font support
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  ext/imgui/imgui_impl_thin3d.cpp
  ext/imgui/imgui_impl_thin3d.h
Labels: Debugger

#19654 ImDebugger: Add Breakpoints window
  Core/Core.cpp
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/Breakpoints.h
  Core/Debugger/MemBlockInfo.cpp
  Core/Debugger/WebSocket/BreakpointSubscriber.cpp
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  Core/HLE/ReplaceTables.cpp
  Core/MIPS/ARM/ArmJit.cpp
  Core/MIPS/ARM64/Arm64IRCompSystem.cpp
  Core/MIPS/ARM64/Arm64Jit.cpp
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/MIPSTables.cpp
  Core/MIPS/fake/FakeJit.cpp
  Core/MIPS/x86/Jit.cpp
  Core/MIPS/x86/X64IRCompSystem.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  UI/ImDebugger/ImStructViewer.cpp
  Windows/Debugger/BreakpointWindow.cpp
  Windows/Debugger/BreakpointWindow.h
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/Debugger_Disasm.h
  Windows/Debugger/Debugger_Lists.cpp
  Windows/MainWindowMenu.cpp
Labels: Debugger

#19655 More ImDebugger stuff
  Common/System/Request.h
  Common/System/System.h
  Core/Core.cpp
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/Breakpoints.h
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/DirectoryFileSystem.h
  Core/FileSystems/MetaFileSystem.h
  Core/FileSystems/VirtualDiscFileSystem.cpp
  Core/FileSystems/VirtualDiscFileSystem.h
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  UWP/PPSSPP_UWPMain.cpp
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
Labels: Debugger

#19656 ImDebugger: Add a basic kernel object list
  Common/Input/KeyCodes.h
  Core/Core.cpp
  Core/FileSystems/BlobFileSystem.h
  Core/FileSystems/DirectoryFileSystem.h
  Core/FileSystems/FileSystem.h
  Core/FileSystems/ISOFileSystem.cpp
  Core/FileSystems/ISOFileSystem.h
  Core/FileSystems/MetaFileSystem.h
  Core/FileSystems/VirtualDiscFileSystem.h
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  Windows/RawInput.cpp
  ext/imgui/imgui_impl_platform.cpp
Labels: Debugger

#19657 ImDebugger: Basic framebuffer viewer
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/GLRenderManager.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  Core/Debugger/DebugInterface.h
  Core/HLE/sceKernel.cpp
  Core/MIPS/MIPSDebugInterface.h
  GPU/Common/FramebufferManagerCommon.cpp
  UI/ImDebugger/ImDebugger.cpp
  ext/imgui/imgui_impl_thin3d.cpp
  ext/imgui/imgui_impl_thin3d.h
Labels: Debugger

#19659 Android: Bump the gradle plugin version again
  build.gradle
Labels: Platform-specific (Android)

#19662 ImDebugger: Add the ability to draw using multiple pipelines
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/FramebufferManagerCommon.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  ext/imgui/imgui_impl_thin3d.cpp
  ext/imgui/imgui_impl_thin3d.h
Labels: Debugger

#19660 Fix toast warning in SDL build
  SDL/SDLMain.cpp
Labels: SDL2

#19663 ImDebugger: Add config saving, add new audio channels window
  Core/Config.cpp
  Core/HLE/sceAudiocodec.cpp
  Core/HLE/sceAudiocodec.h
  Core/HLE/sceMp3.cpp
  Core/HLE/sceMp3.h
  Core/HLE/sceMpeg.cpp
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_impl_platform.h
  gradle.properties
Labels: Debugger

#19664 Log "host" thread names when not on EmuThread
  Common/GPU/Vulkan/VulkanLoader.cpp
  Common/Log/LogManager.cpp
Labels: Debugger

#19666 Use a separate file for the "Failed GPU backends" on all platforms.
  Common/GhidraClient.h
  Core/Config.cpp
  Core/Config.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  UI/NativeApp.cpp
Labels: GE emulation

#19668 File system perf part 1: Remove some unnecessary file access
  Common/File/DirListing.cpp
  Common/File/FileUtil.cpp
  Common/File/VFS/VFS.h
  Common/Net/HTTPNaettRequest.h
  Core/Config.cpp
  Core/HW/SasAudio.cpp
  Core/MIPS/ARM64/Arm64IRCompFPU.cpp
  GPU/Common/TextureScalerCommon.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  UI/CwCheatScreen.h
  UI/GameSettingsScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/MainScreen.cpp
  UI/Theme.cpp
  UI/TiltAnalogSettingsScreen.h
  Windows/main.cpp
Labels: User Interface, Performance

#19670 [Libretro] Fix deadzone and sensitivity
  libretro/libretro.cpp
Labels: Libretro, Input/Controller

#19671 File system perf, part 2
  Common/File/AndroidStorage.cpp
  Common/File/AndroidStorage.h
  Common/File/DirListing.cpp
  Common/File/DirListing.h
  Common/File/PathBrowser.cpp
  UI/GameInfoCache.cpp
  UI/MainScreen.cpp
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
Labels: Performance

#19676 File system perf part 4, fix save deletion regression
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Common/Data/Text/I18n.cpp
  Common/File/AndroidStorage.cpp
  Common/File/DirListing.cpp
  Common/File/FileUtil.cpp
  Common/File/VFS/DirectoryReader.cpp
  Common/File/VFS/DirectoryReader.h
  Common/File/VFS/VFS.cpp
  Common/File/VFS/VFS.h
  Common/File/VFS/ZipFileReader.cpp
  Common/File/VFS/ZipFileReader.h
  Common/Log/LogManager.cpp
  Core/Config.cpp
  Core/Config.h
  Core/Dialog/SavedataParam.cpp
  Core/FileLoaders/LocalFileLoader.cpp
  Core/HLE/sceIo.cpp
  Core/SaveState.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  UI/GameInfoCache.cpp
  UI/GameScreen.cpp
  UI/GameScreen.h
  android/src/org/ppsspp/ppsspp/PpssppActivity.java
  unittest/UnitTest.cpp
Labels: Performance

#19679 File system perf 5, fix ini file regression
  Common/Data/Format/IniFile.cpp
  Common/File/VFS/ZipFileReader.cpp
  Core/Dialog/SavedataParam.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Common/TextureReplacer.h
  UI/ImDebugger/ImGe.cpp
Labels: Texture replacement
