Repository hrydgard/ppsspp, pull requests merged in 2024-12, with the labels that each got.

#19683 Add texture cache stats to ImDebugger
  GPU/Common/ReplacedTexture.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
Labels: Texture replacement

#19685 Cull through-mode 2D draws against scissor rectangle
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/GPUCommonHW.cpp
Labels: GE emulation, Performance

#19686 Fix small accuracy issue in through-mode 2D culling
  GPU/Common/DrawEngineCommon.cpp
Labels: GE emulation

#19691 Move irrelevant code out of Core.cpp
  Common/System/NativeApp.h
  Core/Core.cpp
  Core/Core.h
  Qt/QtMain.cpp
  Qt/mainwindow.h
  SDL/SDLMain.cpp
  UI/NativeApp.cpp
  UWP/App.cpp
  Windows/EmuThread.cpp
  Windows/MainWindow.cpp
Labels: Code Cleanup

#19694 Minor log manager refactor
  Common/Log.cpp
  Common/Log/LogManager.cpp
  Common/Log/LogManager.h
  Core/Config.cpp
  Core/Core.cpp
  Core/Core.h
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/WebSocket/LogBroadcaster.cpp
  Core/HLE/HLE.cpp
  Core/HLE/sceGe.cpp
  Core/Util/BlockAllocator.cpp
  GPU/GPUCommon.cpp
  UI/DevScreens.cpp
  UI/NativeApp.cpp
  UWP/App.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/EmuThread.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
Labels: Code Cleanup

#19695 More GE refactor
  Core/HLE/sceGe.cpp
  Core/System.cpp
  GPU/Debugger/Playback.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
Labels: Code Cleanup

#19697 Add "Split syscall" mechanism
  Core/HLE/HLE.cpp
  Core/HLE/HLE.h
  Core/HLE/sceGe.cpp
  Core/MIPS/MIPS.cpp
  Core/System.cpp
  GPU/Debugger/Playback.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  headless/Headless.cpp
Labels: Debugger

#19693 More GE debugger refactoring, initial work on the new debugger
  Core/Core.cpp
  Core/Core.h
  Core/Debugger/DisassemblyManager.cpp
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  Core/HW/Display.h
  Core/System.cpp
  GPU/Common/GPUDebugInterface.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/Debugger.h
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Stepping.cpp
  GPU/Debugger/Stepping.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUDefinitions.h
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImGe.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/GEDebugger/SimpleGLWindow.cpp
Labels: Code Cleanup, Debugger

#19699 More Im GE debugger: State window, extract more code from the Windows GE debugger
  CMakeLists.txt
  GPU/Common/GPUDebugInterface.h
  GPU/Debugger/State.cpp
  GPU/Debugger/State.h
  GPU/GPU.vcxproj
  GPU/GPU.vcxproj.filters
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  UWP/GPU_UWP/GPU_UWP.vcxproj
  UWP/GPU_UWP/GPU_UWP.vcxproj.filters
  Windows/Debugger/Debugger_Lists.cpp
  Windows/Debugger/Debugger_Lists.h
  Windows/GEDebugger/TabDisplayLists.cpp
  Windows/GEDebugger/TabDisplayLists.h
  Windows/GEDebugger/TabState.cpp
  Windows/GEDebugger/TabState.h
  Windows/GEDebugger/TabVertices.cpp
  Windows/GEDebugger/TabVertices.h
  Windows/W32Util/Misc.cpp
  Windows/W32Util/Misc.h
  android/jni/Android.mk
Labels: Code Cleanup, Debugger

#19703 Im Ge Debugger: Add basic disassembly view
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
Labels: Debugger

#19705 ImDebugger: Add a window to inspect upcoming CoreTiming events
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Collections/LinkedList.h
  Common/Serialize/Serializer.h
  Core/CoreTiming.cpp
  Core/CoreTiming.h
  Core/System.cpp
  Core/System.h
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/Debugger.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
Labels: Debugger

#19706 Core.cpp cleanup
  Common/Data/Encoding/Utf8.cpp
  Common/File/DirListing.cpp
  Common/File/DiskFree.cpp
  Common/File/FileUtil.cpp
  Common/GPU/D3D11/D3D11Loader.h
  Common/GPU/D3D9/D3DCompilerLoader.h
  Common/MachineContext.h
  Common/Render/Text/draw_text_win.h
  Common/StringUtils.cpp
  Common/System/NativeApp.h
  Common/Thread/ThreadUtil.cpp
  Core/Core.cpp
  Core/Core.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Debugger/WebSocket/GPUStatsSubscriber.cpp
  Core/HLE/proAdhoc.h
  Core/HLE/sceFont.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelThread.cpp
  Core/HLE/sceKernelThread.h
  Core/HW/AsyncIOManager.h
  Core/Loaders.cpp
  Core/MIPS/ARM/ArmAsm.cpp
  Core/MIPS/ARM64/Arm64Asm.cpp
  Core/MIPS/ARM64/Arm64IRAsm.cpp
  Core/MIPS/IR/IRAsm.cpp
  Core/MIPS/MIPS.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/RiscV/RiscVAsm.cpp
  Core/MIPS/x86/X64IRAsm.cpp
  Core/PSPLoaders.cpp
  Core/System.cpp
  Core/System.h
  Core/Util/PortManager.cpp
  GPU/GLES/GPU_GLES.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/Vulkan/GPU_Vulkan.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/PauseScreen.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  Windows/TouchInputHandler.cpp
  Windows/W32Util/Misc.cpp
  Windows/W32Util/TabControl.h
  headless/Headless.cpp
  libretro/libretro.cpp
Labels: Code Cleanup

#19707 Core improvements: Run-from-breakpoint fix, add two new step types
  Core/Core.cpp
  Core/Core.h
  Core/HLE/HLE.cpp
  UI/ImDebugger/ImDebugger.cpp
Labels: Debugger

#19711 Extracted fixes and cleanups from #19709
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Core/Config.h
  Core/Core.cpp
  Core/Core.h
  Core/System.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Debugger/Playback.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImGe.cpp
  Windows/EmuThread.cpp
  Windows/MainWindow.cpp
Labels: Code Cleanup

#19709 GE dump playback refactor and fix
  Core/HLE/HLETables.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelModule.h
  Core/MIPS/MIPSCodeUtils.h
  Core/PSPLoaders.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Playback.h
  UI/EmuScreen.cpp
  UI/ImDebugger/ImGe.cpp
Labels: Debugger

#19712 Show active compat flags on crash screen
  Core/Compatibility.cpp
  Core/Compatibility.h
  Core/Core.cpp
  UI/DebugOverlay.cpp
  Windows/EmuThread.cpp
Labels: User Interface

#19716 More debugger code cleanup
  Common/Log.h
  Common/Log/LogManager.cpp
  GPU/Common/GPUDebugInterface.cpp
  GPU/Debugger/Breakpoints.h
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/GECommandTable.cpp
  GPU/Debugger/GECommandTable.h
  GPU/Debugger/Playback.cpp
  GPU/Debugger/State.cpp
  GPU/Debugger/State.h
  GPU/Debugger/Stepping.cpp
  GPU/Debugger/Stepping.h
  GPU/ge_constants.h
  UI/ImDebugger/ImGe.cpp
  Windows/GEDebugger/TabState.cpp
  Windows/GEDebugger/TabState.h
Labels: Code Cleanup, Debugger

#19718 ImGeDebugger: new state viewer
  GPU/Common/GPUDebugInterface.h
  GPU/Debugger/GECommandTable.cpp
  GPU/Debugger/GECommandTable.h
  GPU/Debugger/State.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  UI/ImDebugger/ImGe.cpp
  Windows/GEDebugger/TabState.cpp
Labels: Debugger

#19721 Stepping cleanup, DebugInterface cleanup
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/Breakpoints.h
  Core/Debugger/DebugInterface.h
  Core/Debugger/DisassemblyManager.cpp
  Core/Debugger/DisassemblyManager.h
  Core/Debugger/WebSocket/BreakpointSubscriber.cpp
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  Core/HLE/HLE.cpp
  Core/HLE/HLE.h
  Core/HLE/KernelThreadDebugInterface.h
  Core/HLE/sceKernelThread.cpp
  Core/MIPS/MIPSAnalyst.cpp
  Core/MIPS/MIPSAnalyst.h
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MIPS/MIPSDebugInterface.h
  GPU/Common/GPUDebugInterface.h
  GPU/Debugger/Stepping.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDisasmView.h
  UI/ImDebugger/ImMemView.h
  UI/ImDebugger/ImStructViewer.cpp
  Windows/Debugger/BreakpointWindow.cpp
  Windows/Debugger/BreakpointWindow.h
  Windows/Debugger/CtrlDisAsmView.h
  Windows/Debugger/CtrlMemView.h
  Windows/Debugger/CtrlRegisterList.h
  Windows/Debugger/DebuggerShared.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/Debugger_Disasm.h
  Windows/Debugger/Debugger_Lists.cpp
  Windows/Debugger/Debugger_Lists.h
  Windows/Debugger/Debugger_MemoryDlg.cpp
  Windows/Debugger/Debugger_MemoryDlg.h
  Windows/Debugger/Debugger_VFPUDlg.cpp
  Windows/Debugger/DumpMemoryWindow.cpp
  Windows/Debugger/EditSymbolsWindow.cpp
  Windows/Debugger/WatchItemWindow.cpp
Labels: Code Cleanup

#19722 More GE debugger code cleanup
  Core/Debugger/DisassemblyManager.cpp
  Core/Debugger/DisassemblyManager.h
  Core/Debugger/WebSocket/BreakpointSubscriber.cpp
  Core/Debugger/WebSocket/DisasmSubscriber.cpp
  Core/Debugger/WebSocket/HLESubscriber.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  GPU/Debugger/State.cpp
  GPU/Debugger/State.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  UI/ImDebugger/ImGe.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlDisAsmView.h
  Windows/Debugger/EditSymbolsWindow.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/GEDebugger/GEDebugger.h
  Windows/GEDebugger/VertexPreview.cpp
Labels: Code Cleanup, Debugger

#19723 ImGui: Switch to the docking branch, enable window docking
  GPU/Common/TextureCacheCommon.cpp
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImGe.cpp
  ext/imgui/imgui.cpp
  ext/imgui/imgui.h
  ext/imgui/imgui_demo.cpp
  ext/imgui/imgui_draw.cpp
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_internal.h
  ext/imgui/imgui_tables.cpp
  ext/imgui/imgui_widgets.cpp
  ext/imgui/imstb_textedit.h
Labels: Debugger

#19724 Implement vertex preview in the new Ge debugger
  GPU/Debugger/State.cpp
  GPU/Debugger/State.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  Windows/GEDebugger/VertexPreview.cpp
Labels: Debugger

#19725 Fix vertex previews for triangle fans and strips, and lines.
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImMemView.cpp
Labels: Debugger

#19726 TextureReplacer: Load ini if available, even if just saving.
  GPU/Common/TextureReplacer.cpp
Labels: Texture replacement

#19727 Refactor the display list processing loop
  Common/TimeUtil.h
  Core/Core.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUDefinitions.h
  UI/ImDebugger/ImGe.cpp
Labels: Code Cleanup

#19728 GE debugger: Cleaner resume from stepping. Fixes GE debugging in God of War
  Core/Core.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUDefinitions.h
Labels: Debugger

#19729 ImGui improvements
  Core/HLE/proAdhocServer.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImMemView.cpp
  Windows/MainWindow.cpp
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_impl_platform.h
Labels: Debugger

#19730 ImGeDebugger stepping improvements
  Common/Render/Text/draw_text.cpp
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/State.cpp
  GPU/Debugger/Stepping.cpp
  GPU/Debugger/Stepping.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  ext/imgui/imgui_impl_thin3d.cpp
Labels: Debugger

#19731 GE debugger refactor: Have GPUCommon own more of the debugging data
  Core/Core.cpp
  Core/Debugger/WebSocket/GPURecordSubscriber.cpp
  Core/HLE/sceDisplay.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUDebugInterface.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Debugger/Breakpoints.cpp
  GPU/Debugger/Breakpoints.h
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/Debugger.h
  GPU/Debugger/GECommandTable.cpp
  GPU/Debugger/GECommandTable.h
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Record.cpp
  GPU/Debugger/Record.h
  GPU/Debugger/State.h
  GPU/Debugger/Stepping.cpp
  GPU/Debugger/Stepping.h
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/Software/SoftGpu.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  UI/DevScreens.cpp
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/GEDebugger/TabState.cpp
  Windows/GEDebugger/TabVertices.cpp
Labels: Code Cleanup

#19733 Ge debugger refactor: Lift even more functionality into GPUCommon
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/Common/GPUDebugInterface.cpp
  GPU/Common/GPUDebugInterface.h
  GPU/Common/SplineCommon.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/GPU_D3D11.cpp
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/Debugger.h
  GPU/Debugger/Stepping.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/Directx9/GPU_DX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GLES/GPU_GLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/Software/SoftGpu.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Software/TransformUnit.h
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  GPU/Vulkan/GPU_Vulkan.cpp
  UI/ImDebugger/ImGe.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/GEDebugger/GEDebugger.cpp
Labels: Code Cleanup, Debugger

#19735 ImGeDebugger: Make the preview work with software rendering
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
Labels: Debugger

#19736 ImGeDebugger: Add pixel color inspection
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/GPU/thin3d.h
  GPU/Common/DepthBufferCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/StencilCommon.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/FramebufferManagerDX9.cpp
  GPU/GLES/FramebufferManagerGLES.cpp
  GPU/GLES/StencilBufferGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  ext/imgui/imgui_impl_thin3d.cpp
  ext/imgui/imgui_impl_thin3d.h
Labels: Code Cleanup, Debugger

#19738 Android joystick event handling: Don't blow up java ref counting by forgetting ReleaseElements.
  Common/Render/Text/draw_text_android.cpp
  android/jni/app-android.cpp
Labels: Platform-specific (Android), Input/Controller

#19739 LogManager code cleanup
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Encoding/Compression.cpp
  Common/Log/ConsoleListener.cpp
  Common/Log/ConsoleListener.h
  Common/Log/LogManager.cpp
  Common/Log/LogManager.h
  Common/Log/StdioListener.cpp
  Common/Log/StdioListener.h
  Core/Core.cpp
  Core/Debugger/WebSocket/LogBroadcaster.cpp
  Core/HLE/sceGe.cpp
  GPU/Debugger/State.cpp
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  Qt/QtMain.cpp
  SDL/SDLJoystick.cpp
  SDL/SDLMain.cpp
  UI/DevScreens.cpp
  UI/NativeApp.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  UWP/PPSSPP_UWPMain.cpp
  android/jni/app-android.cpp
  android/jni/app-android.h
  headless/Headless.cpp
  ios/main.mm
  libretro/Makefile.common
  libretro/libretro.cpp
Labels: Code Cleanup

#19740 ImGeDebugger: Visualize and inspect depth/stencil buffers
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  ext/imgui/imgui_impl_thin3d.cpp
Labels: Debugger

#19742 Fix more GE debugger bugs, add break-on-count
  Core/HLE/sceGe.cpp
  GPU/Common/GPUDebugInterface.h
  GPU/Common/IndexGenerator.cpp
  GPU/Debugger/Debugger.cpp
  GPU/Debugger/Debugger.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  Windows/GEDebugger/GEDebugger.cpp
  Windows/InputBox.cpp
  Windows/InputBox.h
Labels: Debugger

#19743 Vertex decoder code cleanup
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/SplineCommon.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/Directx9/DrawEngineDX9.h
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/Software/TransformUnit.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  GPU/Vulkan/DrawEngineVulkan.h
  UI/ImDebugger/ImGe.cpp
  Windows/GEDebugger/TabVertices.cpp
  unittest/TestVertexJit.cpp
Labels: Code Cleanup

#19744 Cleanup: Avoid looking up the decoder multiple times per draw
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/SoftwareTransformCommon.h
  GPU/Common/SplineCommon.cpp
  GPU/Common/SplineCommon.h
  GPU/Common/TransformCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GLES/DrawEngineGLES.h
  GPU/GPUCommonHW.cpp
  GPU/Software/TransformUnit.cpp
Labels: Code Cleanup

#19745 De-spam an error message about ports
  Common/Log/LogManager.cpp
  Core/HLE/sceNetAdhoc.cpp
  SDL/CocoaBarItems.mm
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
Labels: User Interface

#19749 Restore removed <algorithm> includes.
  Common/CPUDetect.cpp
  Common/Data/Encoding/Utf8.cpp
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Common/GPU/Vulkan/VulkanMemory.cpp
  Common/Render/DrawBuffer.cpp
  Core/Debugger/MemBlockInfo.cpp
  Core/Dialog/PSPGamedataInstallDialog.cpp
  Core/Dialog/PSPMsgDialog.cpp
  Core/Dialog/PSPNetconfDialog.cpp
  Core/Dialog/PSPNpSigninDialog.cpp
  Core/Dialog/PSPOskDialog.cpp
  Core/Dialog/PSPSaveDialog.cpp
  Core/Dialog/SavedataParam.cpp
  Core/FileLoaders/CachingFileLoader.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileLoaders/RamCachingFileLoader.cpp
  Core/FileSystems/BlockDevices.cpp
  Core/FileSystems/ISOFileSystem.cpp
  Core/Font/PGF.cpp
  Core/HLE/ReplaceTables.cpp
  Core/HW/MemoryStick.cpp
  Core/HW/StereoResampler.cpp
  Core/MemMap.cpp
  Core/RetroAchievements.cpp
  Core/Screenshot.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/PresentationCommon.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/TextureScalerCommon.cpp
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/D3D11/StateMappingD3D11.cpp
  Windows/Debugger/CtrlDisAsmView.h
Labels: Code Cleanup

#19751 SIMD include cleanup
  CMakeLists.txt
  Common/Common.h
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Data/Convert/ColorConv.cpp
  Common/Data/Convert/SmallDataConvert.h
  Common/Math/CrossSIMD.h
  Common/Math/SIMDHeaders.h
  Common/Math/fast/fast_matrix.c
  Common/TimeUtil.cpp
  Core/HLE/ReplaceTables.cpp
  Core/HLE/__sceAudio.cpp
  Core/HW/MediaEngine.cpp
  Core/HW/StereoResampler.cpp
  Core/MIPS/IR/IRInterpreter.cpp
  Core/MIPS/MIPSVFPUUtils.cpp
  Core/MIPS/x86/CompVFPU.cpp
  Core/MIPS/x86/RegCacheFPU.cpp
  Core/Util/AudioFormat.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/IndexGenerator.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureDecoder.cpp
  GPU/Common/TextureScalerCommon.cpp
  GPU/Common/VertexDecoderHandwritten.cpp
  GPU/Common/VertexDecoderX86.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/GPUCommon.cpp
  GPU/GPUState.cpp
  GPU/GPUState.h
  GPU/Math3D.cpp
  GPU/Math3D.h
  GPU/Software/DrawPixelX86.cpp
  GPU/Software/Lighting.cpp
  GPU/Software/Rasterizer.cpp
  GPU/Software/RasterizerRectangle.cpp
  GPU/Software/RasterizerRegCache.h
  GPU/Software/Sampler.cpp
  GPU/Software/SamplerX86.cpp
  GPU/Software/TransformUnit.cpp
  ext/at3_standalone/atrac3plusdsp.cpp
  unittest/UnitTest.cpp
Labels: Code Cleanup

#19756 Depth raster: Fix when software transform is enabled, support non-through mode rectangles
  Common/Math/CrossSIMD.h
  GPU/Common/DepthRaster.cpp
  GPU/Common/DepthRaster.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Vulkan/DrawEngineVulkan.cpp
Labels: GE emulation

#19758 Depth raster: more improvements
  Common/Math/CrossSIMD.h
  GPU/Common/DepthRaster.cpp
  GPU/Common/DepthRaster.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
  UI/ImDebugger/ImGe.h
Labels: GE emulation

#19759 Enable software depth raster for Wipeout, Midnight Club LA, Resistance.
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  GPU/Common/DrawEngineCommon.cpp
  Tools/langtool/Cargo.lock
  UI/GameSettingsScreen.cpp
  assets/compat.ini
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: GE emulation

#19760 Depth raster: Clip rects to scissor too. Fixes some crashes
  GPU/Common/DepthRaster.cpp
Labels: GE emulation

#19764 Enable depth raster in all backends
  Common/Math/CrossSIMD.h
  GPU/Common/DepthRaster.cpp
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  UWP/lua/lua.cpp
  UWP/lua/lua.h
  UWP/lua/pch.cpp
  UWP/lua/pch.h
  UWP/lua/targetver.h
Labels: GE emulation

#19766 OpenXR - Remove non-functional Vulkan implementation
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/VR/OpenXRLoader.h
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Common/VR/VRBase.cpp
  Common/VR/VRBase.h
  Common/VR/VRFramebuffer.cpp
  Common/VR/VRFramebuffer.h
  Common/VR/VRRenderer.cpp
  android/jni/app-android.cpp
Labels: Code Cleanup

#19768 Depth raster: Bugfix, minor opt
  Common/Math/CrossSIMD.h
  GPU/Common/DepthRaster.cpp
Labels: GE emulation

#19771 UI fixes: Rework savedata manager a bit, default keyboard focus to Cancel in confirmation dialogs
  Common/UI/ViewGroup.h
  UI/MiscScreens.cpp
  UI/MiscScreens.h
  UI/SavedataScreen.cpp
  UI/SavedataScreen.h
  UI/TabbedDialogScreen.cpp
  UI/TabbedDialogScreen.h
Labels: User Interface

#19769 Depth raster optimizations: Merge viewport into projection matrix, prepare for further SIMD-ification
  Common/Math/CrossSIMD.h
  Core/MIPS/MIPSInt.cpp
  GPU/Common/DepthRaster.cpp
  GPU/Common/DrawEngineCommon.cpp
Labels: GE emulation

#19773 More SIMD: Add some matrix operations to CrossSIMD
  Common/Math/CrossSIMD.h
  Common/Math/SIMDHeaders.h
  Common/Math/fast/fast_matrix.c
  GPU/Common/DrawEngineCommon.cpp
Labels: GE emulation

#19774 Depth raster refactor
  Common/Math/CrossSIMD.h
  GPU/Common/DepthRaster.cpp
  GPU/Common/DepthRaster.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/Common/VertexDecoderCommon.h
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
Labels: GE emulation

#19776 Implement queueing of depth raster draws
  GPU/Common/DepthRaster.cpp
  GPU/Common/DepthRaster.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPU.h
  GPU/GPUCommon.cpp
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
Labels: GE emulation

#19777 Depth raster: Improve triangle culling in the "clipping" step
  Common/Math/CrossSIMD.h
  GPU/Common/DepthRaster.cpp
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
Labels: GE emulation

#19786 DepthRaster: Better guardband rejection, parallelize triangle setup
  Common/Math/CrossSIMD.h
  Common/Math/SIMDHeaders.h
  GPU/Common/DepthRaster.cpp
  unittest/UnitTest.cpp
Labels: GE emulation

#19789 Implement the low-quality depth raster mode, default to it on Android/iOS
  Common/Math/CrossSIMD.h
  Core/Config.cpp
  GPU/Common/DepthRaster.cpp
  GPU/Common/DepthRaster.h
  GPU/Common/DrawEngineCommon.cpp
Labels: GE emulation
