Repository hrydgard/ppsspp, pull requests merged in 2024-10, with the labels that each got.

#19505 iOS Chat input fix
  Common/UI/View.cpp
  GPU/Common/PresentationCommon.h
  GPU/Common/ReplacedTexture.cpp
  SDL/SDLMain.cpp
  UI/ChatScreen.cpp
  UI/ChatScreen.h
  UI/EmuScreen.cpp
  UI/PauseScreen.cpp
Labels: Platform-specific (iOS)

#19506 Android: New TV banner icon for the Gold version
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  UI/EmuScreen.cpp
  android/AndroidManifest.xml
  android/gold/res/drawable-xhdpi/ic_banner.png
  android/gold/res/drawable-xhdpi/tv_banner.png
  android/gold/res/drawable/ic_banner.png
  android/legacy/res/drawable-xhdpi/ic_banner.png
  android/res/drawable-xhdpi/ic_banner.png
  android/res/drawable/ic_banner.png
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Platform-specific (Android)

#19507 Prevent soft-locking the emulator on bad PBP files
  Core/Dialog/SavedataParam.cpp
  Core/MIPS/IR/IRRegCache.h
  Core/MIPS/x86/X64IRRegCache.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GameInfoCache.cpp
Labels: User Interface

#19476 Support iOS 18 Dark and Tinted Icons
  ios/assets.xcassets/AppIcon.appiconset/Contents.json
  ios/assets.xcassets/AppIcon.appiconset/dark.png
  ios/assets.xcassets/AppIcon.appiconset/tinted.png
  ios/assets.xcassets/AppIconGold.appiconset/Contents.json
  ios/assets.xcassets/AppIconGold.appiconset/dark.png
  ios/assets.xcassets/AppIconGold.appiconset/tinted.png
Labels: Platform-specific (iOS)

#19517 Fix minor code issues flagged by PVS-Studio and reported by alphrixus.
  Common/Data/Format/JSONWriter.cpp
  Common/File/PathBrowser.cpp
  Common/File/VFS/ZipFileReader.cpp
  Common/Net/Sinks.cpp
  Core/ControlMapper.cpp
  Core/Debugger/WebSocket/InputSubscriber.cpp
  Core/HLE/sceUsbMic.cpp
  Core/MIPS/IR/IRPassSimplify.cpp
  Core/RetroAchievements.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  UI/ControlMappingScreen.cpp
Labels: Code Cleanup

#19520 More assorted fixes
  Common/Buffer.cpp
  Common/GPU/Vulkan/VulkanMemory.cpp
  Core/FileSystems/BlockDevices.cpp
  Core/FileSystems/BlockDevices.h
  Core/Util/GameManager.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  UI/GameScreen.cpp
  Windows/W32Util/Misc.cpp
  android/src/org/ppsspp/ppsspp/TextRenderer.java
Labels: Code Cleanup

#19525 D3D9 fix
  Common/GPU/D3D9/D3D9ShaderCompiler.cpp
  Common/GPU/D3D9/D3D9ShaderCompiler.h
  Common/GPU/D3D9/thin3d_d3d9.cpp
  unittest/TestShaderGenerators.cpp
Labels: D3D9

#19529 More misc minor fixes
  Common/GPU/OpenGL/GLRenderManager.h
  Common/GPU/OpenGL/thin3d_gl.cpp
  Common/GPU/Vulkan/VulkanMemory.cpp
  Common/UI/PopupScreens.h
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/VertexDecoderCommon.cpp
  GPU/GPUCommon.cpp
  UI/DisplayLayoutScreen.cpp
  UI/EmuScreen.cpp
  UI/NativeApp.cpp
Labels: Code Cleanup

#19530 Even more misc fixes: Beaterator, sharp bilinear, remove back button
  Core/Debugger/SymbolMap.cpp
  Core/HLE/sceKernelEventFlag.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelThread.cpp
  Core/HLE/sceUsbMic.cpp
  Core/HLE/sceUsbMic.h
  UI/InstallZipScreen.cpp
  assets/shaders/defaultshaders.ini
  assets/shaders/upscale_sharp_bilinear.fsh
  assets/shaders/upscale_sharp_bilinear.vsh
Labels: Camera/Microphone, Code Cleanup

#19532 Fix issue where PresentedThisFrame didn't work correctly on SoftGPU
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  GPU/Software/SoftGpu.cpp
  GPU/Software/SoftGpu.h
  UI/GameSettingsScreen.cpp
Labels: Software Rasterizer

#19547 Improve some asserts, minor fixes (theme, warnings)
  Common/GPU/OpenGL/GLMemory.cpp
  Common/GPU/OpenGL/GLMemory.h
  Common/MemoryUtil.cpp
  Common/MemoryUtil.h
  Common/UI/Root.cpp
  Common/UI/View.cpp
  Common/UI/View.h
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureReplacer.cpp
  GPU/GLES/TextureCacheGLES.cpp
  GPU/Software/TransformUnit.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  GPU/Vulkan/TextureCacheVulkan.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/MainScreen.cpp
  UI/MainScreen.h
  Windows/GEDebugger/VertexPreview.cpp
  assets/themes/1995.ini
Labels: User Interface, Code Cleanup

#19540 [libretro] Expose "analog deadzone" and "analog sensitivity" options
  libretro/libretro.cpp
  libretro/libretro_core_options.h
Labels: Libretro

#19560 Increase the hardcoded free space reported by sceIoDevctl to 1.5 GB
  Core/HLE/sceIo.cpp
Labels: I/O

#19561 Simplify reporting code (removing two threads), other minor fixes
  Common/File/VFS/ZipFileReader.cpp
  Common/LogReporting.cpp
  Common/Net/HTTPRequest.cpp
  Common/Net/Resolve.cpp
  Core/ELF/ElfReader.cpp
  Core/MIPS/JitCommon/JitBlockCache.cpp
  Core/MIPS/JitCommon/JitBlockCache.h
  Core/MIPS/MIPSInt.cpp
  Core/Reporting.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/FramebufferManagerCommon.h
  GPU/GPUCommon.cpp
  GPU/GPUCommonHW.cpp
  GPU/GPUCommonHW.h
  UI/EmuScreen.cpp
  UI/ReportScreen.cpp
Labels: Code Cleanup

#19563 Vulkan: Fix potential crash from binding old CLUT textures
  Common/Data/Encoding/Shiftjis.h
  Common/Log/LogManager.cpp
  Common/UI/Tween.h
  Core/Dialog/SavedataParam.cpp
  Core/HLE/sceFont.cpp
  Core/MIPS/IR/IRInst.h
  Core/MIPS/IR/IRJit.h
  Core/MIPS/MIPS.cpp
  Core/MIPS/MIPSIntVFPU.cpp
  Core/Util/BlockAllocator.cpp
  Core/Util/BlockAllocator.h
  Core/Util/DisArm64.cpp
  Core/Util/GameDB.h
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/IndexGenerator.cpp
  GPU/Common/IndexGenerator.h
  GPU/Common/TextureShaderCommon.cpp
  GPU/Common/TextureShaderCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/GPU.h
  GPU/GPUCommonHW.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  ext/riscv-disas.cpp
Labels: Vulkan

#19564 Some more fixes, Swedish translation improvements
  Core/HLE/sceHttp.cpp
  Core/Reporting.cpp
  Core/System.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/GLES/ShaderManagerGLES.cpp
  GPU/GPU.cpp
  GPU/Vulkan/ShaderManagerVulkan.cpp
  UI/ReportScreen.cpp
  UI/ReportScreen.h
  assets/lang/sv_SE.ini
Labels: Code Cleanup

#19565 Postshader fixes
  UI/DisplayLayoutScreen.cpp
  UI/DisplayLayoutScreen.h
Labels: User Interface
