Repository hrydgard/ppsspp, pull requests merged in 2024-08, with the labels that each got.

#19388 iOS: Enable text chat
  Core/Util/GameManager.cpp
  UI/ChatScreen.cpp
  UI/InstallZipScreen.cpp
  UI/MainScreen.cpp
  UI/MainScreen.h
Labels: Platform-specific (iOS)

#19392 Warning fixes in our zlib fork
  ext/zlib/gzlib.c
  ext/zlib/gzread.c
  ext/zlib/gzwrite.c
Labels: Code Cleanup

#19401 Android: Add new build config "legacyOptimized", which targets an older Android SDK version
  UI/DevScreens.cpp
  android/build.gradle
  android/legacy/conv_color.sh
  android/legacy/icon_color.md
  android/legacy/res/drawable-hdpi/ic_launcher.png
  android/legacy/res/drawable-mdpi/ic_launcher.png
  android/legacy/res/drawable-xhdpi/ic_launcher.png
  android/legacy/res/drawable-xhdpi/tv_banner.png
  android/legacy/res/drawable-xxhdpi/ic_launcher.png
  android/legacy/res/mipmap-anydpi-v26/ic_launcher.xml
  android/legacy/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/legacy/res/mipmap-hdpi/ic_launcher.png
  android/legacy/res/mipmap-hdpi/ic_launcher_foreground.png
  android/legacy/res/mipmap-hdpi/ic_launcher_round.png
  android/legacy/res/mipmap-mdpi/ic_launcher.png
  android/legacy/res/mipmap-mdpi/ic_launcher_foreground.png
  android/legacy/res/mipmap-mdpi/ic_launcher_round.png
  android/legacy/res/mipmap-xhdpi/ic_launcher.png
  android/legacy/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/legacy/res/mipmap-xhdpi/ic_launcher_round.png
  android/legacy/res/mipmap-xxhdpi/ic_launcher.png
  android/legacy/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/legacy/res/mipmap-xxhdpi/ic_launcher_round.png
  android/legacy/res/values/ic_launcher_background.xml
  android/legacy/res/values/strings.xml
  android/res/drawable-xhdpi/ouya_icon.png
  build.gradle
Labels: Platform-specific (Android), Scoped Storage

#19420 OpenXR - Ensure we have a valid poses after app event
  Common/VR/VRFramebuffer.cpp
Labels: VR
