Repository hrydgard/ppsspp, pull requests merged in 2025-04, with the labels that each got.

#20197 Upgrade sol2, vulkan headers and gradle, fix plugins, fix a minor build issue
  Common/Log.h
  Core/HLE/KernelThreadDebugInterface.h
  Core/HLE/sceKernelThread.h
  Core/HLE/sceMpeg.cpp
  Core/System.cpp
  build.gradle
  ext/sol/config.hpp
  ext/sol/forward.hpp
  ext/sol/sol.hpp
  ext/vulkan/vk_platform.h
  ext/vulkan/vk_video/vulkan_video_codec_av1std.h
  ext/vulkan/vk_video/vulkan_video_codec_av1std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_av1std_encode.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_h264std_encode.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std_decode.h
  ext/vulkan/vk_video/vulkan_video_codec_h265std_encode.h
  ext/vulkan/vk_video/vulkan_video_codecs_common.h
  ext/vulkan/vulkan.h
  ext/vulkan/vulkan_android.h
  ext/vulkan/vulkan_beta.h
  ext/vulkan/vulkan_core.h
  ext/vulkan/vulkan_directfb.h
  ext/vulkan/vulkan_fuchsia.h
  ext/vulkan/vulkan_ggp.h
  ext/vulkan/vulkan_ios.h
  ext/vulkan/vulkan_macos.h
  ext/vulkan/vulkan_metal.h
  ext/vulkan/vulkan_screen.h
  ext/vulkan/vulkan_vi.h
  ext/vulkan/vulkan_wayland.h
  ext/vulkan/vulkan_win32.h
  ext/vulkan/vulkan_xcb.h
  ext/vulkan/vulkan_xlib.h
  ext/vulkan/vulkan_xlib_xrandr.h
Labels: Code Cleanup

#20199 Partially implement sceAudiocodec
  Core/HLE/ErrorCodes.h
  Core/HLE/sceAudiocodec.cpp
  Core/HLE/sceAudiocodec.h
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceMp3.cpp
  Core/HLE/sceUtility.cpp
  Core/HW/SimpleAudioDec.h
  Core/Util/AtracTrack.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/GameScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/MainScreen.cpp
  ext/at3_standalone/atrac3plusdec.cpp
Labels: Atrac3+

#20208 Disable HLE of scePsmf and scePsmfPlayer
  Core/Config.h
  Core/HLE/HLE.cpp
  headless/Headless.cpp
Labels: PSMF / MPEG, HLE/Kernel

#20209 More HLE cleanup, fix MP3 in sceAudiocodec
  Common/Data/Random/Rng.h
  Common/Log.h
  Common/Log/LogManager.cpp
  Core/HLE/ErrorCodes.h
  Core/HLE/sceAudiocodec.cpp
  Core/HLE/sceGameUpdate.cpp
  Core/HLE/sceHeap.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  Core/HLE/sceKernelMutex.cpp
  Core/HLE/sceKernelSemaphore.cpp
  Core/HLE/sceMp3.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceMpeg.h
  Core/HLE/sceReg.cpp
  UI/GameSettingsScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
Labels: MP3

#20213 CoreState code cleanup
  CMakeLists.txt
  Core/Core.cpp
  Core/Core.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Debugger/Breakpoints.cpp
  Core/HLE/sceIo.cpp
  Core/HW/AsyncIOManager.cpp
  Core/HW/AsyncIOManager.h
  Core/MIPS/MIPSDebugInterface.cpp
  Core/System.cpp
  Core/ThreadEventQueue.h
  Core/Util/PortManager.cpp
  GPU/GPUCommon.cpp
  UI/EmuScreen.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  Windows/EmuThread.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
  libretro/libretro.cpp
  unittest/JitHarness.cpp
Labels: Code Cleanup

#20219 Init/shutdown UPnP with the app, not each game. Also minor fixes and cleanups
  Core/HLE/sceNet.cpp
  Core/Loaders.cpp
  Core/Util/GameManager.cpp
  Core/Util/PortManager.cpp
  Core/Util/PortManager.h
  GPU/Debugger/Playback.cpp
  UI/InstallZipScreen.cpp
  UI/MainScreen.cpp
  UI/NativeApp.cpp
Labels: Networking / adhoc

#20220 Infrastructure multiplayer fixes
  Common/Data/Text/Parsers.h
  Common/Net/HTTPRequest.cpp
  Core/Dialog/PSPNetconfDialog.cpp
  Core/HLE/ErrorCodes.h
  Core/HLE/NetInetConstants.h
  Core/HLE/sceAudiocodec.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceNet.cpp
  Core/HLE/sceNet.h
  Core/HLE/sceNetResolver.cpp
  Core/HLE/sceNetResolver.h
  UI/ImDebugger/ImDebugger.cpp
  UI/PauseScreen.cpp
Labels: Networking / adhoc

#20221 More infrastructure networking fixes
  Common/Net/HTTPNaettRequest.cpp
  Common/Net/Resolve.cpp
  Core/Dialog/PSPNetconfDialog.cpp
  Core/HLE/sceNet.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/HLE/sceNetInet.cpp
  Core/HLE/sceNetResolver.cpp
  Core/HLE/sceUtility.cpp
  UI/PauseScreen.cpp
  assets/infra-dns.json
Labels: Networking / adhoc

#20226 Various libretro fixes.
  libretro/libretro.cpp
Labels: Libretro

#20225 Some minor fixes, ImDebugger features
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/File/FileUtil.cpp
  Common/Log/LogManager.h
  Common/StringUtils.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceReg.cpp
  GPU/Common/GPUStateUtils.cpp
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GameSettingsScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/ImDebugger/ImDisasmView.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
  UI/ImDebugger/ImMemView.cpp
  UI/ImDebugger/ImMemView.h
  UI/SavedataScreen.cpp
  UWP/CommonUWP/CommonUWP.vcxproj
  UWP/CommonUWP/CommonUWP.vcxproj.filters
  android/jni/Android.mk
  ext/imgui/CMakeLists.txt
  ext/imgui/imgui_extras.cpp
  ext/imgui/imgui_extras.h
  libretro/Makefile.common
Labels: User Interface, Code Cleanup, Debugger

#20228 Developer tools screen: Use tabs
  GPU/Common/GPUStateUtils.cpp
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/DeveloperToolsScreen.cpp
  UI/DeveloperToolsScreen.h
Labels: User Interface

#20229 Try to fix cross compile on macOS
  CMakeLists.txt
  b.sh
Labels: Platform-specific (Mac OS X)

#20230 Move to trash instead of deleting important files like savedata (Windows only so far)
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Common/System/System.h
  Core/Config.cpp
  UI/GameInfoCache.cpp
  UI/GameInfoCache.h
  UI/GameScreen.cpp
  UI/GameScreen.h
  UI/SavedataScreen.cpp
  Windows/main.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#20231 Fix lens flare in L.A. Rush
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/DrawEngineCommon.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/Directx9/DrawEngineDX9.cpp
  GPU/GLES/DrawEngineGLES.cpp
  GPU/Vulkan/DrawEngineVulkan.cpp
  assets/compat.ini
Labels: GE emulation

#20232 Add developer setting to disallow vulkan layers
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanContext.h
  Common/GPU/Vulkan/VulkanImage.cpp
  Core/Config.cpp
  Core/Config.h
  SDL/SDLVulkanGraphicsContext.cpp
  UI/DeveloperToolsScreen.cpp
  Windows/GPU/WindowsVulkanContext.cpp
  Windows/PPSSPP.vcxproj
  Windows/PPSSPP.vcxproj.filters
  android/jni/AndroidVulkanContext.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  ios/ViewControllerMetal.mm
Labels: Vulkan

#20233 Fix Star Ocean with MSAA enabled: don't use the blit optimization
  Common/GPU/Vulkan/VulkanQueueRunner.cpp
  GPU/Common/StencilCommon.cpp
Labels: GE emulation

#20235 ImGUI on SDL: Implement mouse cursor shape support
  SDL/SDLMain.cpp
Labels: SDL2

#20236 Blacklist older Intel GPUs from using Vulkan on Mac
  Common/GPU/Vulkan/VulkanLoader.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  GPU/GPUState.h
  UI/DarwinFileSystemServices.mm
  assets/compat.ini
Labels: GE emulation

#20237 SDL text renderer: Add some sanity checks.
  Common/Render/Text/draw_text_sdl.cpp
Labels: SDL2

#20240 minor-breakpoint-improvements
  UI/ImDebugger/ImDebugger.cpp
Labels: Debugger

#20241 Show little indicators on achievements of the type
  Core/HLE/sceIo.cpp
  UI/RetroAchievementScreens.cpp
Labels: RetroAchievements

#20242 ImDebugger: Add some audio investigation tools
  Core/Config.h
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx2.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  Core/HLE/sceKernelHeap.cpp
  Core/HLE/sceSas.cpp
  Core/HLE/sceSas.h
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  Core/HW/SimpleAudioDec.cpp
  Core/Util/AtracTrack.cpp
  Core/Util/AtracTrack.h
  UI/DeveloperToolsScreen.cpp
  UI/DeveloperToolsScreen.h
  UI/ImDebugger/ImDebugger.cpp
Labels: Atrac3+

#20243 Add a ZipFileLoader, which can let us load any single-file file type from a standard zip file
  CMakeLists.txt
  Common/StringUtils.cpp
  Common/StringUtils.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/FileLoaders/LocalFileLoader.h
  Core/FileLoaders/ZipFileLoader.cpp
  Core/FileLoaders/ZipFileLoader.h
  Core/FileSystems/FileSystem.h
  Core/Loaders.cpp
  Core/Loaders.h
  Core/Util/GameManager.cpp
  Core/Util/GameManager.h
  UI/GameSettingsScreen.cpp
  UI/InstallZipScreen.cpp
  UI/InstallZipScreen.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Loader

#20245 [Adhoc] Partially fixes multiplayer regression on GTA games.
  Core/HLE/proAdhoc.cpp
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#20248 Enable Vulkan again on certain Motorola devices, from a certain driver version
  Common/GPU/Vulkan/VulkanLoader.cpp
Labels: Platform-specific (Android), Vulkan

#20247 [Adhoc] Fixed truncated adhoc group name issue.
  Core/HLE/sceNetAdhoc.cpp
Labels: Networking / adhoc

#20253 Revert to using FFMPEG for MP3 playback
  Common/File/FileUtil.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Core/ELF/ElfReader.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/FileSystems/ISOFileSystem.cpp
  Core/HLE/sceAac.cpp
  Core/HLE/sceHttp.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelMutex.cpp
  Core/HLE/sceMp3.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/scePsmf.h
  Core/HW/SimpleAudioDec.cpp
  Core/MIPS/x86/Jit.cpp
  Core/System.cpp
  GPU/Common/FramebufferManagerCommon.cpp
  GPU/Common/SoftwareTransformCommon.cpp
  UI/DeveloperToolsScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  ext/imgui/imgui_extras.cpp
  ext/imgui/imgui_extras.h
Labels: Atrac3+

#20254 Desktop (Windows) menu: Add "Save frame dump", remove the old "Dump frame to log"
  Common/System/System.h
  SDL/CocoaBarItems.mm
  UI/DevScreens.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/NativeApp.cpp
  Windows/MainWindowMenu.cpp
  Windows/ppsspp.rc
  Windows/resource.h
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Platform-specific (Windows), User Interface

#20255 Vulkan: Auto Max Quality: Avoid conflict between aniso filtering and nearest filtering
  GPU/Common/TextureCacheCommon.cpp
Labels: GE emulation

#20256 Minor debugger fixes
  Core/HLE/__sceAudio.cpp
  Core/HLE/sceAudio.cpp
  Core/HLE/sceAudio.h
  Core/HLE/sceVaudio.cpp
  GPU/Debugger/State.cpp
  UI/ImDebugger/ImDebugger.cpp
Labels: Debugger

#20262 SDL: Allow configuring the audio buffer size
  Common/UI/PopupScreens.cpp
  Common/UI/PopupScreens.h
  Common/UI/View.cpp
  Common/UI/View.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/GameSettingsScreen.cpp
  Windows/MainWindowMenu.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: SDL2, Audio

#20263 Disable the Qt build temporarily
  .github/workflows/build.yml
Labels: Qt

#20265 Vulkan: Remove mac specific hack for specifying host coherent memory
  Common/GPU/Vulkan/VulkanMemory.cpp
  Common/GPU/Vulkan/VulkanMemory.h
Labels: Vulkan

#20266 Quick workaround for Android pause issue when launched from frontend
  UI/EmuScreen.cpp
  android/jni/app-android.cpp
Labels: Platform-specific (Android)

#20270 Avoid using shader blending in skip-buffer-effects mode
  Common/GPU/Vulkan/VulkanDebug.cpp
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/Render/ManagedTexture.cpp
  Common/Render/ManagedTexture.h
  Core/FileSystems/ISOFileSystem.cpp
  GPU/Common/DrawEngineCommon.cpp
  GPU/Common/GPUStateUtils.cpp
  GPU/Common/GPUStateUtils.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/Directx9/StateMappingDX9.cpp
  GPU/GLES/StateMappingGLES.cpp
  GPU/GPUCommonHW.cpp
  GPU/GPUState.h
  GPU/Software/RasterizerRectangle.cpp
  GPU/Vulkan/StateMappingVulkan.cpp
  UI/ControlMappingScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/MiscScreens.cpp
  UI/SavedataScreen.h
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/NativeActivity.java
Labels: GE emulation

#20286 New setting: Texture replacement load speed
  Common/Data/Format/IniFile.cpp
  Common/Data/Format/IniFile.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Core/HW/Display.cpp
  GPU/Common/ReplacedTexture.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Common/TextureCacheCommon.h
  GPU/Common/TextureReplacer.cpp
  Tools/langtool/Cargo.lock
  UI/DeveloperToolsScreen.cpp
  UI/EmuScreen.cpp
  UI/InstallZipScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: GE emulation

#20289 Setup script update from @bovirus, some function renaming
  Core/Dialog/SavedataParam.cpp
  Core/HLE/sceChnnlsv.cpp
  Core/HLE/sceChnnlsv.h
  Core/HLE/sceRtc.cpp
  Core/HLE/sceRtc.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  Windows/GEDebugger/GEDebugger.cpp
  ppsspp.iss
Labels: Debugger

#20299 Don't call rc_client_do_frame when paused.
  UI/EmuScreen.cpp
Labels: RetroAchievements

#20302 More misc fixes
  Common/Data/Format/JSONReader.cpp
  Common/GPU/OpenGL/GLQueueRunner.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/GPU/thin3d.cpp
  Common/MemArenaAndroid.cpp
  Common/Net/HTTPRequest.cpp
  Common/UI/View.cpp
  Core/FileLoaders/CachingFileLoader.cpp
  Core/FileLoaders/DiskCachingFileLoader.cpp
  Core/FileSystems/MetaFileSystem.cpp
  Core/HLE/sceFont.cpp
  Core/HLE/sceHeap.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceNet.cpp
  Core/HLE/scePsmf.cpp
  Core/HW/MediaEngine.cpp
  Core/MIPS/x86/X64IRAsm.cpp
  Core/MemMapFunctions.cpp
  Core/System.cpp
  GPU/Common/GPUStateUtils.cpp
  UI/EmuScreen.cpp
  UI/GameScreen.cpp
  UI/RetroAchievementScreens.cpp
  assets/compat.ini
  ext/libpng17/png.h
  ext/libpng17/pnglibconf.h
  ext/libpng17/pngpriv.h
Labels: User Interface

#20303 Some UI fixes, crashfixes
  Core/HLE/sceKernelModule.cpp
  Core/MemMap.cpp
  Core/Util/GameDB.cpp
  UI/EmuScreen.cpp
  UI/ImDebugger/ImGe.cpp
  UI/PauseScreen.cpp
  UI/PauseScreen.h
  UI/TabbedDialogScreen.cpp
Labels: User Interface

#20305 Fix exiting from framedump playback, some std::thread code cleanup
  Common/UI/PopupScreens.cpp
  Common/UI/View.h
  Core/Dialog/PSPSaveDialog.cpp
  Core/Dialog/PSPSaveDialog.h
  Core/HLE/sceIo.cpp
  Core/HLE/sceSas.cpp
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Playback.h
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/RemoteISOScreen.cpp
  UI/RemoteISOScreen.h
Labels: Code Cleanup
