Repository hrydgard/ppsspp, pull requests merged in 2025-03, with the labels that each got.

#20054 Switch to sleep_precise for WaitUntil(), bump VMA and gradle versions
  Common/TimeUtil.cpp
  Core/FrameTiming.cpp
  build.gradle
  ext/vma/vk_mem_alloc.h
Labels: Vulkan

#20055 libpng: Ignore benign errors.
  Common/Data/Format/PNGLoad.cpp
Labels: User Interface

#20057 Assorted cleanup
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/HLE/sceDmac.cpp
  Core/HLE/sceFont.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelThread.cpp
  Core/MIPS/ARM/ArmCompBranch.cpp
  Core/MIPS/ARM64/Arm64CompBranch.cpp
  Core/MIPS/IR/IRCompBranch.cpp
  Core/MIPS/MIPSInt.cpp
  Core/MIPS/MIPSTables.cpp
  Core/MIPS/x86/CompBranch.cpp
  GPU/Common/VertexDecoderCommon.cpp
  android/jni/app-android.cpp
Labels: Code Cleanup

#20061 Reduce logspam on failed screenshots, add more suggested actions on game crash screen
  Core/SaveState.cpp
  Core/Screenshot.cpp
  UI/DebugOverlay.cpp
  UI/NativeApp.cpp
Labels: User Interface

#20068 Hook framebuffer readback function in Persona 2
  Core/HLE/ReplaceTables.cpp
  Core/MIPS/MIPSAnalyst.cpp
Labels: GE emulation, GPU readback

#20070 Software renderer: Fix regression with gouraud shaded lines
  GPU/Debugger/State.cpp
  GPU/Software/Rasterizer.cpp
Labels: Software Rasterizer

#20072 UI threading improvements
  Common/System/System.h
  Core/Config.cpp
  Core/Config.h
  Core/Core.cpp
  Core/Core.h
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/Breakpoints.h
  GPU/Common/GPUDebugInterface.h
  GPU/Debugger/Breakpoints.cpp
  GPU/Debugger/Breakpoints.h
  GPU/GPUCommon.cpp
  GPU/GPUCommon.h
  GPU/Software/SoftGpu.h
  UI/MainScreen.cpp
  UI/NativeApp.cpp
  Windows/MainWindowMenu.cpp
  headless/Headless.cpp
  libretro/libretro.cpp
  unittest/UnitTest.cpp
Labels: User Interface, Code Cleanup, Debugger

#20077 Implement "WLAN Off" dialog, seen in rare games, plus deadlock fix
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Core/Dialog/PSPNetconfDialog.cpp
  Core/Dialog/PSPNetconfDialog.h
  Core/HLE/sceKernel.cpp
  Core/HLE/scePower.cpp
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Networking / adhoc, Vulkan

#20079 Touch control layout editor: Resize the game image to fit the editing surface
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  UI/EmuScreen.cpp
  UI/GamepadEmu.h
  UI/NativeApp.cpp
  UI/TouchControlLayoutScreen.cpp
Labels: User Interface

#19915 Android: Improve mouse input
  Common/Input/InputState.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  Qt/QtMain.cpp
  UI/DevScreens.cpp
  android/AndroidManifest.xml
  android/jni/app-android.cpp
  android/src/org/ppsspp/ppsspp/InputDeviceState.java
  android/src/org/ppsspp/ppsspp/MogaHack.java
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  android/src/org/ppsspp/ppsspp/NativeApp.java
  android/src/org/ppsspp/ppsspp/NativeGLView.java
  android/src/org/ppsspp/ppsspp/NativeSurfaceView.java
  ext/imgui/imgui_impl_platform.cpp
Labels: Platform-specific (Android), Input/Controller

#20080 Fix some framedump playback issues
  Common/File/FileUtil.cpp
  Common/System/Request.cpp
  Common/System/Request.h
  Core/FileSystems/BlobFileSystem.cpp
  Core/FileSystems/DirectoryFileSystem.cpp
  Core/HLE/sceMpeg.h
  Core/System.cpp
  Core/Util/GameDB.h
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Playback.h
  UI/DevScreens.cpp
  UI/ImDebugger/ImGe.cpp
  UI/OnScreenDisplay.cpp
  UI/PauseScreen.cpp
  Windows/EmuThread.cpp
  Windows/MainWindow.cpp
  Windows/main.cpp
  unittest/UnitTest.cpp
Labels: Debugger

#20090 Fix Atrac codecParams
  Core/HLE/AtracCtx.cpp
Labels: Atrac3+

#20091 ImDebugger: Add log config window, improve atrac window
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
Labels: Debugger

#20096 Misc logging/comment changes and fixes
  Common/File/FileUtil.cpp
  Core/Config.cpp
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/ErrorCodes.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelThread.cpp
  UI/DebugOverlay.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
Labels: Code Cleanup

#20113 Audiocodec findings, prepare for new Atrac3 implementation
  Common/Data/Text/Parsers.cpp
  Common/Data/Text/Parsers.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  Core/HLE/sceAudiocodec.cpp
  Core/HLE/sceAudiocodec.h
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelModule.h
  Core/HLE/sceMpeg.h
  Core/HLE/sceUtility.cpp
  Core/HLE/sceUtility.h
  UI/DevScreens.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
Labels: Atrac3+

#20114 Fix sceUtilityLoadModuleAv, allow browsing memory tags in the memory viewer
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceUtility.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
Labels: Atrac3+

#20115 More Atrac refactoring before the big PR
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/sceAtrac.cpp
Labels: Atrac3+, Code Cleanup

#20116 Even more Atrac refactoring
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/sceAtrac.cpp
  UI/ImDebugger/ImDebugger.cpp
Labels: Code Cleanup

#20117 Atrac: Split out track analysis
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/sceAtrac.cpp
Labels: Atrac3+, Code Cleanup

#20118 Atrac: Prepare for the new way of context management
  Common/Log.h
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  UI/ImDebugger/ImDebugger.cpp
Labels: Atrac3+, Code Cleanup

#20119 Fix an ordering issue in Atrac context creation
  Common/Serialize/SerializeFuncs.h
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/sceAtrac.cpp
Labels: Atrac3+, Code Cleanup

#20126 Fix a crash in sceAtrac sas integration
  Common/Log.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernelModule.cpp
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.h
  UI/NativeApp.cpp
Labels: Atrac3+

#20131 Castlevania X Chronicles - force "Simulate UMD delays" to on
  assets/compat.ini
Labels: Audio

#20130 Break out AtracTrack into its own file
  CMakeLists.txt
  Common/Log.cpp
  Common/Log.h
  Common/System/Request.h
  Core/Core.cpp
  Core/Core.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAtrac.h
  Core/Util/AtracTrack.cpp
  Core/Util/AtracTrack.h
  Qt/QtMain.cpp
  UI/DarwinFileSystemServices.mm
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  UWP/PPSSPP_UWPMain.cpp
  Windows/main.cpp
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup, Debugger

#20136 New sceAtrac impl: Fix low level decoding
  Core/HLE/AtracCtx2.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceUtility.cpp
Labels: Atrac3+

#20137 Screenshot performance improvement
  CMakeLists.txt
  Common/Thread/Promise.h
  Common/Thread/ThreadManager.cpp
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceKernelModule.cpp
  Core/SaveState.cpp
  Core/Screenshot.cpp
  Core/Screenshot.h
  Core/ThreadPools.cpp
  Core/ThreadPools.h
  GPU/Common/GPUDebugInterface.h
  GPU/Debugger/Record.cpp
  GPU/Software/SoftGpu.cpp
  UI/NativeApp.cpp
  UI/ReportScreen.cpp
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: User Interface

#20143 Fix crash when saving screenshots on a thread
  Common/Thread/ThreadManager.cpp
  Common/Thread/ThreadManager.h
  Core/Screenshot.cpp
Labels: User Interface

#20140 Move more error codes to the big enum
  Core/Dialog/PSPGamedataInstallDialog.cpp
  Core/Dialog/PSPGamedataInstallDialog.h
  Core/Dialog/PSPNetconfDialog.cpp
  Core/Dialog/PSPNpSigninDialog.cpp
  Core/Dialog/PSPScreenshotDialog.cpp
  Core/ELF/ElfReader.cpp
  Core/FileSystems/FileSystem.h
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/ErrorCodes.h
  Core/HLE/HLE.cpp
  Core/HLE/HLEHelperThread.cpp
  Core/HLE/KernelWaitHelpers.h
  Core/HLE/NetInetConstants.cpp
  Core/HLE/__sceAudio.cpp
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceAudio.cpp
  Core/HLE/sceCtrl.cpp
  Core/HLE/sceDisplay.cpp
  Core/HLE/sceDmac.cpp
  Core/HLE/sceFont.cpp
  Core/HLE/sceGe.cpp
  Core/HLE/sceHeap.cpp
  Core/HLE/sceJpeg.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  Core/HLE/sceKernelAlarm.cpp
  Core/HLE/sceKernelEventFlag.cpp
  Core/HLE/sceKernelHeap.cpp
  Core/HLE/sceKernelInterrupt.cpp
  Core/HLE/sceKernelMbx.cpp
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceKernelMsgPipe.cpp
  Core/HLE/sceKernelMutex.cpp
  Core/HLE/sceKernelSemaphore.cpp
  Core/HLE/sceKernelThread.cpp
  Core/HLE/sceKernelVTimer.cpp
  Core/HLE/sceMp3.cpp
  Core/HLE/sceMpeg.cpp
  Core/HLE/sceMpeg.h
  Core/HLE/sceNet.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/HLE/sceNetAdhocMatching.cpp
  Core/HLE/scePower.cpp
  Core/HLE/scePsmf.cpp
  Core/HLE/sceRtc.cpp
  Core/HLE/sceSas.cpp
  Core/HLE/sceSsl.cpp
  Core/HLE/sceUsb.cpp
  Core/HLE/sceUtility.cpp
  Core/HLE/sceVaudio.cpp
  Core/SaveState.cpp
  GPU/GPUCommon.cpp
Labels: Code Cleanup

#20138 Use the new sceAtrac implementation by default
  Core/Config.cpp
  Core/Config.h
  Core/HLE/sceAtrac.cpp
  Tools/langtool/Cargo.lock
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/TabbedDialogScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  headless/Headless.cpp
  test.py
Labels: Atrac3+

#20149 Fix regression in Tomb Raider Legends
  Core/HLE/sceAtrac.cpp
  Core/MemMap.h
  Core/Util/AtracTrack.cpp
Labels: Atrac3+

#20152 Settings: Load tabs on demand, instead of all at once
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  Core/Util/PPGeDraw.cpp
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/DriverManagerScreen.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GPUDriverTestScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/MainScreen.cpp
  UI/RemoteISOScreen.cpp
  UI/RetroAchievementScreens.cpp
  UI/RetroAchievementScreens.h
  UI/SavedataScreen.cpp
  UI/TabbedDialogScreen.cpp
  UI/TabbedDialogScreen.h
  UI/TouchControlVisibilityScreen.cpp
Labels: User Interface

#20154 LocoRoco fix, add ability to ImDebugger to export modules as jpscptrace definitions
  Common/Data/Text/Parsers.h
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/Log.cpp
  Common/Log.h
  Core/HLE/AtracCtx2.cpp
  Core/HW/SasAudio.cpp
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  libretro/libretro.cpp
Labels: Atrac3+, Debugger

#20157 Logging optimization
  Common/Log.h
  Common/Log/LogManager.cpp
  Common/Log/LogManager.h
  Core/Dialog/SavedataParam.cpp
  Core/HLE/HLE.cpp
  Core/HLE/HLE.h
Labels: Performance

#20156 Reimplement Atrac-through-SAS
  Core/HLE/AtracCtx.cpp
  Core/HLE/AtracCtx.h
  Core/HLE/AtracCtx2.cpp
  Core/HLE/AtracCtx2.h
  Core/HLE/ErrorCodes.h
  Core/HLE/sceAtrac.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceSas.cpp
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  Core/System.cpp
  Core/WebServer.cpp
  Core/WebServer.h
  UI/ImDebugger/ImDebugger.cpp
  UI/NativeApp.cpp
  UI/TabbedDialogScreen.cpp
Labels: Atrac3+

#20159 Startup code cleanup
  Core/CoreParameter.h
  Core/ELF/ParamSFO.h
  Core/FileSystems/MetaFileSystem.cpp
  Core/FileSystems/MetaFileSystem.h
  Core/Loaders.cpp
  Core/Loaders.h
  Core/PSPLoaders.cpp
  Core/PSPLoaders.h
  Core/System.cpp
Labels: Code Cleanup

#20161 Recent files code cleanup
  CMakeLists.txt
  Common/File/FileUtil.cpp
  Common/System/System.h
  Core/Config.cpp
  Core/Config.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/System.cpp
  Core/Util/GameManager.cpp
  Core/Util/RecentFiles.cpp
  Core/Util/RecentFiles.h
  Core/WebServer.cpp
  SDL/CocoaBarItems.mm
  UI/GameInfoCache.cpp
  UI/GameScreen.cpp
  UI/GameScreen.h
  UI/MainScreen.cpp
  UI/MiscScreens.cpp
  UI/PSPNSApplicationDelegate.mm
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  b.sh
  libretro/Makefile.common
Labels: User Interface

#20169 First step of adding a lua console
  CMakeLists.txt
  Common/Common.vcxproj
  Common/Common.vcxproj.filters
  Common/Thread/ThreadUtil.cpp
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Debugger/DisassemblyManager.h
  Core/HLE/proAdhoc.cpp
  Core/HLE/proAdhocServer.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/LuaContext.cpp
  Core/LuaContext.h
  Core/System.cpp
  UI/ImDebugger/ImConsole.cpp
  UI/ImDebugger/ImConsole.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/MainScreen.cpp
  UI/NativeApp.cpp
  UI/UI.vcxproj
  UI/UI.vcxproj.filters
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  UWP/UI_UWP/UI_UWP.vcxproj
  UWP/UI_UWP/UI_UWP.vcxproj.filters
  UWP/UWP.vcxproj
  android/jni/Android.mk
  ext/imgui/imgui_impl_platform.cpp
  ext/sol/config.hpp
  ext/sol/forward.hpp
  ext/sol/sol.hpp
  libretro/Makefile.common
Labels: Scripting

#20173 More minor UI fixes
  Common/Render/DrawBuffer.cpp
  Common/StringUtils.cpp
  Common/UI/PopupScreens.cpp
  Common/UI/Screen.cpp
  Common/UI/Screen.h
  Common/UI/ViewGroup.cpp
  Core/HLE/sceDisplay.cpp
  Core/System.cpp
  UI/DisplayLayoutScreen.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/PauseScreen.cpp
  Windows/MainWindow.cpp
  Windows/MainWindow.h
  Windows/MainWindowMenu.cpp
Labels: User Interface

#20177 More minor UI fixes
  Common/Data/Text/Parsers.h
  Common/Log.cpp
  Common/Log.h
  UI/DebugOverlay.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  Windows/MainWindow.cpp
  Windows/W32Util/ShellUtil.cpp
  Windows/W32Util/ShellUtil.h
Labels: User Interface

#20181 Add symbol map export support to the ImDebugger
  Common/Data/Text/Parsers.h
  Common/File/FileUtil.cpp
  Common/File/FileUtil.h
  Common/Log.cpp
  Core/Config.cpp
  Core/Config.h
  Core/Debugger/SymbolMap.cpp
  Core/Debugger/SymbolMap.h
  Core/Debugger/WebSocket/HLESubscriber.cpp
  UI/DebugOverlay.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/MainScreen.cpp
Labels: Debugger

#20182 Fix another linebreak issue in savedata dialog
  Common/Render/Text/draw_text.cpp
  Common/Render/Text/draw_text_win.cpp
  Common/StringUtils.cpp
  Common/StringUtils.h
  UI/SavedataScreen.cpp
  android/src/org/ppsspp/ppsspp/TextRenderer.java
  assets/compat.ini
Labels: User Interface

#20183 Refactor the PSP boot process
  Common/Data/Collections/TinySet.h
  Common/ExceptionHandlerSetup.h
  Common/GPU/Vulkan/VulkanImage.cpp
  Common/GPU/Vulkan/VulkanImage.h
  Core/Config.cpp
  Core/CoreParameter.h
  Core/Debugger/DisassemblyManager.cpp
  Core/Debugger/WebSocket.cpp
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/GPURecordSubscriber.cpp
  Core/Debugger/WebSocket/GPUStatsSubscriber.cpp
  Core/Debugger/WebSocket/GameBroadcaster.cpp
  Core/Debugger/WebSocket/GameSubscriber.cpp
  Core/Debugger/WebSocket/HLESubscriber.cpp
  Core/Debugger/WebSocket/ReplaySubscriber.cpp
  Core/Debugger/WebSocket/SteppingBroadcaster.cpp
  Core/FileLoaders/RamCachingFileLoader.cpp
  Core/FileLoaders/RamCachingFileLoader.h
  Core/FileSystems/BlockDevices.h
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernelMemory.cpp
  Core/Loaders.cpp
  Core/MIPS/MIPSDebugInterface.cpp
  Core/MemMap.cpp
  Core/PSPLoaders.cpp
  Core/Reporting.cpp
  Core/RetroAchievements.cpp
  Core/RetroAchievements.h
  Core/SaveState.cpp
  Core/System.cpp
  Core/System.h
  Core/Util/PPGeDraw.cpp
  GPU/Debugger/State.cpp
  GPU/GPU.cpp
  GPU/GPU.h
  UI/DiscordIntegration.cpp
  UI/DisplayLayoutScreen.cpp
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/ImDebugger/ImDisasmView.cpp
  UI/PauseScreen.cpp
  UI/SavedataScreen.cpp
  android/jni/TestRunner.cpp
  android/src/org/ppsspp/ppsspp/NativeSurfaceView.java
  headless/Headless.cpp
  libretro/libretro.cpp
Labels: User Interface

#20186 Expose some PSP kernel structs in headers
  CMakeLists.txt
  Common/Math/expression_parser.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/Debugger/Breakpoints.h
  Core/Debugger/SymbolMap.h
  Core/HLE/KernelThreadDebugInterface.h
  Core/HLE/PSPThreadContext.h
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceKernelMemory.h
  Core/HLE/sceKernelModule.cpp
  Core/HLE/sceKernelModule.h
  Core/HLE/sceKernelThread.cpp
  Core/HLE/sceKernelThread.h
  Core/MIPS/MIPSDebugInterface.h
  Core/MemMap.h
  GPU/GPUCommon.cpp
  UI/ImDebugger/ImDebugger.cpp
  Windows/Debugger/Debugger_Lists.cpp
Labels: Debugger
