Repository hrydgard/ppsspp, pull requests merged in 2025-02, with the labels that each got.

#19947 Fixes for minor code issues reported by PVS-Studio
  Common/GPU/Vulkan/VulkanContext.cpp
  Common/GPU/Vulkan/VulkanRenderManager.cpp
  Common/Math/math_util.h
  Common/Render/Text/draw_text.cpp
  Common/UI/IconCache.cpp
  Core/Core.cpp
  Core/HLE/sceNetAdhoc.cpp
  Core/HLE/sceUsbMic.cpp
  Core/MIPS/MIPSVFPUUtils.h
  Core/MIPS/x86/CompVFPU.cpp
  Core/MIPS/x86/RegCache.cpp
  Core/Util/BlockAllocator.cpp
  GPU/Common/TextureCacheCommon.cpp
  GPU/Software/SoftGpu.cpp
  UI/MainScreen.cpp
Labels: Code Cleanup

#19948 Consolidate error codes into the big enum
  Core/Dialog/PSPDialog.cpp
  Core/Dialog/PSPDialog.h
  Core/Dialog/PSPGamedataInstallDialog.cpp
  Core/Dialog/PSPGamedataInstallDialog.h
  Core/Dialog/PSPMsgDialog.cpp
  Core/Dialog/PSPMsgDialog.h
  Core/Dialog/PSPOskDialog.cpp
  Core/Dialog/PSPSaveDialog.cpp
  Core/Dialog/PSPSaveDialog.h
  Core/Dialog/SavedataParam.cpp
  Core/HLE/ErrorCodes.h
  Core/HLE/sceAudio.h
  Core/HLE/sceIo.cpp
  Core/HLE/sceKernel.cpp
  Core/HLE/sceKernel.h
  Core/HLE/sceKernelMemory.cpp
  Core/HLE/sceUmd.cpp
  Core/HLE/sceUmd.h
  Core/HLE/sceUsb.cpp
  Core/HLE/sceUsbMic.cpp
  Core/HLE/sceUtility.cpp
  Core/HLE/sceUtility.h
Labels: Code Cleanup

#19953 Struct viewer - Add watch edit and show in window menu
  Common/GhidraClient.cpp
  Common/GhidraClient.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImStructViewer.cpp
  UI/ImDebugger/ImStructViewer.h
Labels: Debugger

#19480 use ComPtr for misc. things
  GPU/Common/Draw2D.h
  UI/RemoteISOScreen.cpp
  Windows/BufferLock.h
  Windows/CaptureDevice.cpp
  Windows/CaptureDevice.h
  Windows/DSoundStream.cpp
  Windows/DSoundStream.h
  Windows/DinputDevice.cpp
  Windows/DinputDevice.h
  Windows/W32Util/ShellUtil.cpp
  Windows/WASAPIStream.cpp
  Windows/main.cpp
Labels: Code Cleanup

#19962 OpenXR - NonVR option fixed
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  GPU/GLES/ShaderManagerGLES.cpp
Labels: VR

#19965 Android shortcut icons: Pad icon images to fix the aspect ratio
  android/src/org/ppsspp/ppsspp/ShortcutActivity.java
Labels: Platform-specific (Android)

#19967 Support battery percentage display on SDL
  CMakeLists.txt
  Common/Battery/AppleBatteryClient.m
  Common/Battery/Battery.h
  Common/System/System.h
  SDL/SDLMain.cpp
  UI/DebugOverlay.cpp
  UI/GameSettingsScreen.cpp
  ios/main.mm
Labels: SDL2

#19971 Volume control UI changes, part 2
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Core/HLE/__sceAudio.cpp
  Core/HW/SasAudio.cpp
  Core/HW/SasReverb.cpp
  Core/HW/SasReverb.h
  UI/BackgroundAudio.cpp
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/RetroAchievementScreens.cpp
  headless/Headless.cpp
  unittest/UnitTest.cpp
Labels: Audio

#19972 Adding sceNet_lib
  CMakeLists.txt
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/HLE/FunctionWrappers.h
  Core/HLE/HLETables.cpp
  Core/HLE/sceNet_lib.cpp
  Core/HLE/sceNet_lib.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: HLE/Kernel

#19973 Add support for displaying the battery percentage on Windows.
  Windows/main.cpp
Labels: User Interface

#19974 Nukem9's D3D11 flipmodel, rebased
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Windows/GPU/D3D11Context.cpp
  Windows/GPU/D3D11Context.h
Labels: D3D11

#19979 Ge: Apply slight adjustment to cull range, see issue #17061
  GPU/Common/ShaderUniforms.cpp
Labels: GE emulation

#19980 ImDebugger: Add zoom functionality, file export
  Core/Core.cpp
  Core/Core.h
  Core/HLE/sceHttp.cpp
  GPU/Debugger/Playback.cpp
  GPU/Debugger/Playback.h
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
  UI/ImDebugger/ImGe.h
Labels: GE emulation

#19982 Remove unused float16 type, split out sceAac from sceMp4
  CMakeLists.txt
  Common/Math/math_util.h
  Core/Core.vcxproj
  Core/Core.vcxproj.filters
  Core/HLE/HLETables.cpp
  Core/HLE/sceAac.cpp
  Core/HLE/sceAac.h
  Core/HLE/sceKernel.cpp
  Core/HLE/sceMp4.cpp
  Core/HLE/sceMp4.h
  UWP/CoreUWP/CoreUWP.vcxproj
  UWP/CoreUWP/CoreUWP.vcxproj.filters
  android/jni/Android.mk
  libretro/Makefile.common
Labels: Code Cleanup

#19983 Touch: Implement "Touch gliding" (keep all dragged/touched buttons pressed until touch release)
  Common/Input/InputState.h
  Core/Config.cpp
  Core/Config.h
  UI/EmuScreen.cpp
  UI/GameSettingsScreen.cpp
  UI/GamepadEmu.cpp
  UI/GamepadEmu.h
Labels: Input/Controller, Touch screen

#19984 Theme system fixes and additions
  Common/Data/Color/RGBAUtil.cpp
  Common/UI/ScrollView.cpp
  Common/UI/View.cpp
  Common/UI/View.h
  UI/GameSettingsScreen.cpp
  UI/MiscScreens.cpp
  UI/Theme.cpp
  assets/themes/1995.ini
  assets/themes/defaultthemes.ini
  assets/themes/slateforest.ini
  assets/themes/vinewood.ini
Labels: User Interface

#19986 Workaround for retroarch's buildserver using an old Windows SDK
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Windows/GPU/D3D11Context.cpp
Labels: D3D11, Libretro

#19988 Add GLES/EGL build config to build script
  b.sh
Labels: OpenGL, GE emulation

#19995 More theming work
  Common/UI/PopupScreens.cpp
  Common/UI/Tween.cpp
  Common/UI/Tween.h
  Common/UI/UIScreen.cpp
  Common/UI/View.cpp
  Common/UI/View.h
  Common/UI/ViewGroup.cpp
  Common/UI/ViewGroup.h
  UI/MainScreen.cpp
  UI/Theme.cpp
  assets/themes/1995.ini
  assets/themes/defaultthemes.ini
  assets/themes/slateforest.ini
  assets/themes/vinewood.ini
Labels: User Interface

#19996 Add confirmation on exit
  Common/Data/Text/Parsers.cpp
  Common/Data/Text/Parsers.h
  Core/Config.cpp
  Core/Config.h
  Core/Dialog/PSPSaveDialog.cpp
  Core/Dialog/PSPSaveDialog.h
  Core/HLE/sceUtility.cpp
  Core/SaveState.cpp
  Core/SaveState.h
  UI/GameSettingsScreen.cpp
  UI/PauseScreen.cpp
  UI/PauseScreen.h
  Windows/MainWindow.cpp
  Windows/MainWindow.h
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#19997 Exit fixes, AutoDNS fixes
  Core/Dialog/PSPNetconfDialog.cpp
  Core/HLE/sceNet.cpp
  Core/HLE/sceNet.h
  UI/PauseScreen.cpp
  UI/PauseScreen.h
  UI/Theme.cpp
  Windows/MainWindow.cpp
  Windows/MainWindow.h
  Windows/MainWindowMenu.cpp
  Windows/main.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: Networking / adhoc, User Interface

#19991 use ComPtr for D3D11
  Common/GPU/D3D11/thin3d_d3d11.cpp
  GPU/D3D11/D3D11Util.cpp
  GPU/D3D11/D3D11Util.h
  GPU/D3D11/DrawEngineD3D11.cpp
  GPU/D3D11/DrawEngineD3D11.h
  GPU/D3D11/ShaderManagerD3D11.cpp
  GPU/D3D11/ShaderManagerD3D11.h
  GPU/D3D11/StateMappingD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.cpp
  GPU/D3D11/TextureCacheD3D11.h
  Windows/DinputDevice.h
  Windows/GPU/D3D11Context.cpp
  Windows/GPU/D3D11Context.h
Labels: D3D11, Code Cleanup

#20000 More assorted fixes
  .ycm_extra_conf.py
  CMakeLists.txt
  Common/Data/Text/Parsers.cpp
  Common/File/VFS/ZipFileReader.cpp
  Core/Config.cpp
  Core/Config.h
  Core/Dialog/SavedataParam.cpp
  Tools/langtool/Cargo.lock
  UI/GameInfoCache.cpp
  UI/GameSettingsScreen.cpp
  android/jni/Locals.mk
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  ext/glslang-build/Android.mk
  ext/miniupnp-build/Android.mk
Labels: Code Cleanup

#20001 Texture shader UI cleanup
  UI/GameSettingsScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  assets/shaders/tex_mmpx.csh
Labels: User Interface

#20003 More ImDebugger improvements (sasaudio, ui)
  Core/HLE/sceDisplay.cpp
  Core/HLE/sceSas.cpp
  Core/HLE/sceSas.h
  Core/HW/SasAudio.cpp
  Core/HW/SasAudio.h
  GPU/Common/PresentationCommon.cpp
  GPU/Common/PresentationCommon.h
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_impl_platform.h
Labels: Debugger

#20005 Atrac3+: Try to work around Code Lyoko issue
  Core/HLE/AtracCtx.cpp
  Core/HW/Atrac3Standalone.cpp
  ext/at3_standalone/atrac3plusdec.cpp
Labels: Atrac3+

#20006 Turn the break reason into an enum, fix some minor issues
  Core/Core.cpp
  Core/Core.h
  Core/CoreTiming.cpp
  Core/Debugger/Breakpoints.cpp
  Core/Debugger/WebSocket/CPUCoreSubscriber.cpp
  Core/Debugger/WebSocket/MemorySubscriber.cpp
  Core/Debugger/WebSocket/SteppingBroadcaster.cpp
  Core/Debugger/WebSocket/SteppingSubscriber.cpp
  Core/HLE/HLE.cpp
  Core/MIPS/MIPSTables.cpp
  Core/MIPS/x86/CompBranch.cpp
  Core/RetroAchievements.cpp
  Core/SaveState.cpp
  SDL/CocoaBarItems.mm
  UI/EmuScreen.cpp
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImMemView.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/Debugger_Disasm.cpp
  Windows/Debugger/DumpMemoryWindow.cpp
  Windows/MainWindow.cpp
  Windows/MainWindowMenu.cpp
Labels: Code Cleanup

#20009 Add easy way to copy build number, add way to copy system information to clipboard
  Common/Data/Text/Parsers.cpp
  Common/Data/Text/Parsers.h
  Common/UI/View.cpp
  Common/UI/View.h
  UI/DevScreens.cpp
  UI/DevScreens.h
  UI/MainScreen.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface

#20010 DPI: Simplify by removing support for non-square pixels
  Common/Render/DrawBuffer.cpp
  Common/Render/Text/draw_text.cpp
  Common/System/Display.cpp
  Common/System/Display.h
  Common/UI/Context.cpp
  Common/VR/PPSSPPVR.cpp
  Common/VR/PPSSPPVR.h
  Core/HLE/sceAtrac.cpp
  Core/TiltEventProcessor.cpp
  GPU/Common/PresentationCommon.cpp
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/DevScreens.cpp
  UI/DisplayLayoutScreen.cpp
  UI/GamepadEmu.cpp
  UI/MiscScreens.cpp
  UI/NativeApp.cpp
  UI/TouchControlLayoutScreen.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/Debugger/CtrlDisAsmView.cpp
  Windows/Debugger/CtrlMemView.cpp
  Windows/Debugger/CtrlRegisterList.cpp
  Windows/Debugger/Debugger_MemoryDlg.cpp
  Windows/GEDebugger/CtrlDisplayListView.cpp
  Windows/MainWindow.cpp
  Windows/TouchInputHandler.cpp
  android/jni/app-android.cpp
  ext/imgui/imgui_impl_platform.cpp
  ext/imgui/imgui_impl_thin3d.cpp
  ios/DisplayManager.mm
Labels: User Interface, Code Cleanup

#20011 macOS SDL: Set the metal layer resolution properly, remove DPI hacks.
  SDL/SDLCocoaMetalLayer.mm
  SDL/SDLMain.cpp
Labels: SDL2, Platform-specific (Mac OS X), User Interface

#20012 More DPI work
  Common/System/Display.cpp
  Common/System/Display.h
  Common/System/NativeApp.h
  Core/Core.cpp
  Core/HLE/sceMp4.cpp
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/DevScreens.cpp
  UI/NativeApp.cpp
  UWP/App.cpp
  UWP/PPSSPP_UWPMain.cpp
  Windows/MainWindow.cpp
  android/jni/app-android.cpp
  assets/compat.ini
  ios/DisplayManager.mm
Labels: User Interface

#20013 UI DPI scale setting
  Common/System/Display.cpp
  Common/System/Display.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Qt/QtMain.cpp
  SDL/SDLMain.cpp
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  UWP/App.cpp
  Windows/MainWindow.cpp
  android/jni/app-android.cpp
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
  ios/DisplayManager.mm
Labels: User Interface

#20014 Add logging of Additional chunk data
  Core/HLE/AtracCtx.cpp
Labels: Atrac3+

#20016 Android: Rework how DPI and Android hardware scaling interacts.
  android/jni/app-android.cpp
Labels: Platform-specific (Android), User Interface

#20018 fix compiler warnings
  Common/GPU/D3D11/thin3d_d3d11.cpp
  Common/GPU/D3D9/thin3d_d3d9.cpp
  Common/GPU/Vulkan/thin3d_vulkan.cpp
  Common/Log/ConsoleListener.cpp
  Common/TimeUtil.cpp
  Core/Debugger/SymbolMap.cpp
  Core/MIPS/IR/IRFrontend.cpp
  Core/MIPS/MIPSVFPUUtils.cpp
  GPU/Directx9/ShaderManagerDX9.cpp
  UI/BackgroundAudio.cpp
  UI/ImDebugger/ImDebugger.cpp
  Windows/CaptureDevice.cpp
  Windows/Debugger/DumpMemoryWindow.cpp
  Windows/GEDebugger/TabDisplayLists.cpp
  Windows/GEDebugger/TabDisplayLists.h
  Windows/GEDebugger/TabState.cpp
  Windows/GEDebugger/TabVertices.cpp
  Windows/WASAPIStream.cpp
  Windows/main.cpp
Labels: Code Cleanup

#20024 More ImDebugger fixes
  UI/ImDebugger/ImDebugger.cpp
  UI/ImDebugger/ImDebugger.h
  UI/ImDebugger/ImGe.cpp
Labels: Debugger

#20029 Add long-requested feature to take screenshots of the raw game image instead of the processed output.
  Common/Input/KeyCodes.h
  Core/Config.cpp
  Core/Config.h
  Core/ConfigValues.h
  Core/HLE/sceCtrl.cpp
  Core/KeyMap.cpp
  Core/KeyMap.h
  Core/KeyMapDefaults.cpp
  Core/KeyMapDefaults.h
  UI/EmuScreen.cpp
  UI/EmuScreen.h
  UI/GameSettingsScreen.cpp
  UI/NativeApp.cpp
  android/AndroidManifest.xml
  android/src/org/ppsspp/ppsspp/NativeActivity.java
  assets/lang/ar_AE.ini
  assets/lang/az_AZ.ini
  assets/lang/bg_BG.ini
  assets/lang/ca_ES.ini
  assets/lang/cz_CZ.ini
  assets/lang/da_DK.ini
  assets/lang/de_DE.ini
  assets/lang/dr_ID.ini
  assets/lang/en_US.ini
  assets/lang/es_ES.ini
  assets/lang/es_LA.ini
  assets/lang/fa_IR.ini
  assets/lang/fi_FI.ini
  assets/lang/fr_FR.ini
  assets/lang/gl_ES.ini
  assets/lang/gr_EL.ini
  assets/lang/he_IL.ini
  assets/lang/he_IL_invert.ini
  assets/lang/hr_HR.ini
  assets/lang/hu_HU.ini
  assets/lang/id_ID.ini
  assets/lang/it_IT.ini
  assets/lang/ja_JP.ini
  assets/lang/jv_ID.ini
  assets/lang/ko_KR.ini
  assets/lang/ku_SO.ini
  assets/lang/lo_LA.ini
  assets/lang/lt-LT.ini
  assets/lang/ms_MY.ini
  assets/lang/nl_NL.ini
  assets/lang/no_NO.ini
  assets/lang/pl_PL.ini
  assets/lang/pt_BR.ini
  assets/lang/pt_PT.ini
  assets/lang/ro_RO.ini
  assets/lang/ru_RU.ini
  assets/lang/sv_SE.ini
  assets/lang/tg_PH.ini
  assets/lang/th_TH.ini
  assets/lang/tr_TR.ini
  assets/lang/uk_UA.ini
  assets/lang/vi_VN.ini
  assets/lang/zh_CN.ini
  assets/lang/zh_TW.ini
Labels: User Interface, Code Cleanup

#20033 Use libpng's full API so we can ignore gamma. Fixes Driver '76's icon.
  Common/Data/Format/PNGLoad.cpp
Labels: User Interface

#20035 Allow binding Toggle touch controls to a custom touch button
  UI/EmuScreen.cpp
  UI/GamepadEmu.h
Labels: Touch screen

#20041 libpng full api: Remember to enable interlace handling, fix error handling
  Common/Data/Format/PNGLoad.cpp
  Common/Render/ManagedTexture.cpp
Labels: User Interface
